### ISSUE TITLE
If the curation contribution dialog is closed, don't clear the editor

### ISSUE THREAD

**Issue by mynameistechno** [clearlydefined/website#104]
If you close the modal dialog the editor is cleared. We may want to only clear after they submit, in case the user wants to edit the curation.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer  @mynameistechno is this still an issue?
If so, can you add steps to reproduce? The UI changed a lot since March so just want to make sure this is not outdated.

**Comment by jeffmcaffer** [comment]
closing. as @AlexWebYourmind says, a LOT has changed. we can reopen if there are problems in this space.
