### ISSUE TITLE
Bad links on new website home page  from "6 ways to get involved"

### ISSUE THREAD

**Issue by Jeffrey-Luszcz** [clearlydefined/website#1048]
Some links are not working on the new web website:

on main page:
https://clearlydefined.io/about

[Learn more](https://docs.clearlydefined.io/contributing-data)

[Learn more](https://docs.clearlydefined.io/adopting)

[Learn more](https://docs.clearlydefined.io/data-curation)

[Learn more](https://docs.clearlydefined.io/using-data)

when clicked on they go to "page not found" or equivalent

**Comment by mairaw** [comment]
Came to report the same. The Get Involved link is also broken.

**Comment by nickvidal** [comment]
Thanks @Jeffrey-Luszcz and @mairaw. This should now be fixed from both sides (from the website and clearlydefined repos).
