### ISSUE TITLE
"Not found" error when attempted to edit Documentation on web site

### ISSUE THREAD

**Issue by Jeffrey-Luszcz** [clearlydefined/website#1049]
If you go on the Documentation link and view the documentation you will see a button on the button of every page saying "Edit this page"

for example

[Edit this page](https://github.com/clearlydefined/clearlydefined/docs/get-involved/data-curation.md)

when clicking on that link you are brought to web page with error message reading "Not found"

for example: 
https://docs.clearlydefined.io/docs/get-involved/data-curation

this is for most? all? of the documentation pages.

**Comment by capfei** [comment]
@Jeffrey-Luszcz This is fixed now.
![image](https://github.com/user-attachments/assets/9cd9f078-f87f-4aa4-b9ad-16ff0aec0388)
