### ISSUE TITLE
Get Involved link doesn't work

### ISSUE THREAD

**Issue by elrayle** [clearlydefined/website#1056]
### Description

The Get Involved link at the top of the [website landing page](https://clearlydefined.io/) gets a 404.  It needs to be updated to point to the new website.

### Proposed Resolution

* look for all links that start with `https://docs.clearlydefined.io/`
* find the corresponding page in the [docs](https://docs.clearlydefined.io/)
* update the link to match the new page location

**Comment by Aysha-py** [comment]
Hi @elrayle , I would love to work on this issue.

**Comment by elrayle** [comment]
Hi @Aysha-py.  I really appreciate your willingness to jump in and take on an issue.  Unfortunately, this issue was fixed by [PR #1055](https://github.com/clearlydefined/website/pull/1055).  I am closing the issue.

Feel free to browse other issues to see if any are something you are willing to take on.
