### ISSUE TITLE
Keep state and URL in sync

### ISSUE THREAD

**Issue by mynameistechno** [clearlydefined/website#112]
E.g. if you browse for a component and click on the Curate link the URL is updated to include the component in the path. However if you select a new component in the filter list the URL is not updated. 

Can we come up with some strategy to cleanly keep state and URL in sync? We should look at what others do, e.g. https://github.com/reactjs/react-router-redux

**Comment by jeffmcaffer** [comment]
Seems like the UI has changed substantially and this is no longer a problem
