### ISSUE TITLE
Nginx configuration is not supporting HTML5 pushstate

### ISSUE THREAD

**Issue by baijum** [clearlydefined/website#118]
If somebody directly click the [about](https://clearlydefined.io/about) page, it will show `404 Not Found`.

**Comment by jpeddicord** [comment]
Oh my, so it does! I never noticed that; I think my browser is aggressively caching. Reviewing this now.

**Comment by fossygirl** [comment]
@baijum Thank you so much for your contribution! Welcome to the ClearlyDefined community! 🎊
