### ISSUE TITLE
Drag and drop a file and have it add to the browse list

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#124]
Users should be able to drag a file of any variety into the list section box of the Browse page and have the list populate with the components in the file.

**Comment by fossygirl** [comment]
Just updating this issue: @Teju-Manchenella has gotten drag and drop working for package-lock files. We would like to have drag and drop support other formats, likely things like .csv for users to put in the box as well.

**Comment by fossygirl** [comment]
Per https://github.com/clearlydefined/website/issues/41, adding context on types and formats:

The file could be

- ORT package dependencies file
- package.json, project.assets or any other fully resolve package manager dependency file
- CSV
- one entry per line
- JSON array

Where each entry might be

- various forms of canonical web URLs
- CD component specs

**Comment by jeffmcaffer** [comment]
Closing for now. As we see a need/demand for specific formats we can add them. Note that some of the things mentioned are also covered by other issues.
