### ISSUE TITLE
Sorting of the browse list

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#126]
We want users to be able to sort lists on the Browse page. 

They should be able to sort lists by: 

- ClearlyDefined score
- Type or provider
- release date
- Version (simple alphabetic sort)
- Name

Sorting should be ascending or descending. Users should also be able to clear the sort settings and return to seeing the list in its natural, as created order.

**Comment by fossygirl** [comment]
@Teju-Manchenella Do you have a PR merged that closes this issue? if so could you reference it here and close this?

**Comment by Teju-Manchenella** [comment]
@fossygirl as soon as I make some revisions on the PR this morning I will reference and close out this issue.

**Comment by Teju-Manchenella** [comment]
PR#200
