### ISSUE TITLE
Auto-completed string match

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#157]
Users can type any portion of the full ClearlyDefined coordinates and be offered a selection of matches from the ClearlyDefined data set. They can select one or more of the offered options and they are added to the list.

**Comment by storrisi** [comment]
Seems to be already in place. Typing a text in the search field returns a list of all the matching paths.

**Comment by AlexWebYourmind** [comment]
@storrisi Thanks! Closing this.
