### ISSUE TITLE
Drag and drop various list or identifying resources

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#159]
Often users have a list of interesting components they want to manipulate in the following ways: 

- The ClearlyDefined Components list should allow users to drag and drop their interests and have the component list populated. 
- ClearlyDefined should understand a wide array of formats from npm package-lock.json files to individual URLs for components on their respective provider. 
- Users should be able to choose to have an action replace or augment the current list.
- ClearlyDefined should make smart choices and picks the latest version of an indicated component that has a definition if for some reason the information a user provides is incomplete. 
- ClearlyDefined should be able to do some isolated version range interpretation from a package manager manifest files to find the latest component version with a definition.
- Users should be able to drag and drop a definition entry from one ClearlyDefined window to another to setup side by side comparisons.

**Comment by jeffmcaffer** [comment]
Closing in favor of individual issues for the different features
