### ISSUE TITLE
High level view of definitions

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#162]
Adding a component to the list should show users a high level view of the definition that includes:

- indications of type, provider, namespace, name, and version
- ClearlyDefined score
- Declared SPDX License expression
- Indicators as to whether or not the entry has any data at all in the system, been curated, or has outstanding contributions

**Comment by jeffmcaffer** [comment]
this is largely done. there are a few things that need to be finalized however. Some buttons to be removed. In addition, the "Add Source" button should be changes to 

* be smaller (i.e., just use an icon)
* have a tool tip that says something like "Add the definition for source that matches this package"

Also swap the order so the scores are always lined up on the right etc.

**Comment by fossygirl** [comment]
@Teju-Manchenella can we close this?

**Comment by Teju-Manchenella** [comment]
This is not fully complete yet according to the spec above. We still don't have all the specified indicators specifically whether a component has been curated and if there are any outstanding contributions. Everything else is completed.

**Comment by jeffmcaffer** [comment]
Let's just tweak
* the "Add source" UX and call this one done. need a good icon
* clear indicator that we do not have any data (i.e., the entry there is just a stub)

**Comment by gianpaj** [comment]
Regarding the icon, ideally it would be one that says "get source" or "retreive source".
Unfornately I didn't find anything from Font-Awesome like that.

Which one should we use?
These are the different PLUS icons and a "coding icon":

`fa-plus` icon:
<img width="1171" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/45763329-e28ecd00-bc38-11e8-9d1d-258c17e774c7.png">

---
`fa-plus-square` icon:
<img width="1173" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/45763406-0d792100-bc39-11e8-9670-54bf51e6032d.png">

---
`fa-plus-circle` icon:
<img width="1174" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/45763502-40231980-bc39-11e8-98d7-7f68b70f272e.png">

---
"coding icon" (`code-branch`):
<img width="1175" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/45764076-87f67080-bc3a-11e8-9c86-97853d13a0c6.png">

More icons here:
https://fontawesome.com/icons?d=listing&q=%22plus%22&m=free

**Comment by jeffmcaffer** [comment]
Using a verb (plus/add) is great but ambiguous. could be adding anything. Perhaps a noun oriented icon related to "code". So the branch (last) one is interesting. I'm leaning towards
   https://fontawesome.com/icons/code?style=solid
