### ISSUE TITLE
Filtering of the browse list

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#164]
Filtering should be independent of sorting. Users should be able to narrow their lists to, for example, just npms and yet still sort by release date. They should be able to filter by:

- Type or provider
- Release date (latest, after/before given date)
- ClearlyDefined score (greater or less than) and missing
- License (is or could be/is not subject to given license)

When the list is filtered users should see a clear indication that they are seeing a subset of the full list (including counts for subset and total) and also be able to clear the list and see all entries.

**Comment by fossygirl** [comment]
@Teju-Manchenella Do you have a PR merged that closes this issue? if so could you reference it here and close this?

**Comment by Teju-Manchenella** [comment]
@fossygirl as soon as I make some revisions on the PR this morning I will reference and close out this issue.

**Comment by Teju-Manchenella** [comment]
close PR #200
