### ISSUE TITLE
Drag and drop PR URL

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#170]
Users should be able to simply drag and drop the URL for a GitHub PR onto ClearlyDefined and end up with a definition list that identical to what contributor had when they made the contributions (except sorting and filtering). Users should also be able to click a link in the GitHub PR “Checks” UI to get to the same view on ClearlyDefined. Both of these allow users to go from raw GitHub Yaml PR files to the much more approachable ClearlyDefined view with which everyone is familiar.
 
The net effect of opening a PR on ClearlyDefined is a definition list view with entries for each component affected by the PR. From there users should be able expand each entry and dive into the full details view.

**Comment by storrisi** [comment]
@fossygirl @jeffmcaffer we can retrieve all the PR data using the GitHub API `GET /repos/:owner/:repo/pulls/:number/files` , which returns all the files in the PR, and then retrieve all the data from each single yaml file.

> Users should also be able to click a link in the GitHub PR “Checks” UI to get to the same view on ClearlyDefined

I'm not completely sure about this. There's any link into the "Checks" UI, except for commits.
Is that something that should be added?
I should investigate if we are able to add custom texts or links into the Check process.
Perhaps it would be better to separate these 2 features?

**Comment by storrisi** [comment]
@jeffmcaffer this implementation needs https://github.com/clearlydefined/website/pull/356 to be reviewed , in order to use the Provider class management
