### ISSUE TITLE
Date picker for editing Release Date

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#177]
When editing a date (e.g., release date) a contributor should have a first class date selection experience to ensure 

* they can easily find the date of interest
* the date is valid and syntactically correct

We expect to use a normal existing React date picker here but also should allow cut and paste of a date into a text input. Ideally that input would be quite flexible on input format. For exmaple, perhaps there is a reasonably flexible moment parsing strategy. The input can come in a variety of forms but the result should always be YYYY-MM-DD

**Comment by Teju-Manchenella** [comment]
Close PR #203
