### ISSUE TITLE
GitHub selector for specing source location

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#179]
A user editing the source location of a component should have a browse experience that guides them to a valid source location. Note that the source may come from GitHub, (eventually) GitLab and other source forges, as well as locations such as Maven source jars.

The user experience should be tailored to the source provider selected. This could be something like the harvest experience. In fact, it would be ideal if the same UI components could be used in both scenarios. Saves code and gives the user a more coherent experience.

**Comment by jeffmcaffer** [comment]
Talked with @valtterihalla about this and they are going to take a stab at this.

**Comment by daniellandau** [comment]
I'm thinking that we could reuse the harvest UI almost as is. Basically the below changes and opening it as a modal when clicking to edit.

![sourcepicker](https://user-images.githubusercontent.com/1044056/45219024-3bae4680-b2b2-11e8-9a0a-caa2c0d8a90a.png)

We do need to add at least the "just type a source URL" source picker before this can replace the current element.

**Comment by jeffmcaffer** [comment]
Likely true for the base components. Just reconfigure them in a different way. There is also a change in that at least for github we are not showing all commits, rather we are showing tags (with their associated commit).

In any event, yes, something like that that fits in a smallish dialog/modal/overlay
