### ISSUE TITLE
on Drop the user can choose to replace all or add

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#181]
Based on the context the user may want to drop a list and have all the entries added to the current list or have them replace. 

It may be acceptable as a first implementation to simply have a Clear button on the list. If the user drops and really wanted to replace then can click Clear first (or after and re-drop if they forgot).

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer is this different from the behaviour of the Clear All button?

**Comment by jeffmcaffer** [comment]
I suspsect that Clear All did not exist at the time this issue was created. We can close this one for now and re-open if we decide a more explicit drop workflow is needed.
