### ISSUE TITLE
Add "has been curated" and "has pending contributions" tags

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#187]
In a definition list entry there should be an indication of 

* whether this definition has been curated (that info is already in the "tools" list but should be more clear and should show up in the two line view)
* whether there are pending contributions for the definition. 

Both affordances should offer the user the ability to click and see the curation or contribution. Note that the first iteration of that can be quite simple and just take the user to GitHub or something. Future iterations can handle multiple pending contributions and a more ClearlyDefined-centric destination.

**Comment by storrisi** [comment]
This is implemented in #320

**Comment by AlexWebYourmind** [comment]
Closing this.
