### ISSUE TITLE
Export the list to a named file

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#188]
Allow the definition list to be exported (downloaded) as a named file.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer is this issue supposed to implement the Share --> Definitions functionality outlined in #271 , or can be closed as it's superceeded by the current Share --> file functionality?

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer any updates on this?
