### ISSUE TITLE
Show details of the score calculation

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#189]
The full details page for a definition should show the user how the definition's score was computed and perhaps indicate where the score was lower than expected and how it could be improved.

**Comment by pombredanne** [comment]
See also https://github.com/clearlydefined/clearlydefined/issues/61 for the new, improved scoring https://github.com/clearlydefined/clearlydefined/issues/61

**Comment by jeffmcaffer** [comment]
The UI for this has been added. Eventually we may have some full details on the scoring but that will likely come as push on the curation workflow
