### ISSUE TITLE
Determine deep link URL to definition details

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#193]
Need to pick the URL at which the details for a component will live. Make sure that it plays well with the other experiences and URLs (e.g, the ones that populate the definition list) and is not too  subtly different so as to be confusing.

**Comment by AlexWebYourmind** [comment]
Assigned to @storrisi. 

@jeffmcaffer @storrisi let's share a few URL suggestions here.

I was thinking about something like: https://clearlydefined.io/definitions/npm/npmjs/-/reason-react/0.4.2  where **https://clearlydefined.io/definitions** is the prefix and **"npm/npmjs/-/reason-react/0.4.2"** is the full path for the definition.

The problem in using **/definitions** is that we have already such a link on ClearlyDefined, pointing to the **browse** page. 
@jeffmcaffer should we consider to change the routing for the **browse** page to something else? Even tho it might still makes sense if we think that **/definitions** might be the listing route (e.g. **GetAll**) and /definitions/<definition_path> would be our **GetOne**
 
The only issue I see is that this type of routing is not very RESTful, as /definitions doesn't really return the list of existing definitions but a page where the user has to search for a specific one, but that might be an acceptable trade-off for now.

We can always review client routes later.

Let me know your thoughts @jeffmcaffer  and @storrisi

**Comment by jeffmcaffer** [comment]
done
