### ISSUE TITLE
UI: Contributing

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#195]
As a consumer of ClearlyDefined data, I sometimes find gaps or errors in the definition for a component in which I am interested. I love that part of the promise of ClearlyDefined is my ability to easily transition from a passive consumer of the data to an active contributor helping to improve the data. From a user experience point of view it is awesome that I can contribute my changes directly in the normal definition list and definition details UI as I search and browse the definitions. In particular, the following experiences really enable me to engage with the community.

**Comment by fossygirl** [comment]
@jeffmcaffer I think we might be able to close this? Can you confirm?

**Comment by jeffmcaffer** [comment]
pretty much done here
