### ISSUE TITLE
Revert individual or all changes to contributions made

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#197]
Everywhere that the user is able to propose a change (e.g., expanded or full view) they can also revert individual changes as well as all changes.

I the case of the definition list, the user can revert an individual change, all changes for an individual definition or all changes in the list. (note that if we end up doing multi-select, then reverting all changes in the selection would be a good option too)

**Comment by storrisi** [comment]
Hi @jeffmcaffer , just a quick clarification.
Should the user be able to revert a contribution-made, or is this something related only to changes not yet submitted within a contribution?

**Comment by jeffmcaffer** [comment]
changes not yet submitted.

**Comment by storrisi** [comment]
Thanks @jeffmcaffer , we've made a mockup proposal for this activity.
The purpose, as asked by the requirement, is to let the user to Revert a set of changes, or Revert them individually.
The only question is about the File List view: should the user be able to revert every single action into the File List or is acceptable to Revert it all in that case?

![schermata 2018-09-17 alle 15 34 47](https://user-images.githubusercontent.com/7654979/45626521-124ea100-ba90-11e8-8899-7bd234aa4e31.png)
![schermata 2018-09-17 alle 15 35 02](https://user-images.githubusercontent.com/7654979/45626520-124ea100-ba90-11e8-9d7d-6cc4c3a20e51.png)
![schermata 2018-09-17 alle 15 35 13](https://user-images.githubusercontent.com/7654979/45626519-11b60a80-ba90-11e8-93ec-197b1f916fbf.png)

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer any updates on @storrisi question + mockup?

**Comment by storrisi** [comment]
@jeffmcaffer this is how actually the implementation looks like on the Browse list
I've added a Tooltip on the Revert Changes button in order to give more information of the purpose to the user.

<img width="1419" alt="schermata 2018-09-19 alle 18 56 00" src="https://user-images.githubusercontent.com/7654979/45768641-c04b7e00-bc3d-11e8-8e6b-7bb2883800cf.png">
