### ISSUE TITLE
Facet picker 

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#202]
Just like the license and date pickers we want to use in our UIs for various views, we want to have a facet picker that lists the facets and allows users to select a facet. The main scenario for this is on the Full Details page for a component.

We will likely need to iterate on the design/flow of this. Starting off simple, perhaps something and leveraging the following assumptions:
* There are exactly 6 facets
* The `core` facet is not user-defined. Rather it is whatever is left over from not being in another facet
* Each facet is a list of globs
* Facets can overlap. that is, one file can be in multiple facets
* A very common case is that a folder and its transitive children are assigned to a facet

So a first cut might be something like 

facet | definition
----|---------
core | "everything that is not otherwise assigned a facet"
data | **/*.csv
dev |
doc | 
examples | src/examples/**/*.js
test | test/**/*.js, testrunner.js

Where
* the right side is just and editable CSV with each entry being a valid glob
* the right side may be empty. in fact it will typically start empty
* the core entry is a fixed string with content roughly as shown

Note: The table format above is just illustrative. Not intending this compoentn to show up actually as a table with borders etc. 

## Evolutions
As we go forward this component can get richer and richer. We should prioritize improvements based on user feedback.

1. Facet specs are validated
1. rather than being a plain, single line text input, the glob spec is a multi-line (one CSV element per line) UI affordance with the ability to add, delete, and modify rows. Each entry would have content assist for helping to complete the folder names etc.
1. As the user edits the entries above, the entries in the filelist are updated with their recomputed facet tags. If the file list is filtered by facet then the user will see just the files that are in the selected facet. That allows them to see the effect of their facet edits.
2. In the file list a user can select a **folder** and tag it with one or more facets. that would compute the relevant glob and add it to the specified facet(s).
1. Potentially users are able to click on a file in the file list and mark it with facets. The challenge here is in creating and maintaining the facet spec if the user is enumerating many individual files rather than creating a glob pattern

**Comment by jeffmcaffer** [comment]
addressed by #248
