### ISSUE TITLE
Build plugability model for new drag and drop support

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#204]
We want to enable users to be able to drag and drop pretty much anything into the component list and have that produce lists for them. 

We want to continue adding support for more kinds of things to drag and drop. And we want to enable contributors to add that support. So we need to make these integrations extensible, and so we need to have a plugability model for these. Would be great for someone to build that plugability model to enable new developers in the future.

**Comment by AlexWebYourmind** [comment]
Closing as #289 covers this.
