### ISSUE TITLE
Retrieve Multiple shield.io Badges

### ISSUE THREAD

**Issue by Teju-Manchenella** [clearlydefined/website#226]
Instead of retrieving 1 shield.io badge at a time, the retrieval should be batched so multiple consecutive badges are retrieved at the same time.

**Comment by jeffmcaffer** [comment]
Is this still relevant now that the UI is going straight to shields.io? in theory the browser should be caching etc.

**Comment by jeffmcaffer** [comment]
This seems obsolete
