### ISSUE TITLE
error in file list

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#233]
When browsing a set of definitions from a package-lock file I notice the following error in the Chrome console. Note that many of the components had no data in ClearlyDefined so various properties of the definitions would be empty.

@storrisi you might want to take a look

index.js:2178 Warning: Failed prop type: The prop `values` is marked as required in `PopoverComponent`, but its value is `undefined`.
    in PopoverComponent (at LicensesRenderer.js:23)
    in LicensesRenderer (at FileList.js:78)
    in div (created by TdComponent)
    in TdComponent (at TdCustomComponent.js:23)
    in TdCustomComponent (at treeTable.js:91)
    in TdComponent (created by ReactTable)
    in div (created by TrComponent)
    in TrComponent (at TrCustomComponent.js:32)
    in TrCustomComponent (at treeTable.js:93)
    in TrComponent (created by ReactTable)
    in div (created by TrGroupComponent)
    in TrGroupComponent (created by ReactTable)
    in div (created by TrGroupComponent)
    in TrGroupComponent (created by ReactTable)
    in div (created by TrGroupComponent)
    in TrGroupComponent (created by ReactTable)
    in div (created by Tbody)
    in Tbody (created by ReactTable)
    in div (created by TableComponent)
    in TableComponent (created by ReactTable)
    in div (created by ReactTable)
    in ReactTable (at treeTable.js:103)
    in RTTreeTable (at FileList.js:116)
    in div (at FileList.js:115)
    in FileList (at PageInspect.js:165)

**Comment by storrisi** [comment]
I will fix this, probably it needs a check if the data are empty.
Could you please share what is the definition that gave you the warning?

**Comment by jeffmcaffer** [comment]
actually I was looking at http://localhost:3000/inspect/npm/npmjs/-/amdefine/1.0.1

There is a 404 as that component has no curations (that's ok) Then in the fileList if you expand the various folders, the above stack trace appears.

**Comment by storrisi** [comment]
I've submitted PR #235  that fixes this issue
