### ISSUE TITLE
Clicking into a field that runs off doesn't work as intended

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#246]
If you click into a field on a definition that runs off the field and then click away the text then overruns the text block, doesn't display the edit pencil, and doesn't snap back to the beginning of the field.

![screen shot 2018-08-15 at 11 03 02 am](https://user-images.githubusercontent.com/17101092/44164527-219a9300-a07b-11e8-9fce-5f9ac34b11ad.png)

**Comment by AlexWebYourmind** [comment]
Hi @fossygirl . We are introducing a fix for this issue as part of #231 .
