### ISSUE TITLE
Add a "validated" button

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#247]
Contributors and curators will want the ability to look at a ClearlyDefined definition and then, if it's already accurate and doesn't need curation, mark that they have reviewed it. We should add a "validated" button so curators know someone (or they) have reviewed it and believed it to be correct.

**Comment by AlexWebYourmind** [comment]
Hi @fossygirl ! Is this button supposed to be both on the Browse view and the full detail view?

Besides, what will the workflow around this functionality? (Who can click on "Validate", anyone? What happens after the button has been clicked from a technical standpoint?)

**Comment by fossygirl** [comment]
@AlexWebYourmind I don't think we need it on both, probably just on the Browse view. The use case here is for someone to at a glance be able to know if something has been validated and to be able to validate it if it hasn't been quickly. 

I would assume the group of people who can merge curations would also be the people who can validate, so it would only show up for them.

**Comment by fossygirl** [comment]
@jeffmcaffer I'm going to close this for now unless we decide this is actually useful and want to reopen.

**Comment by fossygirl** [comment]
Reopening with @dabutvin

**Comment by storrisi** [comment]
@fossygirl may i ask you an update on this?

Starting from your last comment:

>@jeffmcaffer We talked about this briefly a few weeks ago. We actually may not want to do this because we may then need to mark everything as "validated" and so it becomes a useless signal. I think we should close this?

There are some changes about this kind of identification, and the resulting workflow?

**Comment by fossygirl** [comment]
@storrisi Yes, we'd like users to be able to validate a license.

**Comment by storrisi** [comment]
Thanks @fossygirl ,
so i guess that a "validation" value should come from the service (if available) for each browsed definition.
If a definition is not already validated, someone should be able to hit a "validate" button that confirms the validation, and send back the action to the service again.

Can you confirm this workflow?

Just a few questions:
- you mentioned that
> I would assume the group of people who can merge curations would also be the people who can validate, so it would only show up for them.

Is this still valid? If yes, i actually don't know how to identify those users, maybe they have a specific permission on github? @dabutvin can you help me on this?

- Could the action be "revertable", if someone consider validated a definition that is not really valid, or hits the button by fault (i think that a confirmation dialog is required here)?

- Should we add a Validation filter to the Browse page, that removes from the list any already valid definition?

A little bit of implementation from the service is required here, so probably an issue should be opened in the service repo.

@dabutvin do you have any additional question or doubts on this?

**Comment by storrisi** [comment]
@fossygirl @dabutvin do you have any updates about my questions above? thanks!

**Comment by storrisi** [comment]
As discussed in today's meeting, we'll have a future discussion about this specific topic.

**Comment by nellshamrell** [comment]
Closing this for now due to age, but if anyone would still like to discuss this, please feel free to re-open it.
