### ISSUE TITLE
Filtering on full details page is confusing

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#252]
This might be a case sensitivity issue? But for now, when I filter on a field in the full details view:

![screen shot 2018-08-16 at 1 49 53 pm](https://user-images.githubusercontent.com/17101092/44234479-89c0a600-a15b-11e8-83ed-915bd0522a80.png)

It does not produce components that I as a user would expect to be present in the list based on the full component information:

![screen shot 2018-08-16 at 1 50 26 pm](https://user-images.githubusercontent.com/17101092/44234511-9ba24900-a15b-11e8-8064-c2259e5ccf9e.png)

We may not be displaying MIT because I typed in lower case, but if that's true, we should allow user entries to not be case sensitive. Or it may be a bug. Either way... 😄

**Comment by storrisi** [comment]
Thank you @fossygirl , filtering methods are case sensitive for each field. This has already been fixed in PR #248
