### ISSUE TITLE
"Dig In" to `async-limiter` package shows white screen

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#254]
![2018-08-21 10 26 15](https://user-images.githubusercontent.com/5168796/44418231-b0e8f000-a52c-11e8-8210-779f1a33b7a7.gif)

See the GIF. The other packages I tried show the modal appropriately.
It's something specific to `async-limiter`

**Comment by storrisi** [comment]
Thank you @dabutvin , i will check into this
