### ISSUE TITLE
UI should allow for adding multiple declared licenses

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#255]
Right now the Browse UI for editing components only provides one drop down and only allows you to add one declared license. For components that have multiple licenses, we should enable curators to add multiple licenses to the component.

**Comment by jeffmcaffer** [comment]
Adding to that, licenses are more generally *license expressions*. The typical case is just one license but our license picker should have a way of the user entering a valid SPDX license expression.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer @fossygirl allowing this type of behaviour will probably require changes on the schema as well, given that right now "declared" license is a simple string . 

Can you confirm we need to allow multiple SPDX license Expression? or should we just focus in entering single licenses in the SPDX expression form?


![image](https://user-images.githubusercontent.com/8700407/44453610-5feeff80-a5f1-11e8-8bf5-49d975e59577.png)

**Comment by fossygirl** [comment]
@AlexWebYourmind For example, this component shows the declared license as BSD and MIT. I don't think we want to change the schema since the schema is clearly allowing this information in the declared license for components. I think we just need to change the user's license picker or picker UI to enable them to do the gesture that can produce something like "BSD and MIT" if that's appropriate.

![license](https://user-images.githubusercontent.com/17101092/44542693-6b5e2b80-a6c2-11e8-8130-193e02148fca.png)

**Comment by fossygirl** [comment]
@AlexWebYourmind Can we just have another picker appear after the first one is changed or clicked on? But have them all be optional so if the user doesn't choose a second, third, etc license they can still submit the proposed curation with one license?

**Comment by AlexWebYourmind** [comment]
@fossygirl not sure about what you mean, tbh (But I might just need further details).  Implementing as you have suggested, we would not be able to account for OR and AND conditions and the UX wouldn't be great, in my opinion. @storrisi what's your view on it?

**Comment by jeffmcaffer** [comment]
a few comments here.

1. The discovered list in the panel is a collection of the info found on the relevant files. It will never be editable. The actual license info is on the individual files. It needs to be editable there
2. the value for each file is a single [license expression](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60). today we allow picking a single license. In the future we need a license expression "editor"
3. The Discovered license on a definition is also a single license expression. That is editable on the list entries and in the full details view and should use the same UI affordances as the file level license UX.
4. The 80% case is a single license so we can optimize for that.
5. The expression editor can start of simple and evolve. While technically expressions can have all manner of stuff in them, most are simple AND and OR clauses.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer Thanks for your comments

1. Absolutely, I have highlighted the "Discovered" one more for its content (Multiple Expressions rather than a single one), assuming that it should be allowed to enter something like that (in the Declared section and in Files) 

2.  Ok. Makes sense and still recommend to mock the interaction
3.  That's what we thought as well. Makes sense. 
4. Good to know, let's start with single license expressions
5. Ok.

Agree in having it as a separated component, we can create it under a new clearlydefined/xyz repo.

**Comment by jeffmcaffer** [comment]
Sorry @AlexWebYourmind I forgot a point. We may well (likely) remove the Declared license entry from the top level information. That is, the aggregate of all the license

**Comment by mynameistechno** [comment]
When I added the simple spdx single license picker I came across this npm module that parses spdx expressions: 

https://www.npmjs.com/package/spdx-expression-parse

We could use it to validate expressions and also store the the individual ids, etc:
```js
assert.deepEqual(
  // Licensed under a combination of:
  // - the MIT License AND
  // - a combination of:
  //   - LGPL 2.1 (or a later version) AND
  //   - Three-Clause BSD
  parse('(MIT AND (LGPL-2.1+ AND BSD-3-Clause))'),
  {
    left: {license: 'MIT'},
    conjunction: 'and',
    right: {
      left: {license: 'LGPL-2.1', plus: true},
      conjunction: 'and',
      right: {license: 'BSD-3-Clause'}
    }
  }
)
```

**Comment by AlexWebYourmind** [comment]
@mynameistechno I actually stumbled upon that very module a while ago. Yeah that would be handy for validation.

**Comment by pombredanne** [comment]
reopening based on comment from akirezurc on discord:

>With regards to the note: "how to handle properly the case of multiple licenses with a choice? Should we as curator pick one of the licenses? Since we are curating for others, we should not make a license choice... instead the plan is to use SPDX expressions: they are the way to go for these cases. But the the UI does not help edit these properly today: we would need some UI help to enter such valid expressions."
I found this feature request https://github.com/clearlydefined/website/issues/255 that was raised some time ago and is relevant to the problem at hand: declaring multiple SPDX licenses (i.e. conjunctive “OR”). Is this issue closed indefinitely, or has it been incorporated into a longer term goal to implement such functionality?
