### ISSUE TITLE
Need a Font Awesome icon for Harvest

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#260]
Want to provide users an icon for Harvesting.

**Comment by AlexWebYourmind** [comment]
@fossygirl @jeffmcaffer  what about one of the available leaf icons as a start?

![image](https://user-images.githubusercontent.com/8700407/44798605-d53a7180-aba9-11e8-8694-3fef3db0b21c.png)

**Comment by fossygirl** [comment]
@jeffmcaffer I like the leaf, any thoughts? 😄

**Comment by storrisi** [comment]
I've searched into the fontawesome library and i hadn't found anything suitable for "harvesting".
So i've followed the suggestion by @jeffmcaffer , and these are what i've found:
![schermata 2018-10-19 alle 15 23 12](https://user-images.githubusercontent.com/7654979/47221079-cb680a00-d3b3-11e8-925b-0aef40e0341d.png)
![schermata 2018-10-19 alle 15 23 06](https://user-images.githubusercontent.com/7654979/47221080-cc00a080-d3b3-11e8-9f88-270eefae9b56.png)
![schermata 2018-10-19 alle 15 23 00](https://user-images.githubusercontent.com/7654979/47221082-cc00a080-d3b3-11e8-83e4-171fb41cb912.png)
![schermata 2018-10-19 alle 15 22 53](https://user-images.githubusercontent.com/7654979/47221084-cc00a080-d3b3-11e8-8be0-6c701d648711.png)


@fossygirl is this icon supposed to be used in the Harvest Button into the Harvest Page only?

**Comment by storrisi** [comment]
@jeffmcaffer @fossygirl any updates on this?

**Comment by storrisi** [comment]
@fossygirl @jeffmcaffer any updates on this?

**Comment by fossygirl** [comment]
You can just ignore this for now, we’ll talk about it next week.

**Comment by fossygirl** [comment]
@jeffmcaffer Have you made a decision here? Let's just pick one and close this out.

**Comment by storrisi** [comment]
@jeffmcaffer @fossygirl thanks for the decision.

I guess it should be added to the Harvest button in the Harvest page, is that right?

**Comment by fossygirl** [comment]
@storrisi @jeffmcaffer Is this implemented and we can close? This is a tiny thing and I'd really, really like to just be done with it.

**Comment by storrisi** [comment]
@fossygirl i'm able to do it in a short, but i need to know where this icon should be added

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer @storrisi What's the latest on this issue? I see that assigned to Jeff. Does that mean that Jeff will place the icon? If not, please re-assign to @storrisi and we'll get this sorted asap.

**Comment by fossygirl** [comment]
I'll close this.

**Comment by AlexWebYourmind** [comment]
@fossygirl Thanks for following up/Closing on this. Does that mean that the issue have been already addressed?
