### ISSUE TITLE
consider lzma compression for sharing urls

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#261]
When we share a URL the amount we can share depends on the size of the resultant URL. Compression there is key. consider compressing the URL rather than (or before?) Base64 encoding. Look at https://www.npmjs.com/package/lzma as a common compression technique (used in https://itty.bitty.site)

**Comment by storrisi** [comment]
We've looked into this making some test on Izma compression with a huge package-lock.json file.

From our tests looks like that the current compression method used by the website (pako) works better than Izma.

If you take a look at [this test](https://runkit.com/embed/0d068m141kax) you can see that the same object compressed by pako is actually shorter than the same compressed with Izma.
