### ISSUE TITLE
add affordance to refresh definition

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#265]
A common workflow is to work on a definiton, submit a curation and then when it is merged, take a look. Unfortunately, (well sorta) the UI caches the definitions indefinitely. That means the only way to get the new definition on the screen is to reload the web page. Not a great experience.

Some possible answers
* have a refresh button somewhere that re-fetches all the definitions in active use (visible, changed, ...) 
* have a refresh button on each definition
* have push notifications telling the UI that something has changed

The push notifications is a great eventual goal but it brings in a lot of other topics. 

For now I suspect we need a refresh button that the user can hit when they are interested in seeing what's up with the outside world. Simplest is like the first one that just reloads all definitions. Note that it may be that things with pending changes will no longer be changed (e.g., someone merged the same change you were going to propose). that's actually a good outcome. making it an explicit user action means they should not be surprised and they have control.

**Comment by gianpaj** [comment]
Hi Jeff,

We discussed this and we think the first approach is to have a 'Refresh All' button in the Browse page.
We can add an additional 'Refresh' button in the Modal and Full Details Page, at a second stage.

Is that acceptable?

Few questions on the details of the single 'Refresh All' button:
1. Can a user refresh all if they have some pending changes?
2. Assuming yes to the 1st point, what happens to those changes? Should we simply alert and discard them?
  One use case, you mentioned above, was:
    - if a user has e.g. pending changes A, B, C (copyrights)
    - he refreshes, and another user has already changed C (copyrights).

    Or should we do a diff between the updated definition coming from the API and the user's pending changes and only keep changes A and B?
While this is doable, it would add some complexity and development time.

Thanks

**Comment by jeffmcaffer** [comment]
Hey @gianpaj, the first step should likely just tell the user they are going to lose their changes with OK/Cancel. In the future you could imagine just slipping a new def in under their changes. their changes are held separately so they'll still be there. 

So for example, the user changes Declared license from GPL to MIT. Then refreshes and the license has already been changed. They still have a pending change (technically) but the UI would likely already show no change and we could do a "simplify" step to update the `changes` prop on the component.

Simplifying for things like copyright lists may be a little more complicated. In the end the user will need to review the new state of the world and merge.

Anyway, lets start simple and evolve as the users/usecases demand

**Comment by gianpaj** [comment]
Great. We'll start with a single 'Refresh All' button that will discard all the user's pending changes after they confirm on an alert message
