### ISSUE TITLE
Opening full details on a curation fails and reloads the page.

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#269]
When you access .../curations/ you should see a view with all the changed definitions listed. If there you click on the magnifying glass for one of the components listed the full details page should open. That currently fails and just the curations page just reloads.

I've not had time to investigate

**Comment by storrisi** [comment]
Hi @jeffmcaffer , is this something related to #267 ? 
We need a real URL to check this out, could you please provide one so we can test it and solve it?
Thank you!

**Comment by jeffmcaffer** [comment]
I was not able to repro in dev. For exapmle, I tried https://dev.clearlydefined.io/curations/185 and it worked fine.

There is definitely some quirks in this space but this issue may not capture. I'm going to close and reopen if necessary.
