### ISSUE TITLE
file license changes not showing

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#270]
1. Go to https://clearlydefined.io/definitions and pick npm async/2.6.0.
2. open the full details view
3. expand to show a file
4. change the license for a file
5. the file list collapses so re expand and notice that your change is not showing
6. click Cancel and notice that the system thinks there are changes

Seems like the change is being recognized but not showing.

**Comment by storrisi** [comment]
Actually this something related to some change happened on the service side.
The API for the preview returns an error: 

> Unknown↵data.files[1].attributions should be array, data.files[2].attributions should be array

The `attribution` param for a file, if empty, is passed as an empty string.
We assume to change that and consider `attribution` always as an array, according to the schema, even if empty.

Is this correct?

Thank you @jeffmcaffer

**Comment by jeffmcaffer** [comment]
The attribution prop (actually pretty much all props) should be absent if they do not have a value. I went through the service and cleaned up place where that was wrong.  So when you submit a proposed curation, please make sure that props either have a useful value or are absent.  Sorry I missed the impact of this change for you.

There is likely a change in the server to validate the incoming curations so you would have gotten a 400 not a 500

In the crawler and service we've tended to use a helper `setIfValue` which is like lodash.set but only sets a prop if there is a given value.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer the changes applied on the services side of things makes sense. We will address this and make sure to send the correct data.

**Comment by storrisi** [comment]
This is something that would had an impact to the contribution process i guess, given that the patched data are the same sent to the preview API

**Comment by jeffmcaffer** [comment]
right. on the service we should validate the the incoming curation to preview and bounce it before doing any compute. Ideally the UI is also validating before it sends to the service.
