### ISSUE TITLE
merge the share buttons

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#271]
Currently there are two share buttons, Share and Share URL. In the future there will be more ways to share. We should change this to be a single Share dropdown which has entries for "URL" and "File". The function from there should be the same. 

Note that examples of future entries are

* "Definitions" (would write a file in JSON format containing all the actual definition text, 
* "SPDX" Same as Definitions but the file would be in SPDX format

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer @gianpaj @storrisi  Adding mockup of how we could realize this feature.

![image](https://user-images.githubusercontent.com/8700407/44797544-5cd2b100-aba7-11e8-8a9c-05cd2d0a3d10.png)


Component we could use --> 
https://react-bootstrap.github.io/components/dropdowns/

**Comment by jeffmcaffer** [comment]
fixed by #275
