### ISSUE TITLE
Enhance contribution/PR descriptions

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#282]
Right now the freeform text for a curation commit message is blank. We should automatically add an @mention of the person's username to the message so they will automatically be notified of messages on the pr later.

**Comment by jeffmcaffer** [comment]
see also this copied over from #51 

In addition to style improvements, we should try to put some sturucture to the pull requests. Effectively a PR template. Don't have to get too fancy but something like is shown below. Given that, what is the best UI we can do to get the right result. (e.g., dropdowns for enum fields, ...)

**Type:** [ Missing | Incorrect | Incomplete | Ambiguous | Other ]

**Description:**
<free text describing the problem being addressed ...>

**Resolution:**
<what does this PR do to address the issue ...>

**Supporting info:**
<references to docs where the new data was found, pointer to public conversations with the affected project team, ...>

**Comment by jeffmcaffer** [comment]
I updated a few of the suggestion and added a "title" field to be used as the commit message and PR title.

**Comment by storrisi** [comment]
Hi Jeff, we have some questions about the issue:
- In your suggestions we don't see the @mention anymore. Is this not longer part of the task? 
- In order to add the Contributor's username (if the user is logged) should the service add that automatically, or should the UI retrieve the user from GitHub?
- Should we sent all the information as a formatted string, maybe using MarkDown markup, or  should the service needs to be updated in order to accept a structured object?
- As confirmation, these should be the submitted fields by the user from the UI:
  - Summary (mandatory)
  - Type (dropdown menu, mandatory)
  - Details (mandatory)
  - Supporting info (mandatory)
  - Resolution
- As confirmation as well, these should be the fields filled automatically by the service:
  - Contributor's username
  - Affected definitions (automatically generated, cannot be edited)

**Comment by jeffmcaffer** [comment]
Answers

* yes, user's username
* if they are not logged in, the UI should guide them to do so however, we have to be careful to not lose the data they have already entered. If that is at all hard, for now we can stage this and for not, just tell them that the contribution will be anonymous and in the future they should login.
* info should be sent as a json object. The service will be in charge of structuring etc.
* the submitted fields are correct (to be clear, we will change these over time). 
* the computed fields are correct (they too will change over time)

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer 

> info should be sent as a json object. The service will be in charge of structuring etc.

Should we open an issue on the service repo to address this?

**Comment by jeffmcaffer** [comment]
yup. thought there was one but I don't see it right now. Please open and cross link

**Comment by storrisi** [comment]
@jeffmcaffer , here is the first implementation of the UI. The service side will be developed in https://github.com/clearlydefined/service/issues/233

This is one option on how to prompt or guide a user to Login, if the they are not:
<img width="571" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/45555409-64e64e00-b841-11e8-908a-10084c4530eb.png">

> if they are not logged in, the UI should guide them to do so however, we have to be careful to not lose the data they have already entered. If that is at all hard, for now we can stage this and for not, just tell them that the contribution will be anonymous and in the future they should login.

Currently, when you log in it opens a new tab for Github Auth and doesn't lose your current changes when you finish logging in.

- Do we want to show the username if user is logged in?
If that's the case we need the service to return the username from the `/auth/github` callback script.
https://github.com/clearlydefined/service/blob/master/routes/auth.js#L61

**Comment by jeffmcaffer** [comment]
@storrisi this looks great! A few suggestions/comments

* Yes, lets show the user name if we have it. Sort of surprised we don't already. Would be good to show it in the UI normally to indicate that the user is logged in etc. (but that's a separate topic)
* Summary could potentially be one line in the UI. We should limit it to 100 chars (and indicate that in the UI)
* I'm rethinking the `supporting info` and `Resolution` sections. The value is that forcing the "supporting info" calls out that you need to substantiate your changes. On the other, folks may be confused as to difference between Details, Supporting info, and Resolution. Feels like we should combine Supporting Info and Resolution into on field called Resolution where the help text is a combination of the current text in both fields.
* what are the possible Type values?
* We could put the Type selector up beside the Contributor
* Eventually we should put a summary list of the definitions being modified here so the user can check that they are actually doing what they think they are. (that can be added incrementally later)

**Comment by gianpaj** [comment]
> Yes, lets show the user name if we have it. Sort of surprised we don't already. Would be good to show it in the UI normally to indicate that the user is logged in etc. (but that's a separate topic)

Great. I'll work on that.

> Summary could potentially be one line in the UI. We should limit it to 100 chars (and indicate that in the UI)

I've made the first change. Regarding the limit, I've indicated the limitation in the placeholder text. If we want to show a counter we could use this https://github.com/isaachinman/react-bootstrap-character-counter

> I'm rethinking the supporting info and Resolution sections. ..

Sounds good. I've done that. We can improve further the placeholder text. I've put this for the moment:
`What does this PR do to address the issue? Include references to docs where the new data was found and, for example, links to public conversations with the affected project team`

> what are the possible Type values?

See the screenshot below. They're the same as listed above by @storrisi.

> We could put the Type selector up beside the Contributor

done.

> Eventually we should put a summary list of the definitions being modified here so the user can check that they are actually doing what they think they are. (that can be added incrementally later)

Sounds good. Let's add this in the UI in a second stage. Note that the server will add this list in the description of the PR.

<img width="672" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/45629895-28fcf400-baa0-11e8-98c5-208950a69d91.png">
