### ISSUE TITLE
Full Details View - Filtering doesn't work on editing data

### ISSUE THREAD

**Issue by AlexWebYourmind** [clearlydefined/website#283]
Steps to reproduce:

1. visit https://dev.clearlydefined.io/definitions/npm/npmjs/-/async/2.6.0
2. Enter "MIT" in the Filelist License Filter
3. Verify the Filelist displays only the files with MIT licensing
4. Edit one of the files, and change it's license to "Aladdin" or anything else
5. Repeat 2.
6. Verify that the edited file still appears, while it shouldn't given that its license is no longer "MIT"

  
![image](https://user-images.githubusercontent.com/8700407/44914027-dba22800-ad26-11e8-8fe8-c2458df800e5.png)

**Comment by AlexWebYourmind** [comment]
Let's make sure to verify if this needs to be fixed also for the other fields.

**Comment by gianpaj** [comment]
I've tested editing Facets, Licenses and Copyrights.
The only filter that's not working is Licenses

**Comment by AlexWebYourmind** [comment]
Reopen as we need #285 to be reviewed first.
