### ISSUE TITLE
Full Detail View - Editing Copyrights inside the File Edit is confusing

### ISSUE THREAD

**Issue by gianpaj** [clearlydefined/website#284]
The current workflow when updating a file's Copyright is to:
1. Click on a copyright
2. Add or edit a current copyright inside a Popover
3. Click "Done" to save the changes made inside the Popover
4. Contribute the updates made on the definition
    - If you're in the Modal, click "Ok" and then "Contribute"
    - If you're in the Full Detail Page, click "Contribute"

In step 3, if you don't click "Done" and click outside the Popover, the changes will stay in the popover but the Full Detail View won't know you made any changes.
As you can see in the gif, the green "Contribute" button is disabled, until you press "Done"

![aug-31-2018 18-41-47lowframrate](https://user-images.githubusercontent.com/899175/44922824-1b7d0580-ad4f-11e8-9a98-f633bba9b300.gif)

Possible solutions are:
1. Keep the Popover open when editing, so the user MUST click on "Done". Making sure to allow the close the Popover when there are no changes (read-only)
2. Ideally, when the Popover is closed, as the user clicks outside, those edits should be visible to the Full Detail View

**Comment by AlexWebYourmind** [comment]
@gianpaj let's go with 1. "Keep the popover open when editing" as it seems to be the most obvious solution to the user (clicking on Done will close the popover) and will prevent from inadvertently clicking outside while editing.

Let's keep in mind that click-outside-to-close should be still allowed in Copyrights read-only mode.
