### ISSUE TITLE
remove stale code

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#287]
There are a number of routes and components left over from old UI approaches (e.g., Curations). Remove this.

**Comment by storrisi** [comment]
Hi Jeff,

After looking at the website routes there are 2 that look like are not being used:
- `/curate`. This shows a Current curation and Proposed curation. Should we remove this route? ([screenshot](https://imgur.com/a/EUepRlL)) 
- `/inspect`. This has been replaced by the FullDetailsView,  and this route is not linked from anywhere anymore, except https://docs.clearlydefined.io/using-data . Should we remove the route and associated component, as well as update the docs?

**Comment by jeffmcaffer** [comment]
@storrisi sounds good. We will end up adding back some of the routes but it's better to delete and then add as needed.
