### ISSUE TITLE
SPIKE: "Push notifications" for data changes

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#288]
As a user of the Definitions page (and others?) I want to be told when the definitions I am looking at have changed. Specifically, if I have done (or am doing) changes, it would be great to know that the underlying data has changed so I can adjust or eliminate my changes.

For this initial effort we should look at design and technology options and come up with a plan. From there we can look at when and how to implement,

**Comment by storrisi** [comment]
Documented in https://docs.google.com/document/d/1BeFUFa25nau3gW3nOhBZ3jv1YL-BjyrBthIVyLeznhg/edit?usp=sharing

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer closing this.  feel free to reopen if needed.
