### ISSUE TITLE
context help in the curation editor

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#29]
Monaco has the ability to add content assist (eg., auto complete). Based on the new schemas we have, we should be able to add content assist.

This is very related to #30 and likely should be done at the same time/by the same person

**Comment by storrisi** [comment]
Since this is related to #30 which has been closed because considered obsolete, since the way to contribute has been changed over time, than probably this one is closable as well.

**Comment by AlexWebYourmind** [comment]
Closing this.
