### ISSUE TITLE
I cant see all the attributions in the Attribution field at https://clearlydefined.io/definitions 

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#294]
In the Attribution field, it will list multiple copyrights and then just have ….  I cant see them all.  And then when I click on magnifying glass, I then have to open ALL the files to find all the copyrights?  And then if I click on one, I get a pop-up window, where I still cant easily see the whole copyright.

**Comment by fossygirl** [comment]
@AlexWebYourmind Can you take a look at this, please?

**Comment by AlexWebYourmind** [comment]
@fossygirl This would probably be an enhancement to the current UI View.
As @ariel11 correctly said, the current way to see the full list of copyrights is navigating file by file.
![image](https://user-images.githubusercontent.com/8700407/45083901-d6612680-b0f4-11e8-862d-8cf0c5b6dfc2.png)

@gianpaj The quickest way to address this (we should review the overall UX as we go) is to add a Read-only popover (with vertical scrollbar) that allows the user to see the full list of Copyrights when clicking on the **Attribution** content. 

This would be consistent with the fileview experience we have right now, and enable a user to see the full list of Copyrights without having to look on each single file.
