### ISSUE TITLE
Can we increase the character limit on the contribute button?

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#295]
I would like to be able to say "Updated [license or copyright] per commit [insert URL]" but I run into a character limitation and it cuts off the URL.  It would make the person's job who is validating the change a lot easier to have the URL the contributor is using for vetting/reference.

**Comment by gianpaj** [comment]
The current limit of the "Short description of changes" is 100 characters.

@AlexWebYourmind, @jeffmcaffer and @fossygirl, I'm happy to increase this. What should be a higher number?

You can see the input text here, after making a change to the definition and press Contribute:
https://clearlydefined.io/definitions/npm/npmjs/-/extract-opts/2.2.0

**Comment by fossygirl** [comment]
@jeffmcaffer I don't see why we couldn't make it 1,000; 2,000...is there a reason at all it needs to be a low number?

**Comment by AlexWebYourmind** [comment]
@fossygirl @jeffmcaffer we are happy to increase the limit as a short term solution.

https://github.com/clearlydefined/website/issues/282 , when implemented, will definitely result in a much better experience.

**Comment by dabutvin** [comment]
You could break the field out to a title and a description and format that into the commit message. Leave the 100 character limit for the commit title and the rest for the commit body.

**Comment by jeffmcaffer** [comment]
suggest we just implement #282. should be a half day job...

**Comment by jeffmcaffer** [comment]
closing this in favor of #282
