### ISSUE TITLE
'Share' links with a sort setting is not reflected in the list

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#303]
The selection is there in the 'Sort By' dropdown, but the list itself is not sorted. Probably some kind of timing or ordering issue.

Here is an [example share link](https://clearlydefined.io/share/eJy9VU2P2kAM/S85sxb5DtyA7ba0pa2WZVu16mFIHBg1mYlmJqyyiP9eQwNSCJdQ2hMKI/vZfu/ZWyvlmUFlDbe7nqWlMuPKGlqC5Wj1rFhKlXDBDGpr+GNrmarA/Wu5QkPPhZIbnuyDT38dAofWjMdKapkaeOa6ZNnclAmXsDA844ajhqkgUMEyClG44ZpLQWG2B30IB3c50/Qcpt6Aeehau97fQz9hhjkaVZ0h+hDCwHNqyCAY2FG0xG6Q84pic5h+htFSG8ViQ8l1E8gBm3qzw6Bj6jVTxXdefOTLZr4+RAH0bzKaR8ylwYkURslLhDiBW4+HBUGaupHXDfYby5niAkYiUZIn8HBoimC1LFWMX46BTWQCJmj/2g6nCQrDTTWTCWYwyTh9ahgRNRu85wpjI8+14IDjgtt3nMCOvPA/ArswqHH9fnTHsmLNbkLsfs6YwLOeUC33uCxXNGsj4xbL/l6a/Yh+7X9stggG/tFsthPZtp8mt4FcK2S0q1YtSBecq33ylYtEvujRa6kQyCEpX5WK7e09Y4Kt2qINu3qyy+7o6Ltj6oYgn+QvFBrev5gmxsHoNKnAcWzX7yiDy02QDLQhRt5hVqC6TU8NQuaoNjzGcdnK3VnIxx31tuQLwc2n1blDQ6rX6ZbzYfThzfmQA7trZfW2nMi84BmqY9NnHbv7YV6tclzSQU4VuVKVsaHRXtjFVyliRqflfAt43dmps43LNG0JyQPvRnfwtELoUrGsem1B0TIJwOt6wf/U/liSCXM88VjTqGEhNEuxPSLq6efuN6MIMNg=) to demonstrate

![2018-09-19 10 26 20](https://user-images.githubusercontent.com/5168796/45770184-87d48180-bbf6-11e8-9bf1-56e3d26231fc.gif)

**Comment by storrisi** [comment]
This doesn't seems to happen anymore on dev.clearlydefined.io

[example link](https://dev.clearlydefined.io/share/eJy9VU2P2kAM/S85sxb5DtyA7ba0pa2WZVu16mFIHBg1mYlmJqyyiP9eQwNSCJdQ2hMKI/vZfu/ZWyvlmUFlDbe7nqWlMuPKGlqC5Wj1rFhKlXDBDGpr+GNrmarA/Wu5QkPPhZIbnuyDT38dAofWjMdKapkaeOa6ZNnclAmXsDA844ajhqkgUMEyClG44ZpLQWG2B30IB3c50/Qcpt6Aeehau97fQz9hhjkaVZ0h+hDCwHNqyCAY2FG0xG6Q84pic5h+htFSG8ViQ8l1E8gBm3qzw6Bj6jVTxXdefOTLZr4+RAH0bzKaR8ylwYkURslLhDiBW4+HBUGaupHXDfYby5niAkYiUZIn8HBoimC1LFWMX46BTWQCJmj/2g6nCQrDTTWTCWYwyTh9ahgRNRu85wpjI8+14IDjgtt3nMCOvPA/ArswqHH9fnTHsmLNbkLsfs6YwLOeUC33uCxXNGsj4xbL/l6a/Yh+7X9stggG/tFsthPZtp8mt4FcK2S0q1YtSBecq33ylYtEvujRa6kQyCEpX5WK7e09Y4Kt2qINu3qyy+7o6Ltj6oYgn+QvFBrev5gmxsHoNKnAcWzX7yiDy02QDLQhRt5hVqC6TU8NQuaoNjzGcdnK3VnIxx31tuQLwc2n1blDQ6rX6ZbzYfThzfmQA7trZfW2nMi84BmqY9NnHbv7YV6tclzSQU4VuVKVsaHRXtjFVyliRqflfAt43dmps43LNG0JyQPvRnfwtELoUrGsem1B0TIJwOt6wf/U/liSCXM88VjTqGEhNEuxPSLq6efuN6MIMNg=)

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer can we close this as it cannot be reproduced on dev?

**Comment by dabutvin** [comment]
:+1:
