### ISSUE TITLE
Curation contribution UI feedback

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#304]
1. We got some feedback from @ariel11 that on the contribution page "OK" instead of "Done" would make more sense. "As I still need to hit 'contribute' on the other page"
 2. Can you also look into having a “Contribute” button on the “File view” page vs. hitting OK at the top to get back to the Definitions page and hitting “Contribute” there? 

@storrisi can you take a look at this please?

**Comment by storrisi** [comment]
> We got some feedback from @ariel11 that on the contribution page "OK" instead of "Done" would make more sense. "As I still need to hit 'contribute' on the other page"

@fossygirl actually there's no "Done" label in the codebase. The contribution page (which i guess is the Detailed view of a definition) has only an "OK" button (if it's inside a Modal), or "Save" if is a deep linked page.
Maybe this request in not addressable anymore?

About 2. , as we discussed with @jeffmcaffer , we don't need to make any change, so maybe this issue could be considered closable?

**Comment by storrisi** [comment]
@fossygirl any updates on this?

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer @fossygirl can we close this?
