### ISSUE TITLE
Would be useful to see if a component has a pending curation

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#306]
Currently, you can't tell in the ClearlyDefined UI if a component has a pending curation.  As more and more people curate, the same components can be on multiple lists, and it would be helpful to see that a component has a pending curation (or maybe you yourself curated it previously, maybe on a different day, and for whatever reason it hasn't been merged yet, this would prevent you from contributing the change again).

**Comment by fossygirl** [comment]
@ariel11 Great minds think alike, we're also interested in doing this per https://github.com/clearlydefined/website/issues/187 

I think @AlexWebYourmind might have this on his radar.

**Comment by storrisi** [comment]
This is related to #290 and it's actually addressed in the PR #320

**Comment by storrisi** [comment]
This is implemented in #320

**Comment by AlexWebYourmind** [comment]
Closing this.
