### ISSUE TITLE
Contribute button submits all changes even if they were already submitted

### ISSUE THREAD

**Issue by capfei** [clearlydefined/website#317]
When working from a list of components, making one edit, click "Contribute" at the top, and then repeat the process with another component ends up with progressively longer pull requests that include the previous changes.

* https://github.com/clearlydefined/curated-data/pull/377 to https://github.com/clearlydefined/curated-data/pull/406
* https://github.com/clearlydefined/curated-data/pull/407 to https://github.com/clearlydefined/curated-data/pull/431

**Comment by fossygirl** [comment]
@storrisi @AlexWebYourmind Can you take a look at this?

**Comment by storrisi** [comment]
@fossygirl , just want to make sure to addressing the expected behaviour:
when working on a list of components, once the user submits a Contribution, all the changes already submitted should be cleared, in order to start with a brand new Contribution?

**Comment by jeffmcaffer** [comment]
yeah, something like that. Possibilities
1. reset the submitted changes (In the eventual (soon?) future show the user that there are pending curations)
1. remove the changed definitions from the list
1. leave the changes but remember they have been submitted such that any subsequent contribution does not include those changes.

Probably door # 1 or 3. 2 could be an option in the contribute dialog. Eg.., checkbox saying "remove contributed definitions from the list". that would be useful for people working through a list of definitions. If the user does NOT check that then we still have to do 1 or 3

**Comment by storrisi** [comment]
I think that the best solution is 1, together with 2. I'm going to implement this.

IMO option 3 would be not so clear for the user (e.g. i see the changes, but then they are not submitted).
