### ISSUE TITLE
Weird data showing up in recent definitions

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#319]
As originally discovered by @AlexWebYourmind  there are several licenses that recently started to show up and should most likely be entirely filtered out such as `No_licend`, `See_license`, `No_license_found` and more... I would guess these come from the addition of Fossology to the definition? These are not SPDX licenses, so IMHO anything not SPDX should be filtered out of the definition.

See for instance search reactive UI and 8ed94f5d40248f409177e2cdd82e2029e9f7c601 e.g. at https://api.clearlydefined.io/harvest/git/github/reactiveui/reactiveui/8ed94f5d40248f409177e2cdd82e2029e9f7c601?form=raw 

(I would have given a website link but #318 is missing for now)

**Comment by pombredanne** [comment]
Note there was also `'.git` directories showing in the UI... but I cannot find that anymore.

**Comment by jeffmcaffer** [comment]
Lets keep the issues separate. One is random text showing up for the license. this is likely a Fossology thing. More generally we should be checking the values coming from the harvested data when we put it into the definitions. 

There is a separate problem of "ignoring" files/folders we know to not to be interesting. The .git folder is one example. I'm assuming that scancode is skipping those. It may be the way we are running fossology that is not.

Both of these are service issues and should be addressed there. @AlexWebYourmind , can you open/guide these appropriately?

**Comment by dabutvin** [comment]
I can take this on next week

**Comment by dabutvin** [comment]
This is now fixed for all components.

**Comment by pombredanne** [comment]
@dabutvin Thanks!
