### ISSUE TITLE
Change title that is created on curation pull requests

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#321]
Right now the titles on curation pull requests is the person's GitHub username (or "clearlydefinedbot") and then some numbers appended on the end. 

We should make the titles more useful. Likely representing the component and/or version curated if it's a single curation? Possibly also reflecting information from some sections of the curation description dialogue would be good.

**Comment by storrisi** [comment]
I think has already been addressed enhancing the Contribution panel:
![schermata 2018-10-05 alle 09 25 32](https://user-images.githubusercontent.com/7654979/46521707-b56d2c00-c880-11e8-94b7-cfa5afc25b17.png)

@fossygirl  are this fields enough to solve what are you talking about?

**Comment by fossygirl** [comment]
@storrisi I'm talking about this:
![screen shot 2018-10-09 at 12 07 27 pm](https://user-images.githubusercontent.com/17101092/46692392-fe441e00-cbbb-11e8-8588-eb95f885d743.png)

We need to make those titles a lot more meaningful for people looking at a glance at curations.

**Comment by storrisi** [comment]
Ok, i see. Probably this needs an enhancement on the service side too. I will double check this.

**Comment by fossygirl** [comment]
Opened https://github.com/clearlydefined/service/issues/259
