### ISSUE TITLE
update docker file to pre-build the site before deployment

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#326]
currently the dockerfile does not run the `build` command to prepackage the site. that means start takes longer and can fail for build reasons. Also, we should be running tests in the build.

Also, seems like we are running watch-css in production?!

**Comment by storrisi** [comment]
> Also, seems like we are running watch-css in production?!

Is it something coming from the new env implementation? Cause i can't see `watch-css` in the build script

**Comment by jeffmcaffer** [comment]
I think we were just confuse with many things going on at once and were looking at the wrong (service's) Dockerfile and then the website's package.json.
