### ISSUE TITLE
"Pencil" icon for selecting declared license redirects you to a blank page when clicked

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#329]
Greetings,

When I dig into the following component's definition: 
https://clearlydefined.io/share/eJwtjTEOwyAMRe/imTJE6sLYa1QdLOJItGAjQ1GjiLuHqKzvva9/wBZiJQV3dANFtD52cPyN0YAX0TUwVirgngfUPRM4SNiIwUBWaWG9pn/kiatiHIYxUcnor9pLshuWcfFL0b7Rf4qw9aI0w9FMeptUqYUShIdZ7N0u0F/9BJOCOjI=

, I have observed that the "Pencil" icon used for editing the declared license field redirects me to a blank page instead of actually allowing me to edit the Declared license field.

![2018-10-15_8-17-32](https://user-images.githubusercontent.com/31491646/46960667-e8b77400-d053-11e8-93c6-95cc3b6f5e27.png)

Tested on Chrome 69.0.3497.100, Firefox 62.0.3 64bit, and Edge 42.17134.1.0 and I observe the issue occurs on all three browsers.

Kind Regards,
Brian

**Comment by dabutvin** [comment]
the fix is now live and verified in dev. Will be shipped to prod soon. Thanks all!

**Comment by bduranc** [comment]
@dabutvin: I am still seeing some cases of #329 despite it being closed.

I was trying to declare some licenses on the file level, but I keep getting that infamous blank screen: 

https://clearlydefined.io/definitions/git/github/javaee/javax.annotation/9b07ccb6abe68f55f5d48ecfa84a300998d7c9a0. 

It basically happens whenever I try to edit a field that already has an SPDX expression in it.

Thanks.

**Comment by storrisi** [comment]
@bduranc the problem here is that the file has a license that cannot be validated by the spdx library that we use, since the license contains a NOASSERTION value: `CDDL-1.1 OR NOASSERTION AND GPL-2.0-only`

So i've made a quick update to avoid this, but i'm wondering if this is really possible?

**Comment by bduranc** [comment]
@storrisi : I'm not sure I really follow. In almost all cases, it seems these are files that already have a valid SPDX expression entered of either NOASSERTION by itself or in combination with other licences.

I simply wished to update the license to a different value. The expression I planned to enter would have also been a valid SPDX. Other fields let me do this without any trouble, even if there is a value already existing in the field.

**Comment by storrisi** [comment]
@bduranc yes, what you are expecting is right. The problem were the license was not only a NOASSERTION value, but it was part of the license.
@dabutvin has improved the spdx validation including these cases and i'm gonna integrate his work in the website.
