### ISSUE TITLE
Modal dialogue lists user as @null even if logged in

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#333]
I was logged into clearlydefined.io when I made this curation, but it lists my user as @null and doesn't give me any way to correct it.

![screen shot 2018-10-15 at 2 32 41 pm](https://user-images.githubusercontent.com/17101092/46979810-7a8ca480-d087-11e8-8018-4a5db04a1aea.png)

**Comment by dabutvin** [comment]
that worked for me!

Jus thad to log out and log back in this one time then it functions as normal

**Comment by fossygirl** [comment]
@storrisi Yes, that works for me as well. Thanks very much.
