### ISSUE TITLE
Collect search terms on clearlydefined.io/definitions

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#338]
Sounds like we can get this data through Google Analytics pretty easily. I'd like us to keep logs of searches that return a result even if the user doesn't end up curating anything.

**Comment by AlexWebYourmind** [comment]
@fossygirl may I suggest to deploy GA via Google Tag Manager (https://tagmanager.google.com). having GTM on CD might be beneficial and allow to deploy multiple Analytics tool via the platform, without additional code changes.

**Comment by fossygirl** [comment]
@AlexWebYourmind Sure, that sounds good.

**Comment by fossygirl** [comment]
@AlexWebYourmind Is this done and we can close?

**Comment by fossygirl** [comment]
I'll close this for now, we may not need this anymore.
