### ISSUE TITLE
Show suggested data to the user

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/website#339]
This follows the discussion started by @jeffmcaffer in PR #316 , related to Increase the overall data visibility.
These are the outstanding questions:

> Does not matter if the suggested value comes from a curation. Could come from a tool run on a more clearly defined version (earlier or later)

I guess those data are returned from other revisions of the same definition.
Looking at the proposed API from your document, probably is actually missing an endpoint that returns definitions data for any revision?

> Even if there is a value in the current one, might be interesting to point out that other versions had a different value
> Avoids the problem of when to "suggest". effectively we always show the means of seeing the other values. These could just be in the "pickers" for the values. For example. have a "related values" section in the license picker. User could see that related components have other licenses and maybe even navigate to those definitions (separate tab). 

For these 2 point we could end up with a solution similar to the one Facebook use for Ads Management.
The Suggestion label is highlighted only if there is at least one suggestion. Could this proposal be a good solution?
![schermata 2018-10-01 alle 12 19 03](https://user-images.githubusercontent.com/7654979/46355895-faffde00-c661-11e8-8674-4a96f9348ec9.png)

> Will we be able to do the same thing in the drop down panel?

Is the drop down panel actually the Components List?
In that case, we have thought to highlight something to the user, in order to only let know that there are suggestions.
I would not let the user check the suggestions directly from the list, since it could mean to make a lot of calls for each definition in the list, ending with a huge time waiting if the list is pretty long.
What do you think about it?

> Will there be some sort of indication on the two line and/or panel view that there are suggestions? Or will the user need to ask for them?

As mentioned above, we think the best way is to let the user know that a definition has some suggested data, and from the two line list inspect the full details view to see what are the suggested changes.
Likewise the user, in a full details view, should to be notified that there are suggestions (especially if he's checking from a deep linked URL)
This was originally the reason of the highlighted field.
But, given that the user could make a choice, then i would only suggest to highlight the field, and then let the user see all the suggestions in the proposed way.

> Just because I noticed you show it, not sure how we can do the source location as a suggestion unless it is using the GitHub repo and finding a tag that matches the current version. That is, the reusable part of a related source location curation is the repo info, not the revision.

Since there's a new proposal implementation for the Source Location Picker, should we leave this for now?

> Are you thinking that individual files would also have these affordances?

They should, given that any file could have license, facets or copyrights updates.
On the other way, it could very uncomfortable for the user to check any single change for any file, especially if there a lot of files.
Like we've implemented for reverting changes, we could think to have something that allow the user to apply all the suggestions for the entire file list.
It makes sense to you?

**Comment by moranthomas** [comment]
Do we now have a specific definition of what a relationship is in this case for definitions ?

Since newly suggested 'components' can be either a subset of 'definitions' or 'curations, and could be everything related to the definition. 

Any property of a definition (including curations) can become the target of an auto-suggested field" But on the service side there is no logic that computes either a relationship between curations or how to compute 'suggestions' for any given fields.... 

So 'how to get any suggested field' seems to be far from well defined right now 

I don't believe this is an issue that applies to 316 or 291 as the relationship between curations is well known in this case. The related curations here come from all other versions of the same definition and we just chose the latest one

**Comment by storrisi** [comment]
Just a recap following our discussion on this topic

* all the suggestions should be returned by a separate API, sort by update date at first
* the suggestions should be displayed initially only for missing fields of a definition
* for a missing field, the user should be noticed of the presence of suggestions
* the user should be able to check all the suggested data for each single fields, and pick one of them
* the suggestions will be displayed only in the Full Details View
* for the file list, the user can be either apply suggestions for each single field, or in a bulk way for all the files in the definition (like the Revert button)

As an example of the process, i would suggest this flow:

* once in the Full Details View, the client asks for a `POST /suggestions` API, passing in the path of the definition, like `["npm/npmjs/-/async/0.2.6"]`
* then, the client should answer with an object containing all the suggestions for any missing field of the specific version of the definition, taken from any related data
* a sample of the object could be:
```

**Comment by jeffmcaffer** [comment]
Overall this is pretty reasonable. Some thoughts on the details:
* The UX for informing the user that there are suggestions should be uniform. that is, imagine some icon (e.g font-awsome info-circle) that indicates there is more information available. the user clicks or hovers or .. and sees the suggestions.
* suggestions should come back from the service with some match ordering. The client can always offer the user alternative sortings but the service will be in the right place to do the ranking
* Each suggested value should have be annotated with whether or not it is from a curation (and possibly who) as well as the date of the curation and the PR number of the curation. This enables users to make informed choices. Perhaps flag this the a person icon (e.g., fontawesome person-sign).
* Doing suggestions only for missing values is fine as an initial step but we should assume suggestions for more cases will be relevant.
* suggestions should be a standalone thing. That is, not "part of" the full details view. they should show up on the full details view but we may well want them in the drop down panel in the definition list and elsewhere.

**Comment by jeffmcaffer** [comment]
building on @moranthomas comment some more thoughts:
* not everything in a definition should be the subject of a suggestion. For example, release date, source location (though partial may be ok), ... In theory yes, but in practice unlikely.
* the service is responsible for finding suggestions. That algorithm will change over time and will likely vary by component type. This is sort of like search engine page ranking or Amazon "people who like this also liked..."
* likely relationships are 
  * other versions of the same thing
  * source component for a package component
* The fact that a value came from a curation may change that value's suggestion ranking but not the relationship. That is, it is a value from another definition. If it was curated, that means the harvested value was either missing or incorrect. either way it is not relevant.
