### ISSUE TITLE
Declaring license under "Files" view of component

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#343]
Greetings,

As current, when I go to declare a license for a file under the source tree of a component ("File" view), the source tree refreshes and collapses every time I declare a license at that level.

In other words, if want to declare licenses for multiple files under that source tree, I need to expand the tree again and find that file.

![stepscombined](https://user-images.githubusercontent.com/31491646/47451111-c7edcd80-d77b-11e8-8b1f-1a5c39e44590.png)

This is really time consuming as essentially the above steps need to be done for every file I declare a license for.

What I think would be more efficient, is the ability to declare licenses for multiple files in the source tree without having the tree refresh on the user and collapse.

**Comment by AlexWebYourmind** [comment]
@bduranc this is a known issue, related to react-table. We have opened an issue on their repository, that is currently being addressed as part of future implementations --> https://github.com/react-tools/react-table/issues/1062

Should it not be fixed in a reasonable time, we'll probably need to evaluate alternative implementations.

@jeffmcaffer @storrisi thoughts?

**Comment by storrisi** [comment]
@jeffmcaffer we'll look further into this. 
From our past investigations, we ended up that it could be easier to switch to [antd/table](https://ant.design/components/table/#components-table-demo-expand-children) , which is the matter we brought ant-design as a library into the project.

**Comment by jeffmcaffer** [comment]
There are a number of these sorts of things that should be addressed soon. Perhaps for January we should plan a UI pass to fix a bunch of the nits and pain points. @storrisi thoughts?

**Comment by storrisi** [comment]
I agree, we could plan for January an activity to fix these kind of issues.

**Comment by storrisi** [comment]
This one is related to #489 , probably the automation was wrong. It could be closed.
