### ISSUE TITLE
Source Link popup window

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#347]
Now when I click on the source link, a new window pops up with a hyperlink.  However, clicking on the link takes you out of clearlydefined instead of opening it in a new window.  I then have to back page back to ClearlyDefined, at which point it reloads the page and I lose where I am if it is a long list.  If clicking on the source link opened a new window/page, that would be ideal.

**Comment by fossygirl** [comment]
@storrisi Could you take a look?

**Comment by storrisi** [comment]
@fossygirl sure
