### ISSUE TITLE
List "auto-refreshes" after making "Contribution"

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#348]
In the ClearlyDefined UI, if I have a long list of components to curate, I "contribute" the declared licenses in batches.  As I go through and declare licenses, it turns a color (which is helpful).  If I curate 10 entries for example, and hit "Contribute," it auto refreshes the list and those 10 entries now look like they haven't been curated.  Not a big deal, but it takes more attention/work to track what was just contributed, as I continue down the list of components to curate.  I know you are working on this, but it would be very useful to have a way to tell if a component has a pending curation (by anyone).

**Comment by storrisi** [comment]
@jeffmcaffer this is something introduced by #328 , related to issue #317 

The next step on this would be to show Pending Curations for submitted Contributions

**Comment by fossygirl** [comment]
@ariel11 @storrisi Is this still a problem?

**Comment by ariel11** [comment]
@fossygirl - If I recall when I submitted this, after I hit "Contribute" and it reloaded the page, it collapsed the list I was working on.  Now at least the ones I've expanded and worked on stay expanded, so it is easier to see where I am in the list.  However, there is no way to tell if a component has a *pending* curation, and that would be helpful/nice.

**Comment by storrisi** [comment]
Showing pending and merging curation is already implemented in the UI, but the service isn't still returning those data.
I think we can close this one.
