### ISSUE TITLE
[Feature Request] Bootstrap-style tooltips over each field in component definition view

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#352]
Bootstrap-style tooltips over each component definition item field (i.e. "Source", "Facets", "Declared License", "Discovered License") would help newcomers easily understand what different fields are for and their appropriate usage without immediately needing to consult more in-depth documentation.

![tooltip](https://user-images.githubusercontent.com/31491646/48022070-fdd17100-e0ee-11e8-9c43-9ea573dd7ad5.jpg)

This is discussed in another issue already but I don’t believe to the extent I describe above: https://github.com/clearlydefined/website/issues/197#issuecomment-422879004

==Resources==
Example of tooltip in Bootstrap: https://getbootstrap.com/docs/4.1/components/tooltips/#examples

**Comment by storrisi** [comment]
@jeffmcaffer @fossygirl what do you think? Should we implement this on the UI?

**Comment by jeffmcaffer** [comment]
The point is well taken. First step would be to see if we can change the UI layout or wording such that it is more self-evident thus eliminating the need for tips. I don't have any immediate thoughts there but @bduranc may.

Failing that, it is more of a UI design question as to whether we want the UI to flash at users as they move their mouse around. In general I personally dislike it when I have to search for a place to set the mouse down and not trigger a tool tip. Hides bits of the UI and is visually distracting. We do have tool tips on the action buttons which seems fair enough and relatively isolated. 

As such, I'm less inclined to tooltip everything. In a fancy world in the future we could have user settings that controlled this but that seems fancy and future. Unless there is strong pushback, we should close this for now and look to reopen once we've gotten the more basic UX in place.

**Comment by bduranc** [comment]
@jeffmcaffer I have no serious objection to closing this. I think the fact that most of the buttons already have the tool-tips is a good start and a very suitable place to have this.

With #400 in place, this will probably even less of a need.

Fields like "source" and "release" are self-explanatory as the UI forces you to follow very specific instructions already (release has a "date picker" control, and source has a source browsing modal dialog).

But for example, the concept of something like facets and their proper use may not be immediately clear to all users. 

These are just my thoughts. Any other input is also welcome.

**Comment by jeffmcaffer** [comment]
Oh yes, facets are quite opaque. Perhaps this is a good call to review the UI bits and judiciously add tooltips (and doc) at key points.

**Comment by storrisi** [comment]
@jeffmcaffer since we are thinking about a new GlobPicker that could help the users to better apply facets on files, maybe this requirement could be covered by that implementation?

**Comment by storrisi** [comment]
There are some discussions around the facets editing behavior.
Since a decision hasn't yet taken, we should define if this issue is covered by #478 (related to the tooltip that explains how Facets work) or not.

**Comment by storrisi** [comment]
I'm wondering if we still need other tooltips over the UI. We now have a better explanation of facets and scores.
@bduranc thoughts?

**Comment by bduranc** [comment]
@storrisi: I think with the recent addition of the tooltip for Facets (dealt with in #478), there are no other major areas requiring this enhancement.

I agree with @jeffmcaffer said earlier in this issue about over cluttering the UI with too many tool tips and how a bombardment of onHover events can make for a poor user experience.

We can probably close this issue if no one else objects.
