### ISSUE TITLE
Components with curated license data not displaying license

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#355]
Some components that have curations on their license data are not displaying that data in the UI.

Example:
https://github.com/clearlydefined/curated-data/pull/600
https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/Microsoft.Extensions.Logging.Abstractions.yaml

![image001](https://user-images.githubusercontent.com/17101092/48095981-eebff100-e1ca-11e8-95d0-4a53257184d3.png)

@capfei @dabutvin @jeffmcaffer

**Comment by dabutvin** [comment]
I see it now ...
![image](https://user-images.githubusercontent.com/5168796/48151428-1cae3f80-e276-11e8-9a1e-2621af4f2750.png)

This is weird 👀

**Comment by capfei** [comment]
Just got another one today:

https://github.com/clearlydefined/curated-data/pull/681
https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/Edge.js.yaml

![image](https://user-images.githubusercontent.com/5489711/48649504-a614ee80-e9a7-11e8-8f47-ed1ed01191ea.png)

**Comment by fossygirl** [comment]
@dabutvin @jeffmcaffer Were you able to identify this problem and find a resolution?

**Comment by fossygirl** [comment]
@dabutvin @jeffmcaffer I got the impression that this issue was solved by https://github.com/clearlydefined/service/pull/297

Is that true, or is there further work here needed? Can you verify this is fixed?

**Comment by dabutvin** [comment]
Well we have a syncing mechanism now, but it is not any kind of schedule as of yet.

Additionally, there is definitely a bug with the way the definitions are getting invalidated as demonstrated by curations 847 + 848.  Need to dig into it a little deeper to track it down.

Also, the sync is having to work more than I expected it to - it seems like there is another bug in our webhooks somewhere that needs to be tracked down

**Comment by dabutvin** [comment]
this is running on a schedule now every hour it will clean up.

Please re-activate if you see curations not showing up in the UI over an hour after being merged.
