### ISSUE TITLE
New page view: "stats" page

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#358]
We'll eventually want a new page on clearlydefined.io that displays stats of various kinds.

To start, we want to see the top 1k packages from all the package managers and their scores and tracking their scores over time.

We'll also want to display things like how many definitions we have, how many package managers we have coverage with, etc.

**Comment by fossygirl** [comment]
@dabutvin Here's a super quick mockup of what we talked about the other day. Thoughts? Feedback?

![stats](https://user-images.githubusercontent.com/17101092/51941867-7718f100-23ca-11e9-8d03-3827cd320a78.png)

**Comment by storrisi** [comment]
@fossygirl @dabutvin are there any specs about this implementation?
Is there already some service endpoints to retrieve the necessary data?

**Comment by dabutvin** [comment]
there is not any service for this yet. I was planning to put something dead simple together as a starting point and then we can spec out the full implementation

**Comment by dabutvin** [comment]
this is relevant: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/19676359-support-count-of-a-query-on-a-partitioned-collecti

fyi @jeffmcaffer

**Comment by dabutvin** [comment]
I've got an initial implementation for the service side over here: https://github.com/clearlydefined/service/pull/378
