### ISSUE TITLE
dangling tooltips 

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#364]
From time to time it seems that tooltips are not going away.  In the screenshot below not there are two tooltips. The "Revert" tip is actually stuck up. Even if I move to a different area where there are no tips at all, it stays up, The Copy tip OTOH comes and goes as expected. I've notices this as well quite a bit with the tip for the "Revert Changes" button 

![image](https://user-images.githubusercontent.com/10070956/48319657-35e02480-e5c5-11e8-835a-3153bb7c7e9b.png)

Note that I seem to be able to make it happen (in Chrome) by moving the mouse "promptly" over the button. slow enough that the tip pops up but fast enough that you are not lingering.

**Comment by storrisi** [comment]
Seems like this is a knows issue of ant-design when there is a Tooltip on a disabled Button, as explained here: https://github.com/ant-design/ant-design/issues/9581

I've tried to replace the Tooltip with the Bootstrap one, but it doesn't work on elements that are not buttons, like a DropDown for example.

Maybe we can hide the tooltip if the button is disabled?

**Comment by storrisi** [comment]
Looks like it shows up randomly, and due to the fact that the button is disabled, it doesn't disappear.
I'm gonna check into this again.

**Comment by storrisi** [comment]
I've found this issue opened into the react-boostrap repo, https://github.com/react-bootstrap/react-bootstrap/issues/2428 , but applying the suggested solution doesn't seem to solve the problem
