### ISSUE TITLE
Can't populate SPDX declared license field from within Definition view

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#371]
Greetings,

I tried to update the declared license for the following component on CD: 
`git/github/activiti/activiti/2bd372bbaac918962694dc58b7c4e3feaedfdfa7`

However, I am unable to populate the SPDX declared license field when under full Definition view.

![image](https://user-images.githubusercontent.com/31491646/48589319-df8a2300-e8ef-11e8-95fb-b48e16cb4612.png)

The issue does not appear to be present when you use the declared license field visible before you drill into the component definition.

![2018-11-15_16-06-14](https://user-images.githubusercontent.com/31491646/48589445-6f2fd180-e8f0-11e8-9aef-9e4141a23d1c.png)

To **reproduce** the error, I do the following:

1. First, I search the component: git/github/activiti/activiti/2bd372bbaac918962694dc58b7c4e3feaedfdfa7

2. Then I click the "Dig into definition" button:

![2018-11-15_16-00-31](https://user-images.githubusercontent.com/31491646/48589355-ffb9e200-e8ef-11e8-8586-0fcdfa115bd3.png)

3. Then I attempt to enter in SPDX license "Apache-2.0" into the "Declared" (license) field.

**Outcome:** The field clears itself and loses focus (the red "revert changes" button does show though):

![image](https://user-images.githubusercontent.com/31491646/48589319-df8a2300-e8ef-11e8-95fb-b48e16cb4612.png)

This issue appears to happen regardless if I select from the field autocomplete option or I enter in the SPDX license name manually.

Tested on Chrome 64-bit for Windows with a freshly cleared browser cache

**Comment by storrisi** [comment]
@jeffmcaffer @dabutvin it seems the API answers in a strange way.

When the website calls the preview API, passing this kind of data:
`POST definitions/git/github/activiti/activiti/2bd372bbaac918962694dc58b7c4e3feaedfdfa7?`preview=true
with content `{"licensed":{"declared":"0BSD"}}`

the API answers `data Curation object requires coordinates and revisions, data Curation object can only have coordinates and revisions`

I'm pretty sure that anything has been changed in the website when calling this, but i'm gonna check it anyway.

**Comment by jeffmcaffer** [comment]
hmmm, some validation went in recently. Perhaps it is acting up... Will look.

**Comment by bduranc** [comment]
Another colleague noted to me that this bug also may occurring with the "Source" field (i.e. trying to populate a an empty source field)

**Comment by jeffmcaffer** [comment]
Sigh, this was a one char error. Validating against "curations" rather then "curation" (do you see the difference?). Fix has been pushed to prod and is deploying now. Thanks.
