### ISSUE TITLE
Define e2e tests specs

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/website#397]
We need to figure out what kind of e2e tests we want to write for the website.

Those should be something like user stories ("As a user i want to go to a page and click on some elements and return a result") and should cover the most critical parts of the application.

**Comment by AlexWebYourmind** [comment]
Good point. I would suggest to identify the different use cases that we want to test (e.g. As a User, I want to create a curation,  As a User, I want to view the details for a specific definition ). 

@fossygirl @jeffmcaffer comments? We are more than happy to start suggesting / writing a few  e2e tests based on what makes sense to Us. we can review and add additional ones as we go.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer @fossygirl any updates on this?

**Comment by jeffmcaffer** [comment]
Hey @AlexWebYourmind . I was assuming that you / @storrisi were going to identify some use cases and do some examples. Do you need something from me to get started?

**Comment by jeffmcaffer** [comment]
We have the e2e test structure in place now. Can this issue be closed or is it supposed to capture doing the actual tests? If the latter, perhaps we need to narrow it down to specific scenarios that need testing. Suggest we pick one and do it to validate the approach etc.

Who owns driving this? Currently assigned to 4 people. Needs to be one.

**Comment by storrisi** [comment]
Actually i've started from the main scenarios to build the very first e2e tests of the application, testing the Definition page and all of its behaviors (adding a component, edit a license and all of the other fields..) 
I think we can improve all of the e2e tests for the Definition page (which are a lot considering also the detail view and saving / dropping functionalities) and consider them as a guideline.

Thoughts?
