### ISSUE TITLE
Add drag and drop for component searching

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#41]
rather than entering selections one by one, users should be able to drag a file listing components and drop it on the search input text box.

The file could be
* ORT package dependencies file
* package.json, project.assets or any other fully resolve package manager dependency file
* CSV
* one entry per line
* JSON array

Where each entry might be 
* various forms of canonical web URLs
* CD component specs

**Comment by fossygirl** [comment]
We are considering this a stretch goal for our OSLS demo.

**Comment by fossygirl** [comment]
Removing OSLS milestone, we decided we won't get to this for next week.

**Comment by fossygirl** [comment]
https://github.com/clearlydefined/website/issues/124 may be a duplicate of this. I will merge.

**Comment by fossygirl** [comment]
Closing as a duplicate of #124
