### ISSUE TITLE
Add NONE to the UI

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#410]
Add NONE as a curation option for declared license in the UI.

**Comment by dabutvin** [comment]
Should we also remove NOASSERTION as an option?

**Comment by storrisi** [comment]
Maybe i'm wrong but the NONE value is already there
![schermata 2019-01-16 alle 16 05 55](https://user-images.githubusercontent.com/7654979/51257815-beee5000-19a8-11e9-93e7-82b0c536e4fe.png)

**Comment by dabutvin** [comment]
Thanks @storrisi - in that case I think the only action here is to remove NOASSERTION from the list.

We want humans to be able to curate NONE, but the UI should still be able to render NOASSERTION from the definition.
