### ISSUE TITLE
license picker gets in odd state

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#412]
I don't see what is wrong with expression but the bar at the top is red... Theoretically if I just click buttons and fill in all the blanks the expression should always be syntactically valid no?

![image](https://user-images.githubusercontent.com/10070956/51443465-0b35da80-1c9e-11e9-8086-02d802b71308.png)

**Comment by storrisi** [comment]
After each change the expression is passed to the `spdx-expression-validate` library, which returns if the passed expression is a valid license.

Maybe those group of licenses are not possible for some SPDX rules?

**Comment by jeffmcaffer** [comment]
AFAIK the expression validation is not doing any license interpretation. It is analyzing the structure and that each license id is valid. So it should be impossible for someone to fill in all of the boxes and have an invalid expression. 

Perhaps the conversion from the structure here to a string expression is messed up? The validator may be needing `()`s around some of the ANDs (not sure).

One related point, I'm not sure that all licenses allow for `+` (any later version). @dabutvin can you confirm here?

**Comment by storrisi** [comment]
I see, probably you mean that the Picker in this situation should return `(MIT AND ADSL) AND (AFL-3.0 OR AGPL-1.0-only)`

I'm gonna investigate on this.

**Comment by storrisi** [comment]
I've tried to switch on the Picker the last license from `AGPL-1.0-only `to `0BSD` and the validation library returns `true` for `MIT AND ADSL AND (AFL-3.0 OR 0BSD)` and `false` for `MIT AND ADSL AND (AFL-3.0 OR AGPL-1.0-only)`

So i guess that the `spdx-expression-validate` library applies some kind of validation of the used licenses

**Comment by storrisi** [comment]
@jeffmcaffer do you have any update on this?
AFAIK , as i reported in my last comment, looks like that the `spdx-expression-validate` is validating also the used license.
It happens also when you choose a `MIT-0` as a main license.

**Comment by storrisi** [comment]
While applying a `MIT-0` license, the message returned is `"Lexical error on line 1. Unrecognized text.↵MIT-0↵---^"`

**Comment by dabutvin** [comment]
the only thing spdx-expression-validatate does is a try/catch around spdx-expression-parse
https://github.com/jslicense/spdx-expression-validate.js/blob/master/index.js

if it is parseable, then it is validated.

**Comment by storrisi** [comment]
I'm trying to debug the library, but i can't understand why and when that error is returned

**Comment by storrisi** [comment]
I've created PR #452 with two small test cases using as example both `MIT-0` license and `MIT-CMU`.
The first case is failing while the second is passing without any issue.
Thoughts?

**Comment by storrisi** [comment]
#452 shows that the spdx-expression-validate library fails while testing.
I don't know why this happens, libraries and dependencies are updated but there's something wrong with it.
Should we try to implement a validation tools by ourself based on SPDX rules?

**Comment by dabutvin** [comment]
I accidentally pushed this in without a PR

sorry about that. Please feel free to review: https://github.com/clearlydefined/website/commit/a22f3f8cdbf57abe906451d8a62b399c0425b95c
