### ISSUE TITLE
make issues with Notice generation more addressable

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#421]
In the recently added Notice generation setup, the generation may come back with some issues. We Toast the user so they know there were problems but don't give them a way to easily understand what the issues are or fix/curate them.

* near term approach is to give them a link/button they can click to cause the Definitions list to filter to just things that have problems.  Probably need to Toast them again to say that we did just filtered and their list is not gone. (better woul dbe to have a UI signal that the list is filtered)

* longer term approach is to have another page that is dedicated to Notice generation and allows management of that workflow, tweaking of templates, ...

**Comment by storrisi** [comment]
@jeffmcaffer i guess that the Notice generation is already returning a list of definitions that encountered some problems?
How can i replicate the process and generating some Notice issues, in order to take control of the behavior?

**Comment by jeffmcaffer** [comment]
Implemented in #425
