### ISSUE TITLE
License picker broken

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#434]
find a definition that is missing a license. Click on the license area of the drop down panel and you'd expect to get a list of licenses to pick from and some completion help but now it is just a text box

**Comment by storrisi** [comment]
@jeffmcaffer could you spot a definition with a missing license?

**Comment by jeffmcaffer** [comment]
almost any nuget. but Newtonsoft.msgpack 0.1.7

**Comment by storrisi** [comment]
Thanks, i will take a look at it
