### ISSUE TITLE
Browse experience improvements

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#44]
We want to make have more detail in the browse experience as well as making it more useful. The TwoLineRowEntity should show license and the "score" so that people scanning the list can quickly understand what they are looking at. Ultimately there will be sorting and filtering on these sort of fields.

On the drop down we can add links and the tools used (new info that will be added as part of another issue)

* remove revision selection affordance
* add in file counts
* add score (use badge?)

**Comment by jeffmcaffer** [comment]
more tweaks to come but this is looking reasonable for now
