### ISSUE TITLE
Have option to download the actual component

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#462]
There are times when reviewing a definition that it would be good to get the actual component on the local drive and look at the files. We cache a lot of the interesting files but not everything. We could add a `downloadUrl` property to `described` domain and then show it in the UI, or have the UI compute the download URL.  In theory we could also just add a GET API on the service that gets the URL but that seems like a lot of overhead for a relatively simple thing that we've already computed.

I'd lean towards doing it in the definition as that is more durable and enables multiple clients to get the same behavior without duplicating logic.

The download button (whatever form it takes) can just be on the Full Details page I think. perhaps near the Files section. Seems most relevant. Open to options...

**Comment by storrisi** [comment]
I think that, knowing the right rules, this could be implement directly in the UI, as already done for the `componentUrl` and the `revisionUrl`.

Do you already know the rules that explain how a download Url should be computed for each different provider?
Maybe you or @dabutvin could share these rules?

**Comment by jeffmcaffer** [comment]
By putting it on the definition we enable all clients to provide the capability. In light of the code you (@storrisi) just updated for #464, I'm actually thinking that definitions `described` section should have a set of URLs

* component
* revision
* download

I'm not 100% sold on the `component` url but sure.

The downside is the durability of these values. The various providers may not be thinking of their web ui URLs as API and so may change them at any time. While could of course adapt and lazily update all the definitions, that may be less than optimal.

An alternative is for the service to provide an API that returns the URLs. In the UI scenarios, this should be fine. The user is already clicking and going to another website. The one round trip to the serivce would not be a big hit.

@storrisi FYI, all the code for downloading the components is in the corresponding `fetcher` providers in the crawler.

**Comment by storrisi** [comment]
Given the scenario, maybe the API solution could work better, since it doesn't require any update of the UI methods to retrieve the correct download URL.

Do you want me to create a related issue on the service?

**Comment by dabutvin** [comment]
per the conversation this morning let's add to the definitions in the described section 

```
- described 
    -urls
        - web landing page
        - version specific url
        - download url
```

**Comment by storrisi** [comment]
@dabutvin thanks, so we should expect that these data would be returned all from the server?
In that case we could remove any kind of URL-building method from the UI for these values.

**Comment by storrisi** [comment]
@dabutvin @jeffmcaffer do you have any update on this? i would be happy to work on this new implementation.

**Comment by dabutvin** [comment]
@storrisi yes, that's right. We should remove the url building from the website code and read the urls from the definition

**Comment by storrisi** [comment]
Got it, do you want me to open the issue on the service side? We can keep this to address the update of the UI when the implementation of the service is in place.

**Comment by dabutvin** [comment]
I just did. thanks https://github.com/clearlydefined/service/issues/403

**Comment by storrisi** [comment]
I've opened https://github.com/clearlydefined/service/pull/410 that address the service implementation. 

I'm gonna open a WIP PR on the website as well to remove the unused methods and use the returned data from the service instead.
