### ISSUE TITLE
Modify curation review view to show facet changes

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#476]
Right now the curation review view (e.g. https://clearlydefined.io/curations/1078) lights up the change the curator has made, for example a change to the definition, however it's very simple and not detailed enough to show facet editing.

We need to expand out this view to allow reviewers to see changes to facets easily. This page might need to be an augmented Full Details Page, perhaps, with highlighting of the facets a curator changed. We need to give the reviewers a much more at-a-glance understanding of what files will be ending up in the new facets if the change is accepted.

**Comment by storrisi** [comment]
@fossygirl a read-only view of the Full Details View could be an acceptable solution?

**Comment by fossygirl** [comment]
@storrisi No, not completely. We need to highlight the facet changes, so this is a change.

**Comment by fossygirl** [comment]
@storrisi No, not completely. We need to highlight the facet changes, so this is a change.

**Comment by storrisi** [comment]
Actually the FileList already shows which files are affected of a specific facets change.
Should we consider another kind of view for this specific behavior?

**Comment by fossygirl** [comment]
Can you show me a gif of reviewing a facet editing PR?

**Comment by storrisi** [comment]
This is what a user see when he change facets values under the Full Details View.
![schermata 2019-02-21 alle 17 34 44](https://user-images.githubusercontent.com/7654979/53185333-15c9f380-35ff-11e9-89bb-4c50764522ce.png)

**Comment by fossygirl** [comment]
That's not what I'm referring to. I'm referring to the link for reviewing that a person gets from a PR on https://github.com/clearlydefined/curated-data/pulls 

For example, when I click on the link from https://github.com/clearlydefined/curated-data/pull/1078#issuecomment-465690231 I should be taken to view the highlighted facet changes. how do I view that?

**Comment by storrisi** [comment]
Do you know a PR that contains some facets changes that we can use as a test?

**Comment by fossygirl** [comment]
Sure: https://github.com/clearlydefined/curated-data/pull/437

**Comment by storrisi** [comment]
That PR doesn't show any detail on ClearlyDefined, maybe because it's closed?

**Comment by fossygirl** [comment]
Feel free to open some dev PRs that have facet editing if you need to reproduce this.

**Comment by storrisi** [comment]
I've created a contribution on dev which contains a change to the facets.
This is what a user currently can see when looking at the contribution on https://dev.clearlydefined.io/curations/401

![feb-21-2019 18-52-21](https://user-images.githubusercontent.com/7654979/53190492-02705580-360a-11e9-97a3-e8e78e2de64a.gif)

**Comment by fossygirl** [comment]
Okay, thank you. I still don't think that's obvious enough to users. Can we use the same highlighting mechanism we use for changes in other places on the website? The red color just says "warning" to me, it doesn't say "changed value."

**Comment by storrisi** [comment]
Sure, we can definitely apply the same color.
