### ISSUE TITLE
Give curators better guidance around "glob expression"

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#478]
Most of the users who are going to use the Full Details page are not developers. They will not understand what a glob expression is or how to use that functionality. We should change the language on the page to something simpler and also provide tooltips with examples of what is allowed syntax there.

**Comment by storrisi** [comment]
I think that the best solution could be to have a '?' icon in the Facets section, and then have a tooltip or something like that that explains how glob works with some examples.

We can write down a sample text and post it here so we can decide together what works best.

Thoughts?

**Comment by fossygirl** [comment]
Yes, I think that's a good solution. Let's move forward with that and see how it looks.

**Comment by gianpaj** [comment]
Here's what I've written to explain globs:
<img width="707" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/53400124-de1fca80-39b5-11e9-998d-5b3100d8bf51.png">

> Globbing patterns use common wildcard patterns to provide a partial path that can match zero or hundreds of files all at the same time.
> "?" matches a single character.
> "*" matches any number of characters within name.
> 
> For example:
> // Match any file or folder starting with "foo"
> foo*
> 
> // Match any file or folder starting with "foo" and ending with .txt
> foo*.txt
> 
> // Match any file or folder ending with "foo"
> *foo
> 
> // Match a/b/z but not a/b/c/z
> a/*/z
> 
> // Match a/z and a/b/z and a/b/c/z
> a/**/z
> 
> // Matches hat but not ham or h/t
> /h?t

Any feedback on the text, look and the length?

**Comment by fossygirl** [comment]
I think we need even simpler language than this. The examples are good, but the introduction text should be simpler. Something like "Use this to construct what files you want included in the facet(s) below. You can include or exclude files doing the following:" and then put in the examples. 

We should post this in the #curation channels in Discord as well and see if the curators have input here.

**Comment by gianpaj** [comment]
Based on the feedback from here and `#curation` channel on Discord. I've amended the text to:

> Use this to construct what files you want included in the facet(s) below. You can include or exclude files doing the following:
> "?" matches a single character.
> "*" matches any number of characters within a name.
> 
> For example:
> Match any file or folder starting with "foo"
> `foo*`
> 
> Match any file or folder starting with "foo" and ending with .txt
> `foo*.txt`
> 
> Match any file or folder ending with "foo"
> `*foo`
> 
> Match a/b/z but not a/b/c/z
> `a/*/z`
> 
> Match a/z and a/b/z and a/b/c/z
> `a/**/z`
> 
> Matches hat but not ham or h/t
> `/h?t`

One thing remaining is:
- How do we explain what a **facet** is?

**Comment by fossygirl** [comment]
https://github.com/clearlydefined/clearlydefined/blob/6fb49f4a9e373e4dec84e16a30e48dbd8f00726b/docs/clearly.md 

A facet of a component is a subset of the files related to the component, grouped by type

**Comment by fossygirl** [comment]
@dabutvin and I talked today and I think we want to put in these changes. We additionally want:

1. To remove the term glob expression entirely from the UI
2. Add selectors on the files and folders and give users feedback to let them gesture those files or folders into facets more easily

**Comment by storrisi** [comment]
The tricky part here is to build a glob expression starting from a path.

The user should be able to add or remove facets on each file or folder in the file list.
Since the curations wants facets expressed like glob expressions, we need to build those starting from the user activity.
If a user has applied a facet to an entire folder, is quite easily to build the related expression to that.
The problem could come if the user choose to apply a different facet to a file into the same folder, causing a change to the expression.
Also, if a user has applied a rule starting from the GlobPicker mentioned in #562 , we should be able to check if some of the activities done in the FileList are in conflict with those rules, and create an exception.

**Comment by storrisi** [comment]
As mentioned in #562 , our proposal is to start building the GlobPicker first.
Then we can see from there if a smarter UX could help the user to build glob expressions in a more easy way.
Maybe from there some changes will occur to this specific requirement, or even consider this as superseded.

**Comment by storrisi** [comment]
@fossygirl we can start with the implementation of the tooltip and remove the term glob expression entirely from the UI. Do you agree?

>Add selectors on the files and folders and give users feedback to let them gesture those files or folders into facets more easily

As discussed in #562 we should take a decision about implement the FileList facets editing capability or a GlobPicker at first.

**Comment by storrisi** [comment]
Following the discussion on today's weekly meeting:
- we need need to implement validation on user entries on globs
- just add incremental functionality to add a facet to the file list
- only select a facet on folder

Note: if a non-core facet is selected, core will not be selected

**Comment by gianpaj** [comment]
Regarding:
> To remove the term glob expression entirely from the UI

what should we have instead of "Add a valid Glob expression"?

<img width="557" alt="ClearlyDefined" src="https://user-images.githubusercontent.com/899175/54754745-f2d63380-4bec-11e9-8984-d397bf44efca.png">

**Comment by fossygirl** [comment]
@gianpaj Let's just leave that for now.
