### ISSUE TITLE
Add "has pending curation" tag to definitions

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#479]
If there is an open PR on a definition we should display to a user viewing that component that it has a pending curation. We should give them a place to click in the UI so they can get a new window and see the PR on GitHub.

**Comment by storrisi** [comment]
This one is already implemented in the UI, see #290 

We should really address the service to return these details, since several issues are related to the same response.

**Comment by fossygirl** [comment]
Great, maybe @dabutvin can weigh in here.

**Comment by storrisi** [comment]
@dabutvin this is also related to our discussion about the `expanded=prs` params, which i've addressed in https://github.com/clearlydefined/service/issues/408

**Comment by AlexWebYourmind** [comment]
@storrisi @fossygirl @dabutvin can we close this?

**Comment by storrisi** [comment]
Maybe yes, the label already exists on the UI, we need only the service to return the data.

**Comment by fossygirl** [comment]
Nope, we can't close it until I can see these labels on the components, which I don't yet.

**Comment by AlexWebYourmind** [comment]
@storrisi can you look into this?

**Comment by storrisi** [comment]
Actually the implementation is already there from a UI point of view, see #290 

As we discussed in the weekly meeting, the curation details should be returned from the service to complete this.
I think @dabutvin is already looking at this.
There is an opened issue for this: https://github.com/clearlydefined/service/issues/408

**Comment by dabutvin** [comment]
yep. I've been looking into this, there is some updates I need to make to the database schema to enable these queries.
https://github.com/clearlydefined/service/issues/411

**Comment by storrisi** [comment]
This has been implemented in #515 and could be closed

**Comment by fossygirl** [comment]
Closing, this is displaying now! 🎊
