### ISSUE TITLE
Curation metadata is not visible when viewing a component definition

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#485]
**Type:** Bug
**Description:** The "Curation" tab found on definitions pages do not appear to render any detail about the curation.

**Steps to Recreate**
1. Search up an already curated component in CD
2. Dig into that component's definition
3. Go to the bottom of the definition page to the following three tabs: "Current definition", "Curations", "Harvest data"
4. Click the "Curations" tab

**Expected Result**
On curated components, you should see data reflecting the approved curations.

**Actual Result**
Data is not shown, but instead the tab section is blank.

**Example test:** https://clearlydefined.io/definitions/npm/npmjs/-/zlib/1.0.5

![image](https://user-images.githubusercontent.com/31491646/53273041-c4297380-36a7-11e9-8c1d-7d63c51b6433.png)

**Comment by storrisi** [comment]
This has been fixed in #515 and can be closed
