### ISSUE TITLE
Fix mobile view of Full Details

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/website#488]
Related to #95

<img width="294" alt="schermata 2019-02-25 alle 11 43 18" src="https://user-images.githubusercontent.com/7654979/53332045-a865dd80-38f2-11e9-916b-7118b5638b69.png">
<img width="291" alt="schermata 2019-02-25 alle 11 43 36" src="https://user-images.githubusercontent.com/7654979/53332044-a865dd80-38f2-11e9-9dd5-a0920df8e000.png">

<img width="293" alt="schermata 2019-02-25 alle 11 43 47" src="https://user-images.githubusercontent.com/7654979/53332043-a865dd80-38f2-11e9-8d39-956ff9504477.png">

@fossygirl as discussed in #74 i'm not 100% sure that we should show or give to the user the same capabilities of a desktop view in a mobile view.
Is the user supposed to make a contribution in a mobile view, or maybe he could access to a read-only view?

**Comment by gianpaj** [comment]
FYI: in the discussion the solution to was to hide the FileList and Raw data on mobile screen sizes
