### ISSUE TITLE
Browse: License list is too restrictive/short

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#496]
The list of available licenses to filter by is too short. At the very least we should expose all those available from choosealicense.com. That way we are not making a judgement call other than following in their footsteps. That might be too long a list (~36?). Not sure. 

We could instead of a dropdown use the license picker here and let people pick from the full list. would take more real estate but should work reasonably.

Consider a dropdown list like we see in GitHub where the list of choices is long but users can filter by typing at the top. Pretty sure at least one of the component libs we are already using has this capability

**Comment by storrisi** [comment]
Using the LicensePicker is a great idea, it allows the user to pick any kind of license he wants.

As for #500 we could also display the current selected license.
