### ISSUE TITLE
Browse: button styling should be updated

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#499]
The buttons/dropdowns on the /browse (and other) pages have outlines 

![image](https://user-images.githubusercontent.com/10070956/53358740-fde7bd80-38e5-11e9-9f66-7172c32ffa00.png)

whereas it would be much better for them to look like what you see on GitHub itself

![image](https://user-images.githubusercontent.com/10070956/53358828-32f41000-38e6-11e9-921d-f2fc9ca45b26.png)

apply this same change to all lists

**Comment by storrisi** [comment]
Addressed in #545
