### ISSUE TITLE
Browse: "Raise" level of "Provider" and "Curate" buttons

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#500]
The Provider and Curate buttons on the /browse page are great. So great that perhaps they should be "elevated" to be outside the list component, perhaps at the same (conceptual) level as the name filter.

From a user point of view then they can discover at a coarse grain (name, provider, viewpoint) and dive in with finer filters/sorts.

* also consider showing the current value in the button

**Comment by storrisi** [comment]
Is the search by Provider something similar to #158 ?

**Comment by storrisi** [comment]
Following the discussion on weekly meeting, we want just to make clear to the user which kind of search he's currently doing on the Browse Page.
