### ISSUE TITLE
Browse: Curate choices should be Effective and Tool

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#501]
As with the sort choices discussed in #495, the Curate choices should be Effective and Tool.

We will have to come up with other ways to talk about the domain-specific scores (e.g., described and licensed and secure, ...)

**Comment by storrisi** [comment]
@jeffmcaffer as per your comment and changes on #495 , should this one change as well somehow?

**Comment by storrisi** [comment]
This has been addressed in #564  and can be closed
