### ISSUE TITLE
Move current home page content to About

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#502]
To allow the browse page be the home page for clearlydefined.io we need to move the current home page content to About and some how merge with the current content there

**Comment by gianpaj** [comment]
Hi @jeffmcaffer,

How should we merge the content of both pages?

<img width="1074" alt="about_png_and_homepage_png_and__curation" src="https://user-images.githubusercontent.com/899175/53798425-e42b2380-3f40-11e9-9c48-a322571b56f4.png">

Maybe we could replace the text-heavy content (until Get Involved) from the About page with the sections of the current Homepage?
And, move that from the About page to the docs homepage?

**Comment by jeffmcaffer** [comment]
I will take care of this. Updating the title...
