### ISSUE TITLE
Link between binary package components and source repositories

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/website#503]
Often the best source information for a given binary package is the corresponding source tree used to produce that package.  Having a simple way to curate both components simultaneously would be helpful.

**Comment by jeffmcaffer** [comment]
When you are looking at a binary component in the definitions list, there `</>` button that will add the corresponding source component to the definitions page. See 

![image](https://user-images.githubusercontent.com/10070956/53362193-75b9e600-38ee-11e9-9137-b8345166f8b7.png)

From there users can modify both and submit one curation.

Does that address your scenario?

**Comment by royaljust** [comment]
Yes, it does.  Thanks for the quick reply Jeff!
