### ISSUE TITLE
Update look of contribute dialog

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#504]
Looking at the screenshot for the current contribute dialog (below), I suggest some changes...

-  make the dialog narrower
-  move "Type" over to the left and allow the choice to be beside rather than below the "Type" label
- consider putting some data entry parts side by side rather than using a single column

<img width="1224" alt="clearlydefined" src="https://user-images.githubusercontent.com/899175/53360446-3adf9e80-393e-11e9-90d6-f801b5c498b0.png">

**Comment by storrisi** [comment]
We'll address this into #493 , since it's already addressing some changes on the Curation popup

**Comment by storrisi** [comment]
This one could be closed since has been addressed in #493 .
Unfortunately i forgot to mention this issue into the PR so the automation didn't worked.

**Comment by dabutvin** [comment]
Looks like the changes we took here also affected the license expressions modal. Can you take a look at that as part of this issue?

**Comment by storrisi** [comment]
@dabutvin sure! Thanks for catching it
