### ISSUE TITLE
hide the blue border

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#505]
In the /definitions list (and elsewhere) there are cases where you click on an entry / element and its border is changed to a blue glow. See the screenshot below. I had just clicked on one of the entries in the list and the whole list starts to glow. This is distracting, exposes the component hierarchy (why not glow more? or less? of the DOM?), and does not guide the user.

![image](https://user-images.githubusercontent.com/10070956/53370971-f800d500-3903-11e9-861c-d4bdbafcaf81.png)

Previously I have looked for ways to do this but for whatever reason never found success.

**Comment by dabutvin** [comment]
this is the focus outline and can be removed with `outline: none` on the grid control.
We should make sure this doesn't break navigating by keyboard when it is removed
