### ISSUE TITLE
Make a better curation description dialog

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#51]
Currently when a user clicks Save Curation on the Curate page, a dialog pops up asking for a description of the changes. This ends up being the PR comment. The Dialog currently has crappy styling. Need to fix using Bootstrap components so that it looks reasonable.  There should be ample space for a non-trivial description. Say 10 lines? Perhaps growable if that is possible in the modal/overlay.

**Comment by jeffmcaffer** [comment]
In addition to style improvements, we should try to put some sturucture to the pull requests. Effectively a PR template. Don't have to get too fancy but something like is shown below. Given that, what is the best UI we can do to get the right result. (e.g., dropdowns for enum fields, ...)

**Type:** [ Missing | Incorrect | Incomplete | Ambiguous | Other ]

**Description:**
<free text describing the problem being addressed ...>

**Resolution:**
<what does this PR do to address the issue ...>

**Supporting info:**
<references to docs where the new data was found, pointer to public conversations with the affected project team, ...>

**Comment by jeffmcaffer** [comment]
superceded by #282

**Comment by AlexWebYourmind** [comment]
Closing This issue.
