### ISSUE TITLE
Consider removing dropdown options that are "not implemented"

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#513]
I think it gives the user a poor impression of the software to see options they can't have because they're "not implemented." Let's remove these from the drop down or actually make them real. Let's not tell our users they just can't have something. 
![screen shot 2019-02-26 at 3 15 41 pm 2](https://user-images.githubusercontent.com/17101092/53453646-96129f00-39d9-11e9-8bb3-5fdba46550e5.png)

**Comment by AlexWebYourmind** [comment]
@fossygirl Yeah. This was actually agreed and implemented as part of https://github.com/clearlydefined/website/issues/271 (not the Gist one).

If we believe that the iniital approach served its purpose and we can remove not implemented options, we can proceed with that.

**Comment by jeffmcaffer** [comment]
The Gist entry (and associated code) should be removed. It is actually implemented but to write a Gist we need a token that has write permissions and we don't want to ask the user for those perms.

The others should IMO stay as they signal direction/intention.
