### ISSUE TITLE
Remove the "UNLICENSED" wording from the UI

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#522]
Using "UNLICENSED" in the UI is rather confusing as the "UNLICENSE" is a public-domain-like license. I reckon NPM does that, but that's a poor choice of words as an npm license value of `UNLICENSED` and `UNLICENSE` would both be valid and mean completely different thing..

I suggest using "not licensed" or "no license stated" or anything else.

FWIW, "Unattributed" also sounds a tad weird: "no copyright statement" ... or something might be better

**Comment by storrisi** [comment]
This has been addressed in #536 and could be closed

**Comment by fossygirl** [comment]
I have verified this is fixed in the UI. @pombredanne please reopen if you find that's not the case.
