### ISSUE TITLE
Make OK/Cancel coloring, placement, and wording consistent across the site

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#526]
In some places we use the language "dismiss" in other places we use "cancel" in some places we use "okay." Let's make the language on the buttons consistent.

We also need consistency amongst the coloring and placement of the buttons. Sometimes Cancel is on the right, sometimes on the left, and sometimes it's red, sometimes it's not, etc.

Please make all this consistent across every UI on the site.

**Comment by storrisi** [comment]
This has been addressed in #537 and could be closed

**Comment by fossygirl** [comment]
I've verified this is consistent as best I can. If we find any inconsistencies we can reopen.
