### ISSUE TITLE
Fix buttons on /curation and the 'Collapse All' in /definitions

### ISSUE THREAD

**Issue by gianpaj** [clearlydefined/website#531]
We noticed that the buttons at the top on a /curation (e.g [link](https://dev.clearlydefined.io/curations/185)) "Done" and "Collapse All" are always disabled and don't do anything.

- Should we remove the "Done" button? I believe it's not possible to make any changes in this page currently.
- Should we fix the "Collapse All" button and make sure it also expands all the components when clicked back? (the same for [/definitions](https://dev.clearlydefined.io/definitions) page)

**Comment by jeffmcaffer** [comment]
Good catch. Seems like we can remove the Done button as you suggest. Fixing Collapse would be great.
