### ISSUE TITLE
tweak new File List view

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#533]
The new Ant Design based file list view is a good improvement. A few styling suggestions

* remove the line between files
* make each row shorter (smaller height)
* change the amount of indentation on the tree part (need to deal with long paths in Java)
* Expand the first level by default

**Comment by storrisi** [comment]
Some of these fixes are already been addressed in #525 

> Expand the first level by default

This was part of a discussion with @dabutvin 
It makes sense when the list of files has only one main folder, otherwise the tree is already naturally open to the root, which show all the nested folders and files that are in the root directory.

**Comment by storrisi** [comment]
Changes from #525  are in place.
If you are happy with those change, then this issue could be closed.

**Comment by jeffmcaffer** [comment]
Looking better. thanks!  Items 2 and 3 in the original list still need to be addresses AFAICT.

![image](https://user-images.githubusercontent.com/10070956/53839261-ee065400-3f4b-11e9-8436-0b1d94de3661.png)

Note in the image I hacked the CSS directly to 
* set the height of each line considerably smaller (essentially 0 padding). could be a bit higher but not much.
* lower the height of the facet label to 20px. That is in line with the height on the new score labels
* change the indent from 8px of padding to 0px

To do:
* codify the above changes
* center vertically the words in the facet label
* make the triangle "twisty" smaller (probably down to about 75% of its current size)
* remove or make much smaller the "Revert changes" button (it is very dominant in the visual effect)
* make sure the left indent padding change ripples all the way down the tree.
* change the hover background of the twisty triangle to be transparent. As it is, when you hover over it, there the white rectangle background shows.
