### ISSUE TITLE
Errors and warnings in console for /definitions

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#540]
There are a few errors and warnings in the /definitions page on normal load. We should strive for there to be no errors or warnings (no output at all really). Here is the dump I see. 2 warnings and an error
```
WARNING 1
react-ga.js:204 [react-ga] gaTrackingID is required in initialize()
warn @ react-ga.js:204
_initialize @ react-ga.js:385
initialize @ react-ga.js:429
./src/index.js @ index.js:10
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ withTracker.js:38
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1


ERROR 1
index.js:1446 Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by AutosizeInput)
    in div (created by AutosizeInput)
    in AutosizeInput (created by HintedInput)
    in div (created by HintedInput)
    in HintedInput (created by TypeaheadInput)
    in div (created by TypeaheadInput)
    in div (created by TypeaheadInput)
    in TypeaheadInput (created by WrappedInput)
    in WrappedInput (created by Typeahead)
    in div (created by Typeahead)
    in Typeahead (created by WrappedTypeahead)
    in WrappedTypeahead (created by WrappedTypeahead)
    in WrappedTypeahead (created by Typeahead)
    in Typeahead (created by OnClickOutside(Typeahead))
    in OnClickOutside(Typeahead) (created by Container)
    in Container (at FilterBar.js:41)
    in FilterBar (at SearchBar.js:11)
    in div (created by Col)
    in Col (at SearchBar.js:10)
    in div (created by Row)
    in Row (at SearchBar.js:9)
    in SearchBar (at PageDefinitions.js:162)
    in div (created by Grid)
    in Grid (at PageDefinitions.js:155)
    in PageDefinitions (created by Connect(PageDefinitions))
    in Connect(PageDefinitions) (at withTracker.js:33)
    in HOC (created by Route)
    in Route (at RehydrationProvider.js:61)
    in Switch (at RehydrationProvider.js:60)
    in main (at App.js:13)
    in div (at App.js:11)
    in App (at RehydrationProvider.js:59)
    in Router (created by BrowserRouter)
    in BrowserRouter (at RehydrationProvider.js:58)
    in Provider (at RehydrationProvider.js:57)
    in RehydrationDelayedProvider (at src/index.js:18)

WARNING 2
webpackHotDevClient.js:120 ./node_modules/antd/dist/antd.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/antd/dist/antd.css)
Warning

(168:11) Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed
```

**Comment by storrisi** [comment]
This has been addressed in #539 so it could be closed

**Comment by jeffmcaffer** [comment]
This issue covers all the things that are NOT covered by #539. Please take a look at the errors/warnings independent of that PR

**Comment by storrisi** [comment]
I see, thanks. I will fix those.

**Comment by storrisi** [comment]
@jeffmcaffer for the first error:
`react-ga.js:204 [react-ga] gaTrackingID is required in initialize()`

looks like the application is expecting an external param configured in the environment.
`ReactGA.initialize(process.env['REACT_APP_GA_TRACKINGID'])`

This doesn't happen in production, so i guess that we could add a check that doesn't initialize GA for local and dev environment. What do you think?

**Comment by storrisi** [comment]
The second error is tracked [here](https://github.com/ericgio/react-bootstrap-typeahead/issues/381) and looks like to be a Typeahead problem.
I'm looking forward if we are able to upgrade the version.

**Comment by storrisi** [comment]
Upgrading the version of Typeahead introduces an error on `GitHubSelector`, since the method `_updateText()` is not available anymore.

**Comment by storrisi** [comment]
I had some issues with Typeahead.

First of all, upgrading it, to remove the error mentioned here, will cause an error while using the _updateText() method, and it looks like there isn't any other available method that replaces it.

Then, while working on another issue i've tried to clean up the value of the field when clicking on a button.
Using the method already implemented that clear the value doesn't solve the problem.

I'm thinking if we maybe could switch to another similar lib package that implements all of our requirements in a better way.

@jeffmcaffer  what do you think?

**Comment by storrisi** [comment]
As discussed today, we are going to investigate on an update or even a replacement for Typeahead.
We are going to start smart and try to implement this in some specific points, like the SourcePicker.

**Comment by dabutvin** [comment]
I think we should keep the current typeahead for the workspace and browse pages - and upgrade to the latest version - it seemed to work pretty well with the latest. But like you mentioned, we can't use those updateText methods this way. Instead, I think we should rethink the way the sourcepicker works as a whole.

![image](https://user-images.githubusercontent.com/5168796/54553302-1c822700-496f-11e9-9b4f-a26b9cf5516c.png)


The reason we have this is for the `/` character workflow

some ideas:
 - be able to drag and drop a Github url
 - be able to paste a commit hash
 - separate repo owner and repo name into separate boxes
 - combine results for owner and repo name from a single search term

**Comment by storrisi** [comment]
> separate repo owner and repo name into separate boxes
> combine results for owner and repo name from a single search term

I thinks these are the 2 main options to consider an upgrade of Typeahead and removing the updateText() method.

Probably combine the results would help to search immediately for any portion of the string?
