### ISSUE TITLE
Tools list cuts off

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#547]
When we have a bunch of tools run on a component the list gets cut off. We should either wrap the text or enable hover for the full details of the text.

![screen shot 2019-03-06 at 11 24 50 am 2](https://user-images.githubusercontent.com/17101092/53907744-aabaec80-4002-11e9-8ca0-e0bd5cf263fa.png)

**Comment by gianpaj** [comment]
I've noticed here that the values in `tools` array gets trimmed if they start with `curation`:

https://github.com/clearlydefined/website/blob/dba0a8175cfc198927cd9ea1841691d67e76f8b5/src/components/Navigation/Sections/DescribedSection.js#L34-L36

In which circumstance could tools start with `curation`?
Would you know @dabutvin ?

**Comment by gianpaj** [comment]
Got a reponse from Dan via Discord:

> when a curation is merged it gets added as a tool
look at https://clearlydefined.io/definitions/nuget/nuget/-/Newtonsoft.Json/10.0.2

**Comment by jeffmcaffer** [comment]
We should remove the code that slices off the beginning of the tool in the case of `curation`. Not sure why that was added in the first place.

**Comment by dabutvin** [comment]
we are slicing off the end of the string.

instead of 
```
curation/1032ce558db47eee59b75d84132f5fbe6e19efbb
```

we show 
```
curation/1032ce5
```

I think this makes sense in this case
