### ISSUE TITLE
[Browse] update name search box to use typeahead

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#548]
see https://github.com/clearlydefined/service/issues/429 for some context

We want to put in exact matches to the search box for names and typeahead should be able to help us with this.

this is rough idea of what I'm thinking

1. Call https://api.clearlydefined.io/definitions/?pattern=jqu like we do from /definitions
2. parse each coordinate response into EntityCoordinates
3. make a distinct list of coordinates.name
4. let the user choose one of the names
5. update the query with ?name=<selection>

This isn't ideal, but may be a good stopgap

**Comment by storrisi** [comment]
I see. I've tested the behavior on the UI and i didn't notice before that the browse list returns some data only while the name is matching the name of a definition.
Your idea seems to solve the problem.
I will implement this.
