### ISSUE TITLE
suggestions not showing up in UI

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#549]
Looking at the full details for a random definition I am not seeing the "suggestions" blue "i" showing up. Using developer tools I also do not see the suggestions api being called. Did this get broken somewhere? is there something else the user needs to be doing to make this work?

**Comment by storrisi** [comment]
I'm checking the behavior but looks like that the endpoint is called correctly.

![schermata 2019-03-07 alle 09 08 07](https://user-images.githubusercontent.com/7654979/53941510-8d485a00-40b8-11e9-9cc9-f2e46aba09b5.png)

Unfortunately i'm not able to find a definition that has suggestions.
Those would show up only for fields that are missing, but the endpoint didn't return any suggested value.
Could the "NOASSERTION" value on declared.license broke something on this process?

**Comment by storrisi** [comment]
Looks like that in the dev environment every call to the suggestions API fails with a 404 error, see https://dev-api.clearlydefined.io/suggestions/nuget/nuget/-/Handlebars.js/3.0.0

Maybe a change has been introduced on the service that broke something?

**Comment by dabutvin** [comment]
I'm seeing it work in prod but not dev

![image](https://user-images.githubusercontent.com/5168796/53986950-5d0eb480-40d4-11e9-9dbc-df81947b9b74.png)

Investigating

**Comment by jeffmcaffer** [comment]
@dabutvin  has fixed the issue in Dev so in the end this is just user error on my part.

As a side note, it might make sense for us to always show the suggestions `i`. Otherwise it is sometimes there and sometimes not and users don't really have a sense of why. If there are no suggestions then we can simply say that there are none. Not sure. Need some users to comment.
