### ISSUE TITLE
Browse: What selection you've made is not obvious

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#572]
You may not be able to tell it from the screenshot, but I have currently filtered on Provider="npmjs."

That is not obvious after the filter is applied. The background on the Provider dropdown lit up and the list is only displaying npms. But I could easily see a user forgetting they've applied a filter on this page and not understanding how to un-apply it. 

![Screen Shot 2019-03-08 at 8 13 24 PM](https://user-images.githubusercontent.com/17101092/54066075-e5797c00-41de-11e9-84a9-1c9894c386f3.png)

**Comment by storrisi** [comment]
We can show the value of the selected provider in the Button, as well as show a 'x' icon to clean the selection, as part of #573
