### ISSUE TITLE
Browse: Revert changes button not working

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#573]
Applying a filter of Provider="npmjs" and then clicking the Revert changes button does nothing.

**Comment by storrisi** [comment]
The Revert button is supposed to Revert any kind of change over the definitions, not to clean up the search.
For that behavior we should implement a different kind of button or allow the Provider button to a have a "reset" option.

**Comment by storrisi** [comment]
Actually the Provider button has already a reset option, you could select again the same value and the selection got cleaned.
Probably a button that cleans the entire search (provider, name) would be better. 
What do you think @fossygirl ?

**Comment by fossygirl** [comment]
@storrisi Sure, that would be fine. It just needs to be easy for the user to understand how to "undo" whatever they just did.

**Comment by storrisi** [comment]
Since i've made an update on Typeahead in #611 i will continue the work on this one once the changes will be in place.

**Comment by fossygirl** [comment]
@storrisi @dabutvin Is this obviated or still in progress?

**Comment by storrisi** [comment]
We've done several changes since this issue has been opened.
Now we have a Filter Bar that shows all the applied filters and sorts, and the user is able to reset any kind of selection.
I think that that implementation covers also this requirement, so we can close this one.
