### ISSUE TITLE
Consider having the Browse page change sort on refresh

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#592]
Right now visitors to the website see the same list every time with Crates first (because the list is alphabetical). Since this page is meant to spur interest and give folks with no other information a place to get started, it might be nice to have the list sort/populate differently on refresh. This was each time a person visits they'll see something new and might be enticed to help out on seeing new things.

**Comment by storrisi** [comment]
We can do it from the website only applying different random filters or sorting on each reload and pass those values to the API call.

Otherwise, this should be done from the service and only when any other filter is already applied.

@dabutvin do you have any thoughts on this one?

**Comment by storrisi** [comment]
@dabutvin do you have any feedback on this one?

**Comment by DennisClark** [comment]
How about the default sort being Date Modified descending; that is, show most recent updates at the top.

**Comment by storrisi** [comment]
As discussed in the weekly meeting, we're going to sort by release date as a default

**Comment by storrisi** [comment]
@dabutvin should the UI implement a default sort on the page or the API would return the results sorted by the mentioned property?

**Comment by storrisi** [comment]
@dabutvin do you have any feedback on my last question?

**Comment by storrisi** [comment]
Thanks @dabutvin , i will work on this.
