### ISSUE TITLE
Replace 'Copy URL' with 'Open in new tab'

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#598]
![image](https://user-images.githubusercontent.com/5168796/54541894-06b53780-4958-11e9-88d4-40c16aa6a8a0.png)

The argument is that the primary reason you are copying the url is to get it open in a new tab, as well, when you open a new tab you have access to the url easily in the address bar if that's what you are after.

![image](https://user-images.githubusercontent.com/5168796/54542143-77f4ea80-4958-11e9-948d-79d718b14cb8.png)

This shows switching the icon to `fa-external-link-alt`

Clicking it would open a new tab instead of copying the url to the clipboard

**Comment by pombredanne** [comment]
This is an improvement ++  and there is more to do to improve the navigation IMHO (I have entered #599 for that).

**Comment by storrisi** [comment]
@dabutvin i agree. If copying the url hasn't any other purpose, then a link would be enough.
Should we bring this in place?

**Comment by dabutvin** [comment]
I'm all for it! Sounds like @pombredanne is on board too. Let's do it
