### ISSUE TITLE
Accessibility issues with using logos/icons for component type

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#600]
In the browse list, the recent introduction of using a logo/icon for types is confusing unless you are extremely familiar with the logo of a type. It is furthermore not accessible. I would prefer to have a text for this instead

**Comment by storrisi** [comment]
We recently added a tooltip over the logo. Do you think it could be enough from your point of view?

**Comment by storrisi** [comment]
@pombredanne do you have any thoughts on my question above?

**Comment by storrisi** [comment]
@pombredanne I'm likely to close this since we've introduced a tooltip over the logo of each component, that looks to meet your requirement. Do you have thoughts on this?

**Comment by storrisi** [comment]
Closing this for now since we have tooltips that explain which is the related type for each component.
Feel free to open it again if needed.
