### ISSUE TITLE
Cannot search using namespace

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#602]
On the browse page I type `@angular` that is the namespace of several packages and nothing is found. The namespace should be used in search

**Comment by dabutvin** [comment]
👍 this was a shortcut we took to get something working and for sure needs to be followed up on.

Maybe we can add `namespace` and `name` in the same list to choose from?

**Comment by pombredanne** [comment]
@dabutvin re

> Maybe we can add namespace and name in the same list to choose from?

If you mean search in both fields at once, yes. Search-wise, I would think that what you search on is `namespace/name`

**Comment by storrisi** [comment]
@dabutvin is this a change that needs to be applied on the service side?

**Comment by storrisi** [comment]
@dabutvin do you have any feedback on this?
