### ISSUE TITLE
In the browse page consider using type rather than provider as a filter

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#603]
The provider is a proxy for a place. When I search for packages I would typically rather filter by type (npm, maven, etc) than the place they are from.

**Comment by storrisi** [comment]
@jeffmcaffer @dabutvin @fossygirl what do you think? We can even add an additional filter to the browse page.

**Comment by dabutvin** [comment]
How about we replace provider with type?

**Comment by pombredanne** [comment]
@dabutvin this would work fine. :+1:

**Comment by dabutvin** [comment]
let's do this!
