### ISSUE TITLE
Cannot find "flyway-core"

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#610]
I type flyway-core in the search box. This is effectively listed as a possible value in the dropdown. Yet when I select "flyway-core" nothing shows up at all. This seems to be the case of several Maven-related records.
![Screenshot from 2019-03-19 15-24-40](https://user-images.githubusercontent.com/675997/54613573-35680680-4a5b-11e9-8a9f-992577bbbc1e.png)

**Comment by storrisi** [comment]
I've tried that search in production and i've actually found `flyway-core`
<img width="1210" alt="Schermata 2019-03-21 alle 15 21 56" src="https://user-images.githubusercontent.com/7654979/54758763-15684c80-4bed-11e9-9932-d04522d2b3d5.png">

**Comment by dabutvin** [comment]
I've been pushing on getting all the definitions updated in the database and just now getting through the mavens.

The textbox is driven from the search index and the queries for the result list are driven from the mongo definitions store. We were likely experiencing search being ahead of the definition being recomputed.

**Comment by pombredanne** [comment]
@dabutvin @storrisi this makes sense then. Thanks!
Let's keep this open a bit to make sure this is the problem alright.

**Comment by dabutvin** [comment]
agreed.

I've been thinking about other ways to keep these stores in sync and at the same time increase our query capabilities. Our search index is just used for coordinate suggestions today and I'm hoping to use it for better stats capabilities in the future, answering questions like "How many mavens have an MIT license?"

These questions are very expensive to answer with our MongoDB and the way we are partitioning so much data

**Comment by storrisi** [comment]
@dabutvin do you think we can close this one?

**Comment by dabutvin** [comment]
yep. I think we are all mirrored now!
