### ISSUE TITLE
Browse: error when making a contribution

### ISSUE THREAD

**Issue by gianpaj** [clearlydefined/website#614]
```
SystemManagedList.js:342 Uncaught TypeError: _this.buildSaveSpec is not a function
```

Steps to reproduce:

1. Make any changes on a definition in the [browse page](https://dev.clearlydefined.io/)
2. Fill the contribution form and press the green OK button
3. See the error in DevTools

The user is still able to make a contribution but I'm not sure what are the repercussions with this issue.
I believe the fix is to move the function from `UserManagedList.js` to `SystemManagedList.js`

**Comment by dabutvin** [comment]
looks like we are getting a similar error from the workspace page, so not sure if moving from userManaged to systemManaged will help
