### ISSUE TITLE
PR not being opened after contribution submitted

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#618]
@iamwillbar just tried to submit a contribution and got a message that the contribution was started but the PR was never opened

@dabutvin can you confirm this is a website issue and not a service issue?

**Comment by fossygirl** [comment]
@dabutvin Okay, it actually did open https://github.com/clearlydefined/curated-data/pull/1144 but the time delta was a full 2 minutes.

**Comment by iamwillbar** [comment]
Also saw the following errors in the console:

```
Uncaught TypeError: n.buildSaveSpec is not a function
    at t.n.refresh (SystemManagedList.js:332)
    at t.value (SystemManagedList.js:118)
    at t.value (ContributePrompt.js:47)
    at Object.<anonymous> (react-dom.production.min.js:49)
    at d (react-dom.production.min.js:69)
    at react-dom.production.min.js:73
    at k (react-dom.production.min.js:140)
    at T (react-dom.production.min.js:168)
    at L (react-dom.production.min.js:181)
    at j (react-dom.production.min.js:158)
2curations:1 Failed to load resource: the server responded with a status of 524 ()
(index):1 Access to fetch at 'https://api.clearlydefined.io/curations' from origin 'https://clearlydefined.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by dabutvin** [comment]
were you on the browse page when you made the contribution?
see #614

**Comment by dabutvin** [comment]
also looks like there was a 524 error in there somehow

**Comment by fossygirl** [comment]
@dabutvin No, he was on the Workspace page.

**Comment by iamwillbar** [comment]
I was on the home page so I'm not sure which page that is specifically...

**Comment by dabutvin** [comment]
ahh - that's what we call browse page - it used to be at /browse, but now it is the homepage. Thanks

**Comment by storrisi** [comment]
I'm investigating on this problem.

**Comment by storrisi** [comment]
The problem was the same of #614 and it has been addressed in #619

**Comment by fossygirl** [comment]
I was able to replicate this behavior on the /workspace page as well. I submitted the contribution and got two popups but no PR until about 30 seconds later. 

@dabutvin

**Comment by dabutvin** [comment]
I don't think this is a website issue, we are getting a 524 from the service in prod during curations.

**Comment by dabutvin** [comment]
![image](https://user-images.githubusercontent.com/5168796/54789510-ebfcf000-4bef-11e9-9711-ce190cedbb4a.png)

**Comment by storrisi** [comment]
@dabutvin do you think we can close this one, or we need it to track it some still existing problems?

**Comment by storrisi** [comment]
@dabutvin do we need to keep this one open for some reason?

**Comment by dabutvin** [comment]
ahh I couldn't find this one earlier I opened https://github.com/clearlydefined/service/issues/487 on the service side

**Comment by dabutvin** [comment]
i just had a pr open very fast, not sure if this was an anomaly
