### ISSUE TITLE
LicensePicker crashes if the typed license is not valid

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/website#620]
When working on the Components list, and you edit a License of a Definition typing some non-valid chars, that are not matching any existing License, then if from there you open the LicensePicker, this will fail returning a runtime error.

I think we should allow the user only to select one of the values from the list of Licenses, avoiding him to type any kind of character.

**Comment by dabutvin** [comment]
Nice find.

I do think we should retain the ability to type a valid expression without using the modal expression builder.

We have the ability to parse and validate expressions. It would be great if, when the expression typed was valid, then it gets dynamically added to the list

**Comment by storrisi** [comment]
I agree with your suggestion except for one point:

> then it gets dynamically added to the list

What do you mean exactly? Should we consider to add valid expressions to the list that we actually show to the user?

**Comment by dabutvin** [comment]
I was thinking that as soon as the expression becomes valid, it shows up in the list as a selection

**Comment by storrisi** [comment]
Something like we're already doing with the GitHub commit picker i guess.
