### ISSUE TITLE
Incorrect license score and file lists

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#622]
https://clearlydefined.io/definitions/npm/npmjs/-/svgo/1.1.1 is reported with 100 license score which is rather incorrect. A single `LICENSE` file is reported for the entire package which is likely the source of the issue

**Comment by storrisi** [comment]
Probably this should be opened in the service repo, since the UI is showing what the API is actually returning.
See https://api.clearlydefined.io/definitions/npm/npmjs/-/svgo/1.1.1?expand=prs

**Comment by dabutvin** [comment]
I just reharvested this one to get the latest tools.
https://api.clearlydefined.io/definitions/npm/npmjs/-/svgo/1.1.1 showing a licensed score of 46 now

**Comment by storrisi** [comment]
@dabutvin do we need to keep this one still opened for some reason?

**Comment by dabutvin** [comment]
no probably not, we've been doing a good job getting all the old data re-harvested.
