### ISSUE TITLE
Retry loading a definition entry when it has no data

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#624]
You can add components into a definition list that are not yet harvested. This can happen in a few ways. For example, from dragging and dropping a `package-lock.json` file or a URL to the workspace, or from adding more versions of an existing component.

When this happens, we notice it is missing from our dataset and go off and harvest the component - often times very quickly.

IT is hard to know when the data is available and can require a lot fo manual interaction. Instead of removing and adding the entry from the list to get the new data, the website should check back to the service periodically to see if the definition is available now without any interaction from the user. 

This would allow the user to work through the reset of the components in the list while this happens in the background.

**Comment by storrisi** [comment]
It could be useful to check only for components that needs to be harvested.

I'm just wondering if:
- we have some kind of information to identify those components
- how many times, and how often, we should check for the response from the server?

**Comment by storrisi** [comment]
I've investigated a little on this.

Probably the best way to identify these components is to check if the field `described.tools` is missing.

@dabutvin what do you think?

**Comment by storrisi** [comment]
@dabutvin do you have some thoughts about this? This is not a complex implementation, so if we decide the best way to identify these items, we can drive the development soon

**Comment by dabutvin** [comment]
described.tools is definitely the way to check.
I'm hesitant to integrate this until a little further down the road and our harvest queue quiets down
