### ISSUE TITLE
Download component button doesn't work

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#634]
Download component button doesn't work when there are scopes on an npm.

@dabutvin

**Comment by gianpaj** [comment]
Hi @fossygirl,

Could you please provide the URL of a definition when this issue happens?

Thanks

**Comment by fossygirl** [comment]
Here: https://clearlydefined.io/definitions/npm/npmjs/@microsoft/sp-module-interfaces/1.8.0

**Comment by storrisi** [comment]
Looks like the url returned from the service is wrong.
The UI links correctly to the provided URL, which returns `error: "exception parsing path /sp-module-interfaces/@microsoft/sp-module-interfaces-1.8.0.tgz"`

I'm going to investate on this, but this is a service issue so we can close this one and track the same problem on the service repo.

**Comment by storrisi** [comment]
I've opened https://github.com/clearlydefined/service/issues/463 which address this problem.

**Comment by fossygirl** [comment]
Sure, closing.
