### ISSUE TITLE
Sort by newer doesn't sort by newer release date

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#635]
See attached screenshot. I searched for "mitm" on provider: npmjs and then sorted by "newer"

![Screen Shot 2019-03-28 at 7 54 37 AM](https://user-images.githubusercontent.com/17101092/55167801-e000b900-512e-11e9-9f0d-cd2bf318a215.png)

You'll see a release date of 2018 appear both before *and* after a release date of 2017.

**Comment by storrisi** [comment]
As for #637 , this is a service issue, since data are returned already sorted:
![Schermata 2019-03-29 alle 09 44 19](https://user-images.githubusercontent.com/7654979/55220332-54a72680-5207-11e9-98fa-ac877cfefa07.png)

**Comment by storrisi** [comment]
I've created https://github.com/clearlydefined/service/issues/465 which address this problem on the service.

**Comment by fossygirl** [comment]
Sure, closing.
