### ISSUE TITLE
Typeahead suggestions should have the logo of the type they are

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#636]
In the attached screenshot, the Nuget.Client suggestion is for NuGets and the nuget.client suggestion is for GitHub. We should include the logo aside each suggestion so people know which is which.

![Screen Shot 2019-03-28 at 3 10 31 PM (2)](https://user-images.githubusercontent.com/17101092/55196173-d21d5900-516b-11e9-8d9f-1790476c3fea.png)

**Comment by storrisi** [comment]
This change should affect only the Browse page or any place where the same search component is used?

**Comment by storrisi** [comment]
@fossygirl do you have any update on this?

**Comment by fossygirl** [comment]
Any place where the same component is used.

**Comment by storrisi** [comment]
Thanks @fossygirl , i will work on this implementation.

**Comment by storrisi** [comment]
Since this implementation requires to work on Typeahead, and since there's an update for Typeahead under review, it's better to wait for the merge of that change and then start working on this one.
