### ISSUE TITLE
Date picker switches date format on click

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#638]
When you are viewing the date picker the date format is listed as YYY-MM-DD and when you click on it it switches to MM/DD/YYY. Let's please do one or the other but not both. 

![2019-03-28 16 13 29](https://user-images.githubusercontent.com/17101092/55198761-963ac180-5174-11e9-95cb-e4b8e80b8acc.gif)

**Comment by storrisi** [comment]
Unfortunately , the HTML 5 field `date`, which is used here, shows the date based on the local timezone of the system.

In my case, i see `dd/mm/yyyy` when typing in.

We have 2 solutions then:

- use a custom `Datepicker`, like https://ant.design/components/date-picker
- show a normal `text` field with some kind of validation, and convert the input to a standard date

**Comment by dabutvin** [comment]
Can we set the placeholder text based on the current time zone?

**Comment by storrisi** [comment]
@dabutvin sure, i didn't thought about that simple solution
