### ISSUE TITLE
update version of Monaco

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#639]
Lower priority but at some point here we should look to update the `monaco-editor` and `react-monaco-editor` packages we are using. They are very old. Not sure there are substantial new features but they are likely >1 year old.

need to be careful thought. The integration was not altogether easy with some funky file copying and a helper build function etc. Perhaps in the new versions they have simplified this?

**Comment by storrisi** [comment]
@jeffmcaffer do you remember which kind of problem did you faced during the integration? I'd love to update the version since i'm on the way to made some work about loading large payloads.

**Comment by storrisi** [comment]
I've tried to update it and i'm not noticing any breaking change.
BTW we have some styling issues compared to what we have noiw that i'm going to fix.

![Schermata 2019-05-09 alle 16 59 39](https://user-images.githubusercontent.com/7654979/57463941-124c1d00-727c-11e9-8e11-007b0c176193.png)
![Schermata 2019-05-09 alle 16 59 48](https://user-images.githubusercontent.com/7654979/57463946-14ae7700-727c-11e9-810b-63303fb8bfe6.png)

**Comment by dabutvin** [comment]
while we are in here can we make sure we get collapsing/folding for the json? 
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#folding

**Comment by storrisi** [comment]
@dabutvin sure!

**Comment by jeffmcaffer** [comment]
The were just challenges in getting the deployment working. Had to copy files around at build time etc. The was some fuss around syntax highlighting and content assist. 

+1 to @dabutvin suggestion about folding. That would be a huge win.

**Comment by storrisi** [comment]
@jeffmcaffer for the reason you mentioned i would suggest to eject the application from CRA. Things like this one could be addressed by working on the Webpack configuration rather than applying workarounds.

I hope to have the chance to discuss with you further more on this topic.

**Comment by storrisi** [comment]
folding property and syntax highlighting could be enabled only by customizing the Webpack plugin configuration:
https://github.com/Microsoft/monaco-editor-webpack-plugin#options

**Comment by storrisi** [comment]
Following the issue https://github.com/Microsoft/monaco-editor/issues/82 there are different approaches proposed.

Someone injects the external Monaco Editor library instead using it as a dependency, but with that approach is not possible to customize options.

Other guys uses https://github.com/timarney/react-app-rewired , or https://github.com/harrysolovay/rescripts , that allows to override part of the Webpack configuration without ejecting, but i'm not so happy about these solutions, they would lost all the benefits of using CRA like an ejection does, and they are not standards.

**Comment by tmarble** [comment]
@storrisi I have found this [background](https://github.com/harrysolovay/rescripts#background) to be useful in understanding the issues in CRA configuration and "ejecting".

This is one of the [alternatives](https://github.com/timarney/react-app-rewired#alternatives) listed for react-app-rewired. Another one which looks promising is [craco](https://github.com/gsoft-inc/craco#craco). Both of these claim to support customizing without resorting to "eject".

So my question to you is: what are the benefits of "eject" that outweigh the solutions of **rescripts** or **craco**?

_NOTE also_ this [recent approach to using monaco-editor](https://github.com/microsoft/monaco-editor/issues/82#issuecomment-550721306).

And the second question is: would this "recent approach" (using the https://github.com/bitauth/create-react-app-bitauth-ide fork of CRA) be "better" then either of the above (eject and ??, rescripts -or- craco w/o eject)? Realize that you would be hoping that the fork would continue to track upstream CRA (which may be risky).

The answers here should guide the next attempt at upgrading.

**Comment by tmarble** [comment]
Document our discussion on Discord today I plan to investigate https://www.npmjs.com/package/@monaco-editor/react
