### ISSUE TITLE
Update UI on homepage

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#641]
See some of the updates in this picture and I'll try to break them down here

![image](https://user-images.githubusercontent.com/5168796/55255951-19adee80-5219-11e9-8caa-c2d72429be5c.png)

- Move 'Active filters' to the Bar above the definition list
- make the filter bar #0000000a
- update the hover on the definition entry to match this color
- the red X to the left of Filter/Sort will clear all filters
- each individual filter can be cleared with it's X
- Make sure sort by dropdown is transparent
- Remove the far-right 'X' from the browse page (Not pictured)
- Veritcally center the footer components (icons, Are you ClearlyDefined?, and terms links)

**Comment by storrisi** [comment]
@dabutvin in the Workspace page we have also the Multiselect behavior to show in the same position of the filters in the UI.
Also, we recently added a string that shows the number of definitions as you can see in the screenshot.

<img width="1180" alt="Image 2019-04-08 at 3 19 48 PM" src="https://user-images.githubusercontent.com/7654979/55731260-ceae8b00-5a11-11e9-9ef7-0172085daf30.png">

Perhaps we have enough space for both selection details and filters, but i think that the visualization could become a mess for the user.

Could we keep the filters summary separated from this bar like Github does?
<img width="1025" alt="Schermata 2019-04-08 alle 15 31 46" src="https://user-images.githubusercontent.com/7654979/55732202-7f695a00-5a13-11e9-9359-3c41a63ac246.png">

**Comment by dabutvin** [comment]
good point. Let's try and get the filter bar landed first and then figure out how all this fits together.
