### ISSUE TITLE
[Bug Fix/Enhancement] You lose your work if you close or refresh your Workspace

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#647]
**Type:** Bug Fix or Feature Enhancement
**Affected:** https://clearlydefined.io/workspace

I tried to see if an issue for this was already filed, but to my surprise I could not find any.

Currently, if you have multiple items in your work list, a simple refresh of the page will clear all items in that list.

In general, this is troublesome for users who are curating a large list of components. One example is if you have multiple items in the work list staged for curation, then you go into one of them and click the blue "Download component" button, the page will redirect and you will loose your work.

I think a persistent work list tied to a user's session plus the multi-select ability proposed in #617 would really improve the experience and usefulness of the work list / Workspace.

**Comment by dabutvin** [comment]
Yes! Great idea. We can keep your definition list in browser storage or something like that

**Comment by storrisi** [comment]
We already have `redux-persist` in the project, we can plan to use that for this purpose.
