### ISSUE TITLE
alphabetizing when searching

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#648]
Would it work to make alphabetizing not matter when searching for components?  For example, I get different results if I search for "Newtonsoft.Json" vs. "newtonsoft.json."

**Comment by storrisi** [comment]
@dabutvin is the service search case sensitive?

**Comment by dabutvin** [comment]
the suggestions that prompt you to autocomplete are not case sensitive.

Where are you searching when you see this?

**Comment by ariel11** [comment]
I get different packages whether I select "Newtonsoft.Json" vs "newtonsoft.json."
![image](https://user-images.githubusercontent.com/17935946/55735927-2e3b7500-59d7-11e9-8868-2a4be4db12fd.png)

**Comment by ariel11** [comment]
@dabutvin - Thanks for looking into...  Ideally, regardless of which name I select in the above example, I would see all the matches for this name (the packages and the repos), as the only difference between the two names is capitalization. If I only selected the one using upper case, I might think the repos were not in ClearlyDefined.

**Comment by dabutvin** [comment]
Ahh that KS for clearing that up.

Yep this is something that im looking at and can take care of likely this week

**Comment by storrisi** [comment]
@dabutvin is this a service related issue then?

**Comment by storrisi** [comment]
@dabutvin should we make some fixes on the service to solve this one?

**Comment by ariel11** [comment]
@storrisi - this appears to be fixed! :) It doenst appear to be case-sensitive anymore.. 
![image](https://user-images.githubusercontent.com/17935946/60315067-dfd4ad00-9919-11e9-90fa-c49a69782477.png)
