### ISSUE TITLE
It is hard for curators to find what files need curation

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/website#651]
It is very difficult for a curator to find what files need to be curated in a given file system.  For example, filtering by "NOASSERTION" in apache spark requires 6 clicks to see the first three files to curate; and 10 clicks to get to the next file.

For a given component, giving a flat list of files in need of curation would be very beneficial.

![image](https://user-images.githubusercontent.com/36014796/55756413-7a120c80-5a1f-11e9-85d7-c0704337c73a.png)

**Comment by storrisi** [comment]
@royaljust you are definitely right. 
We can maybe think to have all folders open when a filter is applied to the list.
What do you think?

**Comment by dabutvin** [comment]
opening the folders as you type might be really cool 👍

**Comment by royaljust** [comment]
Thanks!
