### ISSUE TITLE
Add links for definition files

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#655]
https://clearlydefined.io/definitions/npm/npmjs/-/cycle/1.0.3

In that definition the `files` entry for `package.json` has a `token` property which is the hash for getting the attached file. The file list entry for `package.json` should be a link that results in the identified attachment is downloaded and showed to the user. Easiest thing for now would be to do that in a simple `text/plain` view in a new browser window.

We have some related function in place for github components but that points to github.

**Comment by storrisi** [comment]
How the token should be used for non-github files to link the content?

For github files we return the url in order to reach the related content.
I guess it should be something pretty similar?

**Comment by dabutvin** [comment]
Should link to api.clearlydefined.io/attachments/<token>
