### ISSUE TITLE
use querystring on homepage browsing

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#657]
for example, browsing to https://clearlydefined.io/?license=MIT should have the license filter preselected.

Actions you take to filter or sort should be reflected in the querystring as well

**Comment by Fredrick-Tam** [comment]
This would be really helpful to allow searching through the available package versions; especially if this information could be routed to from stats page.

**Comment by dabutvin** [comment]
onFilter onSort etc can be found here: https://github.com/clearlydefined/website/blob/master/src/components/Navigation/Pages/PageBrowse/PageBrowse.js#L117
