### ISSUE TITLE
Handle the case of sorting by ReleaseDate when there is no date

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#671]
Entries without a `releaseDate` are omitted from the results when sorting by date. This happens on the Browse page but will happen anywhere that we sort by date as it is a database issue.

**Comment by storrisi** [comment]
@jeffmcaffer i believe you are talking about the browse page?

**Comment by jeffmcaffer** [comment]
@storrisi yes. sorry the original description was really crappy. I updated it to be marginally less crappy.

The base problem is that the doc db removes from the results any entries that have an empty prop on which you are sorting. @dabutvin and I have talked about a couple ways of dealing with this. Ideally they would all be handled service-side so clients would not have to even know. 

As such, this issue (in the Website repo) may be moot (assuming there is a corresponding issue in the service repo)

**Comment by storrisi** [comment]
I believe https://github.com/clearlydefined/service/pull/488 is tracking this problem on the service repo

**Comment by dabutvin** [comment]
@storrisi that one is just handling this for suggestions.

If we do something more holistic with the mongo definition store, it will make that pr obsolete

**Comment by fossygirl** [comment]
@storrisi Can you confirm if the service PR that got merged fixed this, or if there's more work needed on the website?

**Comment by storrisi** [comment]
@fossygirl unfortunately it doesn't. We should handle the case of sorting components without a Release Date.
BTW no further work is required from the website on this topic.
We can close this and keep track of the same thing on the service.
