### ISSUE TITLE
Make it so "Contribution" modal dialog only closes when you click "OK" or "Cancel".

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#675]
**Issue Type:** Feature Request
**Issue Description:** 

Currently, the _"Describe the changes in this curation"_ (a.k.a the "Contribution" dialog) can be accidentally closed by clicking anywhere outside the dialog. If a user does close the dialog, it will likely result in loss of any work spent filling in the fields required to create the curation PR.

It would be better if this dialog could only be closed by clicking the "OK" or "Cancel" buttons present. We may also want to take a look at making this the standard UX behavior for other the modal forms used in CD (i.e. SPDX expression editor, etc.) as well.

**Comment by storrisi** [comment]
@bduranc good point, i'll look forward to implement this behavior. Thanks!
