### ISSUE TITLE
update react-bootstrap-typeahead

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#677]
https://github.com/ericgio/react-bootstrap-typeahead

we are on 4.0.0-alpha.5 right now, but we should not stay here

**Comment by storrisi** [comment]
I know, but the previous version 3.4.2 contained some warnings that we were not able to remove, and actually some of the recent implementations would not be implementable.

What do you suggest?
Since there aren't yet stable releases, should we use always the latest version?

**Comment by dabutvin** [comment]
We can wait for the 4.X stable to launch, just wanted to put this here so we don't forget
