### ISSUE TITLE
The web site resets when tried to add facet glob for Docs

### ISSUE THREAD

**Issue by maxhbr** [clearlydefined/website#679]
# Problem 1
On [git/github/lz4/lz4/dfed9fa1d77f0434306d377c4da1f7191d3ba08a](https://clearlydefined.io/definitions/git/github/lz4/lz4/dfed9fa1d77f0434306d377c4da1f7191d3ba08a), if I try to add a glob expression to `docs` I get a 400 returned, with the content `data/described/facets Facets object can only contain data, dev, doc, examples, and tests`

## Screenshots:
![2019-04-25_15:44:17](https://user-images.githubusercontent.com/1187050/56740351-143cb900-6771-11e9-891a-93a0cd358ab1.png)
![2019-04-25_15:44:36](https://user-images.githubusercontent.com/1187050/56740357-1737a980-6771-11e9-9e29-05db350157f1.png)

## Details regarding the issued request by the UI:
The payload of the POST request was:
```
{"described":{"facets":{"docs":["doc"]}}}
```

# Problem 2
On [git/github/apache/thrift/327ebb6c2b6df8bf075da02ef45a2a034e9b79ba](https://clearlydefined.io/definitions/git/github/apache/thrift/327ebb6c2b6df8bf075da02ef45a2a034e9b79ba), if I try to add a glob expression to `docs` the JS fails with
```
Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'reduxPersist:ui' exceeded the quota.
```
and also the 400 from Problem 1

## Screenshot:
![2019-04-25_15:45:48](https://user-images.githubusercontent.com/1187050/56740448-41896700-6771-11e9-98d8-dc268a27a1f3.png)

**Comment by maxhbr** [comment]
related: https://github.com/clearlydefined/curated-data/pull/1258

**Comment by maxhbr** [comment]
The **problem 1** might just be, that the key for in the JSON has to be `"doc"` instead of `"docs"`

**Comment by dabutvin** [comment]
thanks for tracking this down!

We are really close to getting this fixed in #629 
https://github.com/clearlydefined/website/pull/629/files#diff-2433278eb16164dc386e0cced06c8a2aR261

**Comment by bduranc** [comment]
@dabutvin 

I also observe similar behavior with the entire page becoming white when I click "Curations".

https://clearlydefined.io/definitions/npm/npmjs/-/async-mutex/0.1.3

The trace from my Chrome browser appears to be throwing a TypeError.

react-dom.production.min.js:3744 TypeError: Cannot read property 'isFetching' of undefined
react-dom.production.min.js:4817 Uncaught TypeError: Cannot read property 'isFetching' of undefined

I had opened a similar ticket for this #485 .

**Comment by dabutvin** [comment]
ahhh, that's a bug

Let's get a new ticket open #682
