### ISSUE TITLE
Harvest tab crashes with out of memory for large payloads

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#683]
example: https://clearlydefined.io/definitions/maven/mavencentral/com.amazonaws/aws-java-sdk-bundle/1.11.163

The monaco editor can't handle it, it's over 7MB of data

**Comment by storrisi** [comment]
This is a tricky problem. Don't know if we can handle upgrading the Monaco Editor, but i suspect no.

Any ideas?

**Comment by dabutvin** [comment]
take a look at https://github.com/Microsoft/vscode/blob/d6c200ea57fc3104af1c237dfd16ff0d83c3ad2a/src/vs/editor/common/model/textModel.ts#L48

they are doing stuff with buffers

**Comment by storrisi** [comment]
We need to upgrade Monaco-Editor to work on this. I'm looking further while working on #639

**Comment by storrisi** [comment]
This is fun because actually, while checking that link, the Harvest tab doesn't crash at all.

**Comment by storrisi** [comment]
I see a different problem here instead: since the definition is pretty large, it takes a while to receive the details from the backend, maybe we should consider to add a loader to the FullDetailPage?

**Comment by storrisi** [comment]
Attached a GIF related to the main problem rise by this issue:

![Screen Recording 2019-05-17 at 06 16 PM](https://user-images.githubusercontent.com/7654979/57941731-ff66c780-78cf-11e9-92f5-25bc5e863d3c.gif)

**Comment by dabutvin** [comment]
Seems to be working for me now too. closing
