### ISSUE TITLE
Website crashes on opening the curations tab for eclipse/birt

### ISSUE THREAD

**Issue by maxhbr** [clearlydefined/website#688]
On the component [eclipse/birt/f4668e5d39c486406eca158527b4d7ff511d6a1e](https://clearlydefined.io/definitions/git/github/eclipse/birt/f4668e5d39c486406eca158527b4d7ff511d6a1e) the website crashes in Firefox and Chromium on clicking of the tab `curations`. The whole page becomes white.

There is no asynchronous request issued directly before the error.

The tabs `Current definition` and `Harvested data` work as expected.

## Screenshots:
![2019-04-29_15:40:27](https://user-images.githubusercontent.com/1187050/56900028-2bdbb080-6a95-11e9-9676-0cf7149c2e74.png)

# Off-topic, but maybe related:
Is there a way to curate the sources? The UI lists for `eclipse/birt` only one file which is `LICENSE`.
Why is there a mismatch to the corresponding github sources / the downloadable sources?

![2019-04-29_15:43:45](https://user-images.githubusercontent.com/1187050/56900255-ac021600-6a95-11e9-9ce1-8be8b9420964.png)

**Comment by storrisi** [comment]
@maxhbr the problem about the tab has been fixed recently in https://github.com/clearlydefined/website/pull/686 , probably it only need to be pushed on prod.

**Comment by maxhbr** [comment]
@storrisi : thank you for the information. Should I create an issue for my question with the broken/incomplete sources, or is this also caused by the same bug?

**Comment by storrisi** [comment]
Since those are separate problems, i think that having different issues it's definitely better

**Comment by maxhbr** [comment]
follow up issue for the off-topic stuff is: https://github.com/clearlydefined/website/issues/689
