### ISSUE TITLE
Include other versions of the same component in full details page

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#691]
In the full details view of a component we should include easy links to the other versions of the same component in the same package manager.

**Comment by storrisi** [comment]
@fossygirl should the user be able to change the current version while navigating, or perhaps he should be able to see a complete list of versions, and then click on of them to open it on another tab of the browser?

This question is important to understand how to render the behavior to the user.
In the first case we can add a simple dropdown, maybe near to the version in the title section.
In the second one we should add a newly section to the FullDetailPage, i suggest just below the header section, before the Described details. This section will contain all the versions rendered as a scrollable list.

**Comment by storrisi** [comment]
@fossygirl do you have any feedback?

**Comment by storrisi** [comment]
Here's a quick mockup of the change, just to make some thoughts about it:
![Screen Recording 2019-05-22 at 11 04 AM](https://user-images.githubusercontent.com/7654979/58162186-f6844600-7c81-11e9-8a2e-2db863c25dab.gif)

Some notes:
- Selecting a new version will open a new tab to the definition
- The ![Schermata 2019-05-22 alle 10 37 24](https://user-images.githubusercontent.com/7654979/58162219-1156ba80-7c82-11e9-9732-467dcd914180.png) button will link to the source of the selected version

Just a few questions:
- what should happen to the definitions list? If the user selects a different version from the full detail page, will the version be added to the list? 
- if yes, it will be an addition or a change? (the old version will be substituted)

**Comment by fossygirl** [comment]
@iamwillbar Your thoughts here?

**Comment by storrisi** [comment]
@fossygirl @iamwillbar  i'll be very happy to work and bring this in place. Do you have any feedback for my questions above?

**Comment by iamwillbar** [comment]
I think having an action occur when you select something from a dropdown isn't great for usability/accessibility. What if we had a button that links you to search results for that particular component?

**Comment by storrisi** [comment]
@iamwillbar do you suggest a modal like the one you have in the definition list when you are trying to change the version of an existing component, or maybe a direct link to the browse page, like [this one](https://clearlydefined.io/?type=npm&sort=releaseDate&sortDesc=true&name=async) ?

**Comment by iamwillbar** [comment]
I was thinking a direct link to the browse page.

**Comment by storrisi** [comment]
@iamwillbar , the example above is a search with the same provider and package name. It could be very simple to add this in the detail page.

**Comment by storrisi** [comment]
While start working on this, i felt to have too much buttons near the component title.
We recently added both Copy Url and Curate Source button.
So maybe group them in a dropdown could save some space.

@iamwillbar @fossygirl thoughts?

![Screen Recording 2019-06-12 at 04 23 PM](https://user-images.githubusercontent.com/7654979/59359312-67bd9300-8d2e-11e9-8e32-1e4babd7c143.gif)

**Comment by fossygirl** [comment]
@storrisi I think that's a good addition. @iamwillbar thoughts?

**Comment by iamwillbar** [comment]
Looks good to me.

**Comment by storrisi** [comment]
Thanks, i will proceed on this direction then.
