### ISSUE TITLE
Add ability to link to a list of versions of a component (or the latest)

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/website#702]
Sometimes we want to link people to information about a component rather than a specific version.

It would be good to be able to link to a list of harvested versions for a component or the latest known version of a component.

**Comment by storrisi** [comment]
@iamwillbar do you mean something like this? https://clearlydefined.io/?sort=releaseDate&sortDesc=true&name=electron

**Comment by storrisi** [comment]
@iamwillbar is the link above covering your request?

**Comment by storrisi** [comment]
@iamwillbar do you have any update on this?

**Comment by iamwillbar** [comment]
That's exactly what I need, thanks!
