### ISSUE TITLE
Do not add continuationToken to the address bar on home page

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#710]
when scrolling through the list we should keep this parameter out of the address bar

![image](https://user-images.githubusercontent.com/5168796/57657949-df629b80-7591-11e9-96f3-351a9dbe636f.png)

We would not want to persist this value at any time

**Comment by storrisi** [comment]
This seems to be the same error mentioned in #689 

We are going to investigate on this problem on the service side.

Thanks.
