### ISSUE TITLE
Add button to visit package manager on definition page

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/website#733]
It's not very discoverable that clicking the title of the package on the definition page will take you to the package manager page for that component. Can we add a button next to the title next to the new copy URL button that takes you to the same location as clicking the title?

**Comment by storrisi** [comment]
As mentioned in #691 we are starting to have too many buttons in that position.
In #691 and here we are discussing about adding 2 more buttons, so we'll have a total amount of 4 actions near the title.
I would strongly suggest to consider a dropdown menu.
