### ISSUE TITLE
Problems with definition multiselect

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#734]
Referencing: #169 

Issue Type: Bug
Issue Description:

I tried to edit the one of the definitions in my Worklist. Once satisfied with my improvements, I selected the definition (checkbox) in the Workspace, and clicked the green "Contribute" button.

When the Contribution dialog box came up, I entered in my commit notes and tried to submit the form. Unfortunately, as soon as the dialog closed, I got a nondescript error in the corner of my screen which said "Failed contribution".

<img width="293" alt="2019-06-04_15-22-43" src="https://user-images.githubusercontent.com/31491646/58917812-b3dc5800-86dc-11e9-8672-64eb386e4311.png">

Furthermore, the little blue "halo" that shows behind definitions that have changes staged (along with my proposed contributions within that definition) disappeared, despite the the curation request failing to create.

**Comment by storrisi** [comment]
I'm not able to reproduce it in dev environment. I've done the same process that you described but it ended with a successful contribution.

Are you able to reproduce it on dev and give me further details (like the contributed definition)?

Thanks!

**Comment by bduranc** [comment]
@storrisi : For some reason I am unable to recreate it in dev either. Tried three times.

The components I experienced this issue are as follows:

git/github/stuk/jszip@265c959b1f15f8cd5ebe152154b88796e4a82f42
(https://clearlydefined.io/definitions/git/github/stuk/jszip/265c959b1f15f8cd5ebe152154b88796e4a82f42)

npm/npmjs/jszip@3.2.0
(https://clearlydefined.io/definitions/npm/npmjs/-/jszip/3.2.0)

If I encounter it again, I will try to provide more info. 

One other thing I notice in dev though is that if I have multiple definitions staged for curation, but leave one unselected, it still stays visible in the "involved components" list that comes up when I click Contribute. I don't know if this is intentional or not.

<img width="633" alt="2019-06-06_11-33-18" src="https://user-images.githubusercontent.com/31491646/59057938-5f59e980-8850-11e9-937e-c5a84ff4aef5.png">

**Comment by bduranc** [comment]
Caught another instance of this bug again, but this time got some screenshots.

I encountered it again with the two below definitions in my work list:

1. https://clearlydefined.io/definitions/git/github/tommyjones/textminer/7ced28c7df42b53599c2467a31d682b6ab146755

2. https://clearlydefined.io/definitions/git/github/tommyjones/textminer/1ec38621a2ee9193f6627973a04b70cf512c2daa

I curated the top-level license on the second definition (_1ec386_) and attempted to click Contribute with only that definition checked.

However, my first attempt failed and the following messages were displayed as a result:

<img width="421" alt="2019-06-07_13-59-11" src="https://user-images.githubusercontent.com/31491646/59135566-4aef1d00-8934-11e9-90e5-a712e6f40aae.png">

The work list after this looked like below:

<img width="793" alt="2019-06-07_13-59-24" src="https://user-images.githubusercontent.com/31491646/59135468-d7e5a680-8933-11e9-9adb-b70ef5a09821.png">

After the error occurred, I went to remove the first definition (_7ced28_) from the list, leaving just _1ec386_ because it seems that you can get around this bug if you have only one definition in the work list.

But for some reason the tool still thinks that there are two items in the list!

<img width="925" alt="2019-06-07_14-01-53" src="https://user-images.githubusercontent.com/31491646/59136045-36138900-8936-11e9-9cbb-f1feb328ec10.png">

It submitted ok this time.

**Comment by bduranc** [comment]
Referencing #739

**Comment by storrisi** [comment]
Thanks @bduranc , i'm going through all of the problems faced here.
