### ISSUE TITLE
"Failed contribution"

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#739]
I updated the "Declared" license for https://clearlydefined.io/definitions/npm/npmjs/webcomponents/url/0.7.3 to SAX-PD, selected "Contribute," completed the form and clicked OK.  I then received a "Failed contribution" message.

**Comment by fossygirl** [comment]
@storrisi Can you please look into this?

**Comment by storrisi** [comment]
Probably it's throwing an error because the component is not yet harvested?

This is what the service says in this case : `message: "The contribution has failed because some of the supplied component definitions do not exist"`

**Comment by fossygirl** [comment]
How can we be doing curations for components that aren't harvested? Users shouldn't be able to make a curation on a component that doesn't exist.

**Comment by storrisi** [comment]
@fossygirl good point. Probably we should disable any Contribution activities for these kind of components?

**Comment by fossygirl** [comment]
Yes, please.
