### ISSUE TITLE
Declared license not showing in Workspace

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#740]
If I find this package - nuget/nuget/-/System.Management.Automation/6.1.7601.17515 - in the Workspace, the Declared license field is blank.  However, if you dig into the definition, it says it is curated and shows MIT.  I assume this information is meant to show up in the Workspace view..

**Comment by fossygirl** [comment]
@storrisi Can you please take a look at this?

**Comment by storrisi** [comment]
I've tried to search the same component but everything looks fine:

![Screen Recording 2019-06-07 at 09 49 AM](https://user-images.githubusercontent.com/7654979/59089158-b96ab580-8909-11e9-8173-3f50186fb379.gif)

**Comment by fossygirl** [comment]
@ariel11 Can you please send us a screenshot of the behavior you're seeing?

**Comment by ariel11** [comment]
![image](https://user-images.githubusercontent.com/17935946/59630739-f2214080-90fa-11e9-9422-40677ab85f3f.png)

**Comment by ariel11** [comment]
@fossygirl and @storrisi - sure, above is the screenshot of the component in the Workspace where it looks like no license has been declared (but if you click the magnifying glass, you see MIT).

**Comment by storrisi** [comment]
@ariel11 i've made the same test on a clean browser session without any cache, works fine for me now:

![Screen Recording 2019-06-18 at 10 29 AM](https://user-images.githubusercontent.com/7654979/59665893-11c86f80-91b4-11e9-8421-a46c14a53b0a.gif)

**Comment by storrisi** [comment]
@ariel11 are you still able to reproduce this problem?

**Comment by ariel11** [comment]
@storrisi - I don't know why our views are different, but yes - it still isn't showing the Declared license in this view for me for this one NuGet.  I do see above how it looks right on your machine.
![image](https://user-images.githubusercontent.com/17935946/60313845-72bf1880-9915-11e9-845e-4e12fdd8f564.png)

**Comment by ariel11** [comment]
@storrisi - In my view, I see a red 15 and in your review a red 30?  It appears we are somehow getting different info??

**Comment by storrisi** [comment]
Yes, it looks like.
Do you still see the same info?
I've checked right now and I'm still seeing a 30 score.
