### ISSUE TITLE
Submitting a contribution shows "Failed Contribution" for a few components without any explanation

### ISSUE THREAD

**Issue by joseharriaga** [clearlydefined/website#748]
This happened for the following four components. I'm also including the information I attempted to contribute.

•	**nuget/nuget/-/PInvoke.BCrypt/0.5.184**
https://www.nuget.org/packages/PInvoke.BCrypt/0.5.184
Source:
https://github.com/AArnott/pinvoke/tree/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3
MIT License:
Copyright (c) 2018 All contributors
https://github.com/AArnott/pinvoke/blob/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3/LICENSE
 
•	**nuget/nuget/-/PInvoke.Kernel32/0.5.184**
https://www.nuget.org/packages/PInvoke.Kernel32/0.5.184
Source:
https://github.com/AArnott/pinvoke/tree/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3
MIT License:
Copyright (c) 2018 All contributors
https://github.com/AArnott/pinvoke/blob/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3/LICENSE
 
•	**nuget/nuget/-/PInvoke.NCrypt/0.5.184**
https://www.nuget.org/packages/PInvoke.NCrypt/0.5.184
Source:
https://github.com/AArnott/pinvoke/tree/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3
MIT License:
Copyright (c) 2018 All contributors
https://github.com/AArnott/pinvoke/blob/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3/LICENSE
 
•	**nuget/nuget/-/PInvoke.Windows.Core/0.5.184**
https://www.nuget.org/packages/PInvoke.Windows.Core/0.5.184
Source:
https://github.com/AArnott/pinvoke/tree/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3
MIT License:
Copyright (c) 2018 All contributors
https://github.com/AArnott/pinvoke/blob/cf0176c42bc63ddb8622f60c9fbd7176e7757bd3/LICENSE

**Comment by geneh** [comment]
This issue has been resolved.
