### ISSUE TITLE
Dropdown on definition page gets cut off with longer package names

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/website#752]
The dropdown at the top next to the package name gets truncated if the package has a longer name:
![image](https://user-images.githubusercontent.com/3266447/59525125-630df180-8e8a-11e9-936e-f42291e02f79.png)

**Comment by geneh** [comment]
It is still happening for components with longer names and Pending curations label, for example https://clearlydefined.io/definitions/nuget/nuget/-/StackExchange.Redis.StrongName/1.2.6/1.2.6
![Screen Shot 2019-06-18 at 1 49 58 PM](https://user-images.githubusercontent.com/1537662/59718908-fff4c580-91cf-11e9-8dc8-4b0fb34f5d7a.png)
