### ISSUE TITLE
Dead link to files

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#764]
In https://clearlydefined.io/definitions/nuget/nuget/-/Moq/4.10.1/4.10.1 the Files listed have a link that goes 404. 
For instance Moq.nuspec has a link to https://clearlydefined.io/file/5348e9361ed572304b1c84561461f9adb1151443d1b7d9d283f80a2a480ed0a8 

It would be best to avoid providing such a link (in this case the link may never be possible since there is direct way to get to the file: you need to download the whole archive first)

**Comment by storrisi** [comment]
Actually this is an expected behavior. See https://github.com/clearlydefined/website/pull/659#discussion_r276390974

**Comment by storrisi** [comment]
@fossygirl @geneh @iamwillbar should we change the current behavior like @pombredanne suggested?
