### ISSUE TITLE
Accessing specific component definition is really slow

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#766]
The following component takes around 2 min to load for me, clean-slate.

https://clearlydefined.io/definitions/git/github/johanvos/openjdk-mobile11/19fb8f93c59dfd791f62d41f332db9e306bc1422

It loads in Firefox 67.0.1 (64-bit) but with extreme performance issues and very high resource utilization.

It intermittently loads in Chrome 74.0.3729.169 (64-Bit), almost always first resulting in a white blank screen.

I confirmed this behavior with another colleague who also encounters the same observation in their Safari and Chrome browsers.

**Comment by geneh** [comment]
This component is huge. clearlydefined JSON blob is 13.9 MB, so that' expected.

**Comment by bduranc** [comment]
Ah makes sense. Thank you. I think this is the first time I've encountered such a case.

So I suppose we just let this component run it's course then. I will close the ticket if there is no further investigation required.

**Comment by storrisi** [comment]
@bduranc i think we can close this one.

**Comment by bduranc** [comment]
@storrisi 

Agreed
