### ISSUE TITLE
Copyrights not highlighted on curations page

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#773]
The copyrights curated as shown here - https://github.com/clearlydefined/curated-data/pull/1858/files - are not highlighted on the curations page (just the license changes) - https://clearlydefined.io/curations/1858.

**Comment by ariel11** [comment]
Here is a screenshot showing how the license change is highlighted but not the copyright - 
![image](https://user-images.githubusercontent.com/17935946/60313644-c4b36e80-9914-11e9-9647-0c407c27c969.png)

**Comment by storrisi** [comment]
I'm unable to reproduce it, the call to https://api.clearlydefined.io/curations/pr/1858 returns an empty `changes` value

**Comment by storrisi** [comment]
Finally i was able to reproduce it and to find a solution. Thanks @ariel11 for the catch!
