### ISSUE TITLE
Show a bar graph on /status page for tools

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#774]
Would be nice to add a bar graph on clearlydefined.io/stats that shows the number of tools that have been run each day. 

@iamwillbar

**Comment by storrisi** [comment]
Do we have already a service endpoint that returns all the data?

**Comment by ignacionr** [comment]
We don't at the moment; we could add that to either https://api.clearlydefined.io/stats or https://api.clearlydefined.io/status (the latter currently holding more similar info).

**Comment by storrisi** [comment]
I think the second is the most appropriated one, since in the https://clearlydefined.io/status page we are already showing similar data.

@fossygirl do you agree?

**Comment by fossygirl** [comment]
Yes, agreed.

**Comment by jeffmcaffer** [comment]
I updated the title accordingly
