### ISSUE TITLE
Copied text is truncated in RAW data

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#799]
There is a bug there on Firefox... you cannot copy text from the raw data there correctly (it gets truncated with ... ellipsis as soon as it is more than a few lines)

This is the version of the text editor used in ClearlyDefined: https://clearlydefined.io/vs/editor/editor.main.js

```
/*!-----------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Version: 0.10.1(ebbf400719be21761361804bf63fb3916e64a845)
 * Released under the MIT license
 * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
 *-----------------------------------------------------------*/
```

this is rather old since the latest is 0.17.1 

I also filed a bug upstream.

**Comment by pombredanne** [comment]
See https://github.com/microsoft/monaco-editor/issues/1540

**Comment by storrisi** [comment]
@pombredanne should we do something in the UI or just wait for a fix?

**Comment by storrisi** [comment]
@pombredanne did you received any updates? I've checked the issue you opened but I don't see any answer

**Comment by jeffmendoza** [comment]
Let's just track here, and not make any changes to ClearlyDefined's website.

**Comment by storrisi** [comment]
@jeffmendoza agreed. Thanks!

**Comment by pombredanne** [comment]
@jeffmendoza @storrisi this is tracked in this https://github.com/microsoft/monaco-editor/issues/1540 whcih unfortunately received little or no love for now. Let me see if I can tag a dev based on a blame.

**Comment by pombredanne** [comment]
This happens to be a local setting in my FF after all. The Monaco editor requires some extensive read/write clipboard access to be enabled in the web browse which is a potential security risk tat is disabled in my setup, hence the issue
