### ISSUE TITLE
ClearlyDefined branding: initial logo and typography

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#8]
At a minimum for go live, we need a logo for ClearlyDefined and initial typography for the title. We have a group we've contacted who are interested and available to do at least those things before our initial launch.

**Comment by fossygirl** [comment]
The branding, logos, and typography that we've got so far has been uploaded to Google Drive: https://drive.google.com/drive/u/0/folders/1Jd5ePl2D0WzshKTbYUpPkqvr_YWLk345

The designers will also be adding to GitHub soon.

**Comment by fossygirl** [comment]
Branding is here: https://github.com/clearlydefined/clearlydefined/tree/master/branding

**Comment by jeffmcaffer** [comment]
initial logo placement and font setup done. Need revisit all the pages for general layout once the real text is there

Also need to look at the footer. content, colors, ...
