### ISSUE TITLE
Loading components from long URL fails

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#810]
Why doesn't this URL create a list of components in ClearlyDefined?

https://clearlydefined.io/share/eJyd0sFOhDAQBuB3mTOZwOKq4cauRo0xMZK4B+OhwLA7sbSkLayE8O4WDyasJzi2f+Zr/rYDVCwdGUiGMQCrjdv1kIASNUEAhdamZCUcWUg+BnB9Q1PaHsn5uDG643Ia/tv6HUwgPWTZ3TPutZkYQx1b1soHMca4iTGCMVjA7W33SLLx0Qy7xgjDZdKDaQpMW3eaSxHerJL+F5ykhe1euDDa6sp5rqRUCdlbtrhjlX1xfclf4XYtf//tSE2Q9Sepio+tEc4v8Unx/JgNhutbvOozmexEUuIW36giQ6qg1Fqqc8n+K100WvyI7/rcCHkQec5ujt366wkxhvFz/AERoe7m

**Comment by storrisi** [comment]
@fossygirl are you able to share here the same list using one of the other methods, in order to check what happens when the URL is being generated? Thanks!
