### ISSUE TITLE
details page component name/version layout

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#812]
The layout of the "title" of the details page is quite jumbled. 

![Screen Shot 2019-08-26 at 3 08 59 PM](https://user-images.githubusercontent.com/10070956/63726922-856da500-c813-11e9-96f6-9230e581bbef.png)

Suggestions:

* The type, name and version of the component should be quite prominent. 
* the score and harvested tags should be secondary
* Would be great to have the type logo should also be shown. As is, looking at this page is very challenging to tell what kind of component it is
* The blue `...` box is unprecedented both in this UI and more generally. Each of the entries has an icon, perhaps these should just be buttons beside OK Cancel?
* The version number is indented under the component name. should be left aligned.

**Comment by storrisi** [comment]
@jeffmcaffer thanks for your suggestions.

The only point that is not completely clear for me is:

> The blue ... box is unprecedented both in this UI and more generally. Each of the entries has an icon, perhaps these should just be buttons beside OK Cancel?

Are you suggesting to convert the entries in the ... list to buttons?

**Comment by geneh** [comment]
@storrisi Let's ignore the unclear point for now. Given the relatively recent UI changes, is there anything to be done here?

**Comment by storrisi** [comment]
@geneh anything else here has already been addressed

**Comment by geneh** [comment]
Great, thanks! Let's close this one for now. @jeffmcaffer can reopen if needed.
