### ISSUE TITLE
Broken UI for non-existent definitions

### ISSUE THREAD

**Issue by geneh** [clearlydefined/website#816]
The following definitions does not exist in ClearlyDefined:
https://clearlydefined.io/definitions/maven/mavencentral/-/androidx.lifecycle/lifecycle-viewmodel-ktx/2.1.0-rc01
The page is attempted to be loaded with loading animation but then it becomes blank.
```
TypeError: Cannot read property 'length' of undefined
    at t.n.getTooltip (HarvestIndicator.js:17)
```

**Comment by storrisi** [comment]
This has already been fixed in https://github.com/clearlydefined/website/pull/809/commits/fab90b94c061a2864c839e689dcacc5ed6f0609f
