### ISSUE TITLE
Debian numbers are off on the stats page

### ISSUE THREAD

**Issue by geneh** [clearlydefined/website#836]
https://clearlydefined.io/stats
Debian total count is 0 which is incorrect.
The search type is currently **debian** which is incorrect. It should be **deb** for Debian packages and **debsrc** for Debian sources.
Please correct and also add stats for Debian sources.

**Comment by storrisi** [comment]
Everything looks fine now, maybe it was a temporary problem?

**Comment by geneh** [comment]
@storrisi Could you please fix this one?

**Comment by storrisi** [comment]
Yes, I'm currently working at it
