### ISSUE TITLE
Some definitions show up as curated even though they are not

### ISSUE THREAD

**Issue by geneh** [clearlydefined/website#848]
The following definitions show up as curated with undeclared license even though these specific versions aren't curated. Is there a problem with Curated badge?
https://clearlydefined.io/definitions/nuget/nuget/-/System.Net.Http.WinHttpHandler/4.5.0
https://clearlydefined.io/definitions/nuget/nuget/-/Bond.Runtime.CSharp/8.0.0

https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/System.Net.Http.WinHttpHandler.yaml
https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/Bond.Runtime.CSharp.yaml

![Screen Shot 2019-11-11 at 9 45 19 AM](https://user-images.githubusercontent.com/1537662/68608534-0843ea80-0468-11ea-9651-bcfaae8b8643.png)

![Screen Shot 2019-11-11 at 9 45 33 AM](https://user-images.githubusercontent.com/1537662/68608559-12fe7f80-0468-11ea-90f9-cacec4d9e5ed.png)

**Comment by storrisi** [comment]
The Curated badge is shown if the definition has at least one merged contribution.
In these cases, I see multiple merged contributions so it looks to be fine from my point of view.
Maybe the condition should check for something else?

**Comment by geneh** [comment]
At this point a specific version must be matched for a curation to be applied. In the future this logic may change if and when it is decided to use apply curations from other versions.
It should be checked whether the version matches in the curations list. For example see curations array in
https://api.clearlydefined.io/curations/nuget/nuget/-/System.Net.Http.WinHttpHandler/4.5.0?expand=prs

**Comment by storrisi** [comment]
I'm wondering why that endpoint is returning contributions from other versions since the needed version has been specified in the request.

Thoughts?

**Comment by storrisi** [comment]
I made some tests over the API results:

If I call https://api.clearlydefined.io/curations/nuget/nuget/-/System.Net.Http.WinHttpHandler/?expand=prs (just removing the version from the request) I get the same results that I get by specifying the version.

If I call https://api.clearlydefined.io/curations/nuget/nuget/-/System.Net.Http.WinHttpHandler I get the same results, again.

But if I call https://api.clearlydefined.io/curations/nuget/nuget/-/System.Net.Http.WinHttpHandler/4.5.0 without `expand=prs`, then the API returns a `Not Found` message.

I'm not sure about why this is happening, since in the curations array actually is present a curation over the 4.5.0 version, which ends to be considered a curated component.

**Comment by geneh** [comment]
4.5.0 version is present for other components, not this one. Does it make sense?
![Screen Shot 2019-11-12 at 9 24 37 AM](https://user-images.githubusercontent.com/1537662/68694578-460b4680-052e-11ea-81d3-bdc8f00fc361.png)

**Comment by storrisi** [comment]
Sorry, I missed it.
I still don't get why the endpoint  https://api.clearlydefined.io/curations/nuget/nuget/-/System.Net.Http.WinHttpHandler/4.5.0?expand=prs returns a list of all the curations from different versions if a specific version has been requested.

**Comment by geneh** [comment]
Any clues from the code? @ignacionr Do you know if that's expected?

**Comment by storrisi** [comment]
@geneh I think that the best option, for now, is to add a revision param into the contributions objects, in order to allow the client to filter the values.

**Comment by storrisi** [comment]
I've tried to come up with a solution to the client, but I think that the best solution is to filter the results with contents that are related to the requested version. 

Otherwise, the second option is to search into all the Prs retrieved, and match the same coordinates / revision.

Thoughts?
