### ISSUE TITLE
move to fontawesome 5 to get Discord

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#86]
Fontawesome 5 has a Discord icon we need for the footer.

Moving likely means moving off the current react-fontawesome component as they only work with 4.* it seems.

OTOH, https://www.npmjs.com/package/@fortawesome/react-fontawesome works with FA5 but uses a different code pattern. sigh.

Good news is though that FA5 has a mess of interesting JS transforms etc that this other component enables.  So we can do some fun things if we move.

If we add this, the discord icon will automatically show up in the footer as the entry has already been made.

**Comment by jpeddicord** [comment]
Happy to pick this one up. We don't necessarily need a React-enabled FA package here, unless I'm really misunderstanding how FA5 works.

**Comment by jeffmcaffer** [comment]
Sounds good. we don't need a React enabled component at all. that often makes things simpler but we only use very few icons so whatever works and is reasonably clean.
