### ISSUE TITLE
Add link to curation guidelines on https://clearlydefined.io/

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#873]
Right now, from https://clearlydefined.io/, I am not easily seeing how someone would find the curation guidelines (https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md). 

Recommend adding a link directly on https://clearlydefined.io/.  If folks did not want to do that, then adding the guidelines more clearly to https://docs.clearlydefined.io/ (and mention it here: https://docs.clearlydefined.io/data-curation).

**Comment by nellshamrell** [comment]
We discussed this in this week's community meeting and this is definitely something we should do!

Here are the notes from the discussion:
* Where to put it?
* Have it part of the curation page
* Would there be a link to the curation guide?
* Need to surface curation guide more

**Comment by nellshamrell** [comment]
Done!
![clearlydefined_curation_guidelines_1](https://user-images.githubusercontent.com/813007/106818089-ab17f400-662c-11eb-9bc6-4dbc35ce089b.png)
![clearlydefined_curation_guidelines_2](https://user-images.githubusercontent.com/813007/106818098-ace1b780-662c-11eb-98be-42859febebd5.png)
