### ISSUE TITLE
Curation raw data not showing up in component details

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#875]
Consider https://clearlydefined.io/definitions/maven/mavencentral/org.glassfish.jersey.core/jersey-client/2.25.1

It is curated (there is an entry in the Curations list and it has the Curated tag) but clicking on the **Curations** tab in the **Raw data** section at the bottom shows empty data.

**Comment by nellshamrell** [comment]
Opening up a notes comment here that I will update throughout my investigation.

Using my local environment, I harvested this component, then opened up a curation pull request in [curated-data-dev](https://github.com/clearlydefined/curated-data-dev/pull/1067)

However, it's still now showing up in my local UI when I look at the component's page.

**Comment by nellshamrell** [comment]
@jeffmcaffer what kind of information do you expect to be in the "Curations" tab under raw data?
