### ISSUE TITLE
Need WITH in the curation UI

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#878]
Cannot curate WITH expressions  - e.g. "Apache-2.0 WITH LLVM-exception" (or any of the other WITH exceptions - https://spdx.org/licenses/exceptions-index.html). 

**Note: License Exceptions**
The SPDX License List includes a list of exceptions. These exceptions grant an exception to a license condition or additional permissions beyond those granted in a license; they are not stand-alone licenses. Exceptions are added to a license using the License Expression operator, "WITH".

**Comment by ariel11** [comment]
Note: https://github.com/clearlydefined/service/issues/694

**Comment by nellshamrell** [comment]
Closing since this has an open issue on the service
