### ISSUE TITLE
Query or get a list of definitions feeding into "Declared License Breakdown" tables

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#894]
At the bottom of [the "Stats" page](https://clearlydefined.io/stats), there are various "Declared License Breakdown" tables.  It would be really useful if I could click on the percentage categories and see all the definitions related to that.

For example - taking NPM's - if I could click on the 4.85% that are NOASSERTION, and see all the relevant definitions that feed into that stat.  That way, someone could start curating those if they wanted.  Or, maybe someone wants to see which packages are in the .87% that are "GPL-3.0" (also, that is not a valid SPDX, so if I could, it would be awesome to be able to click into that and see why those specific packages have a declared "GPL-3.0" license vs. the valid SPDX options of "GPL-3.0-only" or "GPL-3.0-or-later."

![image](https://user-images.githubusercontent.com/17935946/107286129-03783880-6a15-11eb-83ac-a78f084988c5.png)

Thank you

**Comment by capfei** [comment]
Closing since the license breakdown is no longer on the stats page.
