### ISSUE TITLE
Can't seem to harvest some Maven components using the harvest page

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#923]
Greetings,

I am experiencing issues harvesting the following Maven components using the https://clearlydefined.io/harvest page:

- [org.apache.logging.log4j:log4j-api:2.17.1](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/)
- [org.apache.logging.log4j:log4j-core:2.17.1](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.17.1/)

Both appear to exist in Maven Central and the groupId/artifact names are correct to the best of my knowledge.

Neither show up in the list of recommendations when I search for them in the UI:

![image](https://user-images.githubusercontent.com/31491646/148823646-b94e1234-7cce-4d98-8161-0593bbf9367f.png)

I cannot even get to the point of entering in the version number.

Another colleague also reported seeing an HTTP 500 error when recreating my above efforts:

```
Request URL: https://api.clearlydefined.io/origins/maven/org.apache.logging.log4j/log4j-api
Request Method: GET
Status Code: 500
```

Same result reported in _dev_ environment too.

**Comment by nellshamrell** [comment]
Interesting, sounds like an issue with our connection to Maven Central.

I was able to queue up a harvest though the API, which is a workaround for now, but is certainly less the ideal.

```
curl -X POST "https://api.clearlydefined.io/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[{\"tool\":\"package\",\"coordinates\":\"maven/mavencentral/org.apache.logging.log4j/log4j-api/2.17.1\"}]"
```

Will look into this after the new UI is deployed soon.

**Comment by nellshamrell** [comment]
This has been fixed with the pull requests from the incredibly helpful @qtomlinson :)
