### ISSUE TITLE
Issues in new UI

### ISSUE THREAD

**Issue by nellshamrell** [clearlydefined/website#931]
This issue is intended to gather any bugs or other issues people spot in the new UI, now deployed to dev.clearlydefined.io. Please mention them as comments on this issue :)

**Comment by capfei** [comment]
The dropdown arrow does not work for selecting the package type, but works correctly for "Fix Something".

**Comment by capfei** [comment]
In the window to edit the license, the clicking "x" does not close the window. It doesn't do anything.
<img width="377" alt="image" src="https://user-images.githubusercontent.com/5489711/152377077-424156b9-6123-4316-a976-b6114817e9ae.png">

**Comment by capfei** [comment]
When I try to edit the source information, clicking the edit pencil only shows me a white screen. 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/5489711/152377334-21843af4-38fa-49fd-b3b8-fcffde595cd9.png">

White page after clicking:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/5489711/152377617-800785bf-deab-4b81-b1d6-a06bc8966442.png">

**Comment by capfei** [comment]
In the current UI, clicking on the version or commit ID, would usually take me to the component/version. If it is a GitHub repo, it would go to github at that commit. Same for pypi, it would go to that package and version on pypi.org.

However, in this UI, it just goes back to the page.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/5489711/152379372-8b8a5895-17ba-4904-a28e-4ae27e17eda2.png">

Will this change once in production?

**Comment by nellshamrell** [comment]
Hi @capfei - are you referring to clicking on the version or commit ID in the browse UI (what you see [here](https://dev.clearlydefined.io/?sort=releaseDate&sortDesc=true) , or on the component page itself such as [this one](https://dev.clearlydefined.io/definitions/git/github/laravel/dusk/138e12604796d88f7fc2d7ee6f7c6bbcb08040e8)?

Feel free to ping me on Teams if it would be easier to show me what you are seeing.

**Comment by capfei** [comment]
@nellshamrell I'm referring to the component page. >_<

**Comment by nellshamrell** [comment]
@capfei aha! I see what you mean. @andrewrmn is it possible to make this workflow happen?

At the top of [this page](https://dev.clearlydefined.io/definitions/git/github/laravel/dusk/138e12604796d88f7fc2d7ee6f7c6bbcb08040e8), could clicking on the commit hash under "dusk" open a new tab that navigates to [this commit](https://github.com/laravel/dusk/tree/138e12604796d88f7fc2d7ee6f7c6bbcb08040e8).

And at the top of [this page](https://dev.clearlydefined.io/definitions/pypi/pypi/-/google-auth/2.5.0), clicking on the version number under google-auth open a new tab that navigates to [this pypi version page](https://pypi.org/project/google-auth/2.5.0/).

Looking up how this is done in the current UI - I suspect it is using the definition.urls.definition, but I will confirm.

**Comment by nellshamrell** [comment]
@andrewrmn I believe [this is where we generate the link](https://github.com/clearlydefined/website/blob/3741e54bbd786f16c1d8a474a535205683a3b598/src/components/Navigation/Ui/DefinitionRevision.js#L20) in the current UI.

**Comment by nellshamrell** [comment]
@ariel11 Yep! We're definitely adding that back in!

**Comment by ariel11** [comment]
Noting this here as another UI change: https://github.com/clearlydefined/website/issues/937.  Thanks!

**Comment by nellshamrell** [comment]
#937 won't be included in the initial launch of the new UI/UX, but it's something that can be looked into after.

**Comment by nellshamrell** [comment]
Hi @capfei and @ariel11 

@andrewrmn has fixed the package version link at the top of the component page and the edit license window not closing. Those changes are now deployed to dev.clearlydefined.io as well. He's working on the remaining issues :)

**Comment by bduranc** [comment]
There is another bug to report (I can create separate issue if need be).

If you go to the https://dev.clearlydefined.io/workspace page and click on the search bar, the page will go blank white.

The issue repeats itself even if you refresh the page and try again.

**Comment by nellshamrell** [comment]
Hi @bduranc! Thanks for the report. That won't block deploying the new UI/UX, but it is absolutely something we should track. Can you add a separate issue for it?

Thank you so much!

**Comment by bduranc** [comment]
Adding to @nellshamrell 's point: 

The workspace page can be useful for those who want to quickly look-up components and create/share work lists with others (especially useful when working with multiple components, including curation).

It also appears to provide the ability to generate and export notice files. I'm not too sure how one would access that functionality without this page (aside from by using the API).

**Comment by nellshamrell** [comment]
I consider these two issues blocking to deploy:

- [ ] When trying to edit the source information, clicking the edit pencil shows a white screen.
- [ ] Going to https://dev.clearlydefined.io/workspace and clicking on the search bar, the page goes to white

And this one not blocking, but something that I will add in immediately when @andrewrmn's work is complete.

- [ ] Add "Workspaces" back to navbar

**Comment by andrewrmn** [comment]
@nellshamrell Just put in a PR to fix the three above items.

**Comment by nellshamrell** [comment]
Thank you! I plan on merging and deploying this to production on Mon!

**Comment by nellshamrell** [comment]
@bduranc - could you move that to another issue? Going to close this one now that the UI has been deployed.
