### ISSUE TITLE
Erroneous dates showing in landing experience

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#948]
On first visiting clearlydefined.io it looks like we show the most recent versions of components in the data. Makes sense. Unfortunately it appears that there are several (as it happens) Ruby gems that have incorrect dates from the future. See screen shot below. As a result, the landing experience highlights incorrect data and can confuse visitors and give a bad first impression. 

Fixing the data would best solution but there will always be new incorrect data. We might consider, for this specific scenario, filtering out any component whose data is after `now()`.

![image](https://user-images.githubusercontent.com/10070956/154121818-567fe623-d6e0-4f05-9123-8744b08c71f2.png)

**Comment by qtomlinson** [comment]
Looked into the following cases:
1. gem/rubygems/-/gtl-sluggable/0.2.0, "date: 2103-09-30 00:00:00.000000000 Z" is in the metadata.txt extracted.
2. gem/rubygems/-/super-app/0.0.1, "date: 2024-04-04 00:00:00.000000000 Z" is in the metatdata.txt extracted.
3. git/github/rescrv/hyperdex/148334d53e76cc03808854050ebcb5addffe3c7c, "2025-06-04 08:58:21 -0400" is the committer date in git show command output

**Comment by qtomlinson** [comment]
For cases in rubygem, the incorrect release dates can be fixed by inferring this information from the file stat of the decompressed files (in addition to the current parsing from metadata.txt).

**Comment by qtomlinson** [comment]
For git/github/rescrv/hyperdex/148334d53e76cc03808854050ebcb5addffe3c7c, 
-the crawler extracted the date from github correctly.  This is consistent with the last commit date as Jun 4, 2025 at https://github.com/rescrv/HyperDex/commits/releases/0.4
-the service layer has the logic in place to ignore invalid release dates beyond the valid range (in summarizers).  Only need to retrigger the definition computation via
https://api.clearlydefined.io/definitions/git/github/rescrv/hyperdex/148334d53e76cc03808854050ebcb5addffe3c7c?force=true
In the resulting definition, the invalid release date is suppressed.
