### ISSUE TITLE
Make the UI more responsive

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#95]
Where to start?! There are elements that will be very hard to make repsonsive (e.g., the current Curation experience). However, much of the UI could/should be more responsive than it is.

Need an overall strategy from someone who's been there done that.

**Comment by mynameistechno** [comment]
Some questions to get us thinking about this stuff:

What device types do we want to support? For each device type we should consider the use cases. What functions make sense? E.g. do users want to curate on their phone while on a bus? 
- [ ] **Mobile** (<768px)
  - [ ] Browse
  - [ ] Inspect
  - [ ] Curate
  - [ ] Harvest
- [ ] **Tablet** (≥768px)
  - [ ] Browse
  - [ ] Inspect
  - [ ] Curate
  - [ ] Harvest
- [ ] **Desktop** (≥992px)
  - [ ] Browse
  - [ ] Inspect
  - [ ] Curate
  - [ ] Harvest
- [ ] **Large Desktop** (≥1200px)
  - [ ] Browse
  - [ ] Inspect
  - [ ] Curate
  - [ ] Harvest

**Comment by mynameistechno** [comment]
I took a stab at specifying the obvious stuff. Please update/add more specific actions, etc

**Comment by mynameistechno** [comment]
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app

**Comment by storrisi** [comment]
Probably related to #74 . The UI is not yet structured to be responsive.

**Comment by gianpaj** [comment]
Hi,
I'm looking into this issue.
Should we also make the harvest page responsive for mobile size devices?

<img src="https://user-images.githubusercontent.com/899175/53245570-c0511d80-36b6-11e9-98de-4d6773cff0ce.png" width="370" />

**Comment by dabutvin** [comment]
@gianpaj good point, though I wouldn't spend too much time on `/harvest`

I would prioritize the other pages first like the homepage, about, browse, definitions, etc

**Comment by storrisi** [comment]
Some work has been addressed in #484 , #486 , #487 and #488 

I'm wondering if we need this issue open to track all the work or maybe we can manage it by opening some specific issues.

**Comment by storrisi** [comment]
I'm closing this for now, we can track some other implementations in specific issues.
