### ISSUE TITLE
Discovered licenses are not separated on the definitions page

### ISSUE THREAD

**Issue by capfei** [clearlydefined/website#950]
Examples:
- https://clearlydefined.io/definitions/pypi/pypi/-/regex/0.1.20100217
- https://clearlydefined.io/definitions/git/github/mono/mono/abad3612068e7333956106e7be02d9ce9e346f92

<img width="395" alt="image" src="https://user-images.githubusercontent.com/5489711/154737397-d86efd3a-82be-4dbd-96c2-7db709bcc971.png">

**Comment by bduranc** [comment]
+1 also made same observation and reported in #926 

Can report it is still an issue.

**Comment by bduranc** [comment]
@capfei: I'd like to add the following to this issue:

In the old UI, if you want to view the full list licenses after truncation (...) you'd just hover and a pop-up would show all licenses.

Now there is no pop-up to show the truncated results. This causes problems for people wanting to see the full list of discovered licenses.

**Comment by capfei** [comment]
@bduranc Yes, definitely a problem! Same thing for the Attributions; can't even edit them.

**Comment by qtomlinson** [comment]
@bduranc @capfei There should also be a pop up to display the full list for "Discovered" and "Attribution" field in the component list view.
![image](https://user-images.githubusercontent.com/92891533/166805474-682e64b6-4dee-4e0e-baeb-201f9f2a3315.png)

**Comment by bduranc** [comment]
@qtomlinson : Correct, this is the behavior we'd like to see ideally for all fields that could be subject to truncation, including both of those you highlighted and declared license. It should also apply to the definition view (when you view the same in "full screen" - i.e. https://clearlydefined.io/definitions/git/github/golang/crypto/c084706c2272f3d44b722e988e70d4a58e60e7f4)

For further clarity, such behavior should be implemented as a tool-tip and not as any sort of blocking pop-up.

**Comment by bduranc** [comment]
This looks to be resolved on both the workspace and home pages for both declared license and copyright attribute fields.
https://clearlydefined.io/share/eJyTcuayT88s0QfijNIk/eLEAv38gtS80kxTfXPLtCTLJFNTIwNj41QDsxRzS2Oj5CSjpGQzozRjS5PERCNTE4vkpBQhBgDs3BQ2

![image](https://user-images.githubusercontent.com/31491646/211386098-17b40813-4957-45f3-a1a0-4d04992c3217.png)

**Comment by bduranc** [comment]
@qtomlinson : @capfei I do not appear able to close this issue since I did not open it originally :)

**Comment by capfei** [comment]
Much better! Thank you! 😃
