### ISSUE TITLE
Discovered license filter options are blank

### ISSUE THREAD

**Issue by capfei** [clearlydefined/website#953]
https://clearlydefined.io/definitions/git/github/nigels-com/glew/7d72257b0ff2aadab92d9b627beb44c36b072e52

<img width="590" alt="image" src="https://user-images.githubusercontent.com/5489711/155398788-ec90d01c-6df5-47c8-b89b-7b23a24dc551.png">

**Comment by fossygirl** [comment]
@qtomlinson  @bduranc The PR for this issue got merged. Let us know if that fixes this issue?

**Comment by capfei** [comment]
@fossygirl How long before it is live on the site?

**Comment by fossygirl** [comment]
I'm not sure. @jeffwilcox @MichaelTsengLZ  is there a regular deployment job?

**Comment by MichaelTsengLZ** [comment]
@capfei Deploy to prod just now. And will go to live in around 10 minutes.

**Comment by bduranc** [comment]
@fossygirl : It looks fixed to me. Thanks all

![Capture](https://user-images.githubusercontent.com/31491646/158227771-0cbc8840-8fed-4869-91d4-904b094c4fc2.PNG)

**Comment by capfei** [comment]
@fossygirl I can see it now. Thank you!
