### ISSUE TITLE
mark top right curation editor read only

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#98]
Figure out the monaco mechanism for making an editor read only and mark the modified curation editor (top right) as read only so people don't type there. (it sorta works but there are quirks)

**Comment by craigez** [comment]
I went to look at this, but I think it is stale. The curation page is commented out and it looks like you do it inline in the insights page.

**Comment by jeffmcaffer** [comment]
Indeed. sorry about that. we are in the process of cleaning up the backlog. Note that there are a set of [projects](https://github.com/orgs/clearlydefined/projects) that group things a bit. need also to apply some labels...
