### ISSUE TITLE
Curated declared licenses not updating on site [New UI]

### ISSUE THREAD

**Issue by capfei** [clearlydefined/website#982]
https://clearlydefined.io/definitions/npm/npmjs/@ag-grid-enterprise/all-modules/25.3.0/

This component has been curated as `OTHER` for the declared, but it still shows the PR as pending and the declared is still `NOASSERTION`. The PR merged back in December 2021.
https://github.com/clearlydefined/curated-data/pull/16073

Another PR for this version is not showing up in "Curations".
https://github.com/clearlydefined/curated-data/pull/19732

**Comment by capfei** [comment]
https://clearlydefined.io/definitions/nuget/nuget/-/MongoDB.Libmongocrypt/1.3.0 has the same issue.

**Comment by capfei** [comment]
Adding more:
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/go-systemd/v0.0.0-20190321100706-95778dfbb74e
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/pkg/v0.0.0-20180928190104-399ea9e2e55f
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fsmartystreets/assertions/v0.0.0-20180927180507-b2de0cb4f26d
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/go-semver/v0.3.0
•	https://clearlydefined.io/definitions/go/golang/honnef.co%2Fgo/tools/v0.0.1-2020.1.3
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fsmartystreets/goconvey/v1.6.4
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fchzyer/logex/v1.1.10
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/etcd/v3.3.10+incompatible
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fmunnerz/goautoneg/v0.0.0-20120707110453-a547fc61f48d
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fkisielk/gotool/v1.0.0
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fenvoyproxy/protoc-gen-validate/v0.1.0
•	https://clearlydefined.io/definitions/go/golang/github.com%2Fkr/logfmt/v0.0.0-20140226030751-b84e30acd515

**Comment by MichaelTsengLZ** [comment]
> Adding more: • https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/go-systemd/v0.0.0-20190321100706-95778dfbb74e • https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/pkg/v0.0.0-20180928190104-399ea9e2e55f • https://clearlydefined.io/definitions/go/golang/github.com%2Fsmartystreets/assertions/v0.0.0-20180927180507-b2de0cb4f26d • https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/go-semver/v0.3.0 • https://clearlydefined.io/definitions/go/golang/honnef.co%2Fgo/tools/v0.0.1-2020.1.3 • https://clearlydefined.io/definitions/go/golang/github.com%2Fsmartystreets/goconvey/v1.6.4 • https://clearlydefined.io/definitions/go/golang/github.com%2Fchzyer/logex/v1.1.10 • https://clearlydefined.io/definitions/go/golang/github.com%2Fcoreos/etcd/v3.3.10+incompatible • https://clearlydefined.io/definitions/go/golang/github.com%2Fmunnerz/goautoneg/v0.0.0-20120707110453-a547fc61f48d • https://clearlydefined.io/definitions/go/golang/github.com%2Fkisielk/gotool/v1.0.0 • https://clearlydefined.io/definitions/go/golang/github.com%2Fenvoyproxy/protoc-gen-validate/v0.1.0 • https://clearlydefined.io/definitions/go/golang/github.com%2Fkr/logfmt/v0.0.0-20140226030751-b84e30acd515
> 
> PR that links to the PRs for these components: [clearlydefined/curated-data#20489](https://github.com/clearlydefined/curated-data/pull/20489)

Here is the bugfix for all those Go components curations. https://github.com/clearlydefined/service/pull/943 

But since the logs of this component `https://clearlydefined.io/definitions/npm/npmjs/@ag-grid-enterprise/all-modules/25.3.0/` could not be found. It's a little bit hard to deal with that issue. @capfei if you find another example of the issue, feel free to let me know.

**Comment by capfei** [comment]
Thank you for fixing this @MichaelTsengLZ! 👍 Closing issue.
