### ISSUE TITLE
figure out CreateReactApp service worker caching deal

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#99]
the CRA system has a funky service worker that is supposed to help keep your app alive even if offline. However, this has implications for caching and new versions. It seems that people to no automatically get the latest version of the app when we roll out a new one. 

Given the likelihood of frequent changes, we need this to be much more responsive.

@iamwillbar can you help here?

I know some work was done previously but there still seem to be challenges.

Does seem like things eventually update but it can take 24 hours or something. If we need to change the service and the site together that could be quite challenging

**Comment by mynameistechno** [comment]
Do we even need this? Wondering if it's worth the added complexity. If the web server is configured properly and we use unique asset URLs to bust the cache (e.g. when you include the <script> you append a query param that is a hash of the contents), the browser will handle client caching and it might be good enough.

**Comment by iamwillbar** [comment]
@mynameistechno that's what I was wondering as well, my understanding is that the service worker is really to support PWAs which we're not (yet).

**Comment by jeffmcaffer** [comment]
Adding this to the Hackathon project as a potential work area. someone who knows about (or is interested in) this can likely configure something up. I don't think we really need this and it inhibits our ability to release new changes and users to get them.

**Comment by caabernathy** [comment]
An attempt to resolve this is in PR #213

**Comment by jeffmcaffer** [comment]
done
